force-app/main/default/objects/CalypsoData__c/CalypsoData__c.object-meta.xml
<CustomObject>
    <label>Calypso Data</label>
    <nameField>
        <displayFormat>CD-{00000}</displayFormat>
        <label>CData No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Calypso Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CalypsoData__c/fields/CD_TradeDate__c.field-meta.xml
<CustomField>
    <fullName>CD_TradeDate__c</fullName>
    <formula>IF(LEN(CD_TradeDateTime__c)&gt;=8, TRIM(LEFT(CD_TradeDateTime__c, FIND(&quot; &quot;, CD_TradeDateTime__c)-1)), &quot;#Error!&quot;)</formula>
    <label>Trade Date</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CalypsoData__c/fields/CD_TradeID__c.field-meta.xml
<CustomField>
    <fullName>CD_TradeID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Trade ID</label>
    <length>35</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/classes/ErrorLogHandlerController_Test.cls
@isTest
public class ErrorLogHandlerController_Test {
    static testMethod void ErrorLogHandlerController_TestMethod()
    {/*
        Account acc = TestData.createCalypsoAccount('Test Acc', '1245', '1234');
        insert acc;
        
        Contact con = TestData.createContact('1234');
        insert con;
        
        CalypsoData__c cdTestWID = TestData.createCalypsoData('1245', null, acc.Id);
        insert cdTestWID;
        
        ErrorLogHandlerController errorObj = new ErrorLogHandlerController();
        errorObj.actionFilter();
        CalypsoData__c cdTestWIDs = [SELECT CD_TradeDate__c FROM CalypsoData__c WHERE CD_TradeID__c ='111888'];
        System.debug('Trade Date>>>>'+cdTestWIDs.CD_TradeDate__c);
        System.assertEquals(system.today(), cdTestWIDs.CD_TradeDate__c);
        
        //ErrorLogHandlerController.wrapAccount errorWrapObj = new ErrorLogHandlerController.wrapAccount();
    */}
}