force-app/main/default/objects/MonthlyPostingSummary__c/MonthlyPostingSummary__c.object-meta.xml
<CustomObject>
    <description>Monthly Posting Summary  for Journal Line Items</description>
    <label>MonthlyPostingSummary</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MonthlyPostingSummary</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MonthlyPostingSummary__c/fields/MPS_Current_Posting_Month__c.field-meta.xml
<CustomField>
    <fullName>MPS_Current_Posting_Month__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Current Posting Month</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MonthlyPostingSummary__c/fields/MPS_Fiscal_Year__c.field-meta.xml
<CustomField>
    <fullName>MPS_Fiscal_Year__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Fiscal Year</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MonthlyPostingSummary__c/fields/MPS_Month__c.field-meta.xml
<CustomField>
    <fullName>MPS_Month__c</fullName>
    <label>MPS Month</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MonthlyPostingSummary__c/fields/MPS_Publish_Date__c.field-meta.xml
<CustomField>
    <fullName>MPS_Publish_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Publish Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MonthlyPostingSummary__c/fields/MPS_Status__c.field-meta.xml
<CustomField>
    <fullName>MPS_Status__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MonthlyPostingSummary__c/fields/MPS_Total_CB_Posting_Amount__c.field-meta.xml
<CustomField>
    <fullName>MPS_Total_CB_Posting_Amount__c</fullName>
    <label>Total CB Posting Amount</label>
    <summarizedField>PostingLineItem__c.PLI_Amount__c</summarizedField>
    <summaryFilterItems>
        <field>PostingLineItem__c.PLI_Cost_Centre__c</field>
        <operation>notEqual</operation>
        <value>250600</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>PostingLineItem__c.PLI_Cost_Centre__c</field>
        <operation>notEqual</operation>
        <value>902175</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>PostingLineItem__c.PLI_Corporate_Code__c</field>
        <operation>equals</operation>
        <value>00101</value>
    </summaryFilterItems>
    <summaryForeignKey>PostingLineItem__c.MonthlyPostingSummary__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/MonthlyPostingSummary__c/fields/MPS_Total_YB_Posting_Amount__c.field-meta.xml
<CustomField>
    <fullName>MPS_Total_YB_Posting_Amount__c</fullName>
    <label>Total YB Posting Amount</label>
    <summarizedField>PostingLineItem__c.PLI_Amount__c</summarizedField>
    <summaryFilterItems>
        <field>PostingLineItem__c.PLI_Cost_Centre__c</field>
        <operation>notEqual</operation>
        <value>250600</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>PostingLineItem__c.PLI_Cost_Centre__c</field>
        <operation>notEqual</operation>
        <value>902175</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>PostingLineItem__c.PLI_Corporate_Code__c</field>
        <operation>equals</operation>
        <value>00601</value>
    </summaryFilterItems>
    <summaryForeignKey>PostingLineItem__c.MonthlyPostingSummary__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/PostingLineItem__c/PostingLineItem__c.object-meta.xml
<CustomObject>
    <description>Posting Line Items - collection of Journal Line Items</description>
    <label>PostingLineItem</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PostingLineItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PostingLineItem__c/fields/MonthlyPostingSummary__c.field-meta.xml
<CustomField>
    <fullName>MonthlyPostingSummary__c</fullName>
    <label>MonthlyPostingSummary</label>
    <referenceTo>MonthlyPostingSummary__c</referenceTo>
    <relationshipLabel>PostingLineItems</relationshipLabel>
    <relationshipName>PostingLineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PostingLineItem__c/fields/PLI_Amount__c.field-meta.xml
<CustomField>
    <fullName>PLI_Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PostingLineItem__c/fields/PLI_Corporate_Code__c.field-meta.xml
<CustomField>
    <fullName>PLI_Corporate_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Corporate Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PostingLineItem__c/fields/PLI_Cost_Centre__c.field-meta.xml
<CustomField>
    <fullName>PLI_Cost_Centre__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Cost Centre</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PostingLineItem__c/fields/PLI_Cr_Dr__c.field-meta.xml
<CustomField>
    <fullName>PLI_Cr_Dr__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Cr/Dr</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PostingLineItem__c/fields/PLI_Description__c.field-meta.xml
<CustomField>
    <fullName>PLI_Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PostingLineItem__c/fields/PLI_GL_Account__c.field-meta.xml
<CustomField>
    <fullName>PLI_GL_Account__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>GL Account</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MonthlyPostingSummaryController.cls
/*
@Author        : Suhas
@Name          : MonthlyPostingSummaryController 
@Created Date  : 26th March 2018
@Description   : This is a Controller class for Monthly Postal Summary 
@version       : 1.0
*/

public class MonthlyPostingSummaryController {
    
   public transient Id  MPSId;
   public  MonthlyPostingSummary__c mpsDetails{get; set;}
   
    
    public ApexPages.StandardController stdCntrlr {get; set;}
   
    public MonthlyPostingSummaryController(ApexPages.StandardController controller) {	
        
         stdCntrlr = controller;
         MPSId = controller.getRecord().id;
       mpsDetails = new MonthlyPostingSummary__c();

        mpsDetails = getMPSDetails();

        if(mpsDetails.MPS_Status__c=='Published'){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO,' Monthly Postal Summary has been Published. Cannot be published again'));
        }
    }
    
    //This Method returns Monthly Posting Summary with 
    public MonthlyPostingSummary__c getMPSDetails(){
         mpsDetails = [SELECT Id,Name,MPS_Fiscal_Year__c,MPS_Publish_Date__c,MPS_Status__c,MPS_Total_CB_Posting_Amount__c,MPS_Total_YB_Posting_Amount__c,MPS_Month__c,MPS_Current_Posting_Month__c,
                       (SELECT Name, PLI_Amount__c,PLI_Corporate_Code__c,PLI_Cost_Centre__c,PLI_Cr_Dr__c,PLI_Description__c,PLI_GL_Account__c,MonthlyPostingSummary__c FROM PostingLineItems__r) FROM MonthlyPostingSummary__c
                       WHERE Id=:MPSId];
        return mpsDetails;
        
    }
    
     public PageReference FileExport()
     {
         Map<Integer,String> monthMap = new Map<Integer,String>{1 => 'January',2 => 'February',3 => 'March',4 => 'April',5 => 'May',
             6 => 'June',7 => 'July',8 => 'August',9 => 'Sept',10 => 'October',11 => 'November',12 => 'December'};
                 
                 if(Integer.valueOf(mpsDetails.MPS_Month__c)==System.today().Month()){
                     ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO,' Monthly Postal Summary has to be published after End of Month.'));
                     return null;
                 }else{
                     List<PostingLineItem__c> postingList = mpsDetails.PostingLineItems__r;
                     String  generatedCSVFileCB = '';
                     String  generatedCSVFileYB = '';
                     
                     String  fileHeader = '';
                     
                     String  fileRowCB = '';
                     String  fileRowYB = '';
                     
                     Id monthlyPostingSummaryCB;
                     //Id monthlyPostingSummaryYB;
                     
                     fileHeader = 'CORP' + '\t' + 'CC' + '\t' + 'GL A/C NO:' + '\t' + 'DESCRIPTION' + '\t' + 'AMTS' + '\t' + '0' + '\n';
                     

                     for(PostingLineItem__c eachPLI : postingList){
                         if(eachPLI.PLI_Corporate_Code__c == label.EOM_CB_Corp_Code)
                         {
                             
                             String cCode='\''+eachPLI.PLI_Corporate_Code__c;
                             String cCenter='\'' + eachPLI.PLI_Cost_Centre__c;
                             String gLAccount='\''+eachPLI.PLI_GL_Account__c;
                             Decimal pLIAmt = eachPLI.PLI_Amount__c.setScale(2);
                             Decimal dScale = pLIAmt - (long)pLIAmt;   
                             String pLIAmtStr = String.valueOf(pLIAmt);
                            /* if(!((dScale>0) || (dScale*(-1)>0))){

                                 pLIAmtStr = '="'+pLIAmtStr+'"'; 
                             }           */ 
                             
                             fileRowCB = fileRowCB + cCode + '\t'+cCenter  +'\t' 
                                 + gLAccount + '\t' + eachPLI.PLI_Description__c + '\t' + pLIAmtStr + '\t' + 
                                 eachPLI.PLI_Cr_Dr__c + '\n';

                             //monthlyPostingSummaryCB = eachPLI.MonthlyPostingSummary__c;
                         }
                         else if(eachPLI.PLI_Corporate_Code__c == label.EOM_YB_Corp_Code)
                         {
                             
                             String cCode='\''+eachPLI.PLI_Corporate_Code__c;
                             String cCenter='\'' + eachPLI.PLI_Cost_Centre__c;
                             String gLAccount='\''+eachPLI.PLI_GL_Account__c;
                             Decimal pLIAmt = eachPLI.PLI_Amount__c.setScale(2);
                             Decimal dScale = pLIAmt - (long)pLIAmt;
                             String pLIAmtStr = String.valueOf(pLIAmt);
                             /*if(!((dScale>0) || (dScale*(-1)>0))){

                                 pLIAmtStr = '="'+pLIAmtStr+'"'; 
                             } */
                             fileRowYB = fileRowYB + cCode + '\t' + cCenter +'\t'
                                 + gLAccount + '\t' + eachPLI.PLI_Description__c + '\t' + pLIAmtStr + '\t' + 
                                 eachPLI.PLI_Cr_Dr__c + '\n';
                             //monthlyPostingSummaryYB = eachPLI.MonthlyPostingSummary__c;
                         }
                     }
                     
                     generatedCSVFileCB = fileHeader + fileRowCB.toUpperCase();
                     generatedCSVFileYB = fileHeader + fileRowYB.toUpperCase();
                     
                     if(!String.isBlank(fileRowCB))
                     {
                         Attachment attachmentCB = new Attachment();
                         attachmentCB.Body = Blob.valueOf(generatedCSVFileCB);
                         
                         attachmentCB.Name = String.valueOf('CB Treasury Solns Jrnl '+(monthMap.get(Integer.valueOf(mpsDetails.MPS_Month__c))).left(3)+' '+(mpsDetails.Name).right(2)+'.xls');
                         attachmentCB.ParentId = MPSId; 
                         insert attachmentCB;
                         
                     }
                     
                     
                     
                     if(!String.isBlank(fileRowYB))
                     {
                         
                         
                         Attachment attachmentYB = new Attachment();
                         attachmentYB.Body = Blob.valueOf(generatedCSVFileYB);
                         attachmentYB.Name = String.valueOf('YB Treasury Solns Jrnl '+(monthMap.get(Integer.valueOf(mpsDetails.MPS_Month__c))).left(3)+' '+(mpsDetails.Name).right(2)+'.xls');
                         attachmentYB.ParentId = MPSId; 
                         insert attachmentYB;
                         
                     }
                     
                     mpsDetails.MPS_Publish_Date__c=System.today();
                     mpsDetails.MPS_Status__c='Published';
                     mpsDetails.MPS_Current_Posting_Month__c=false;
                     
                     update mpsDetails;
                     
                     Integer  nextMonth;
                     if(Integer.valueOf(mpsDetails.MPS_Month__c)<12){
                         nextMonth=Integer.valueOf(mpsDetails.MPS_Month__c)+1;
                     }else{
                         nextMonth=1;   
                     }
                     
                     List<MonthlyPostingSummary__c> monthlyPostingSummaryRecords = new List<MonthlyPostingSummary__c>([Select Id,Name,MPS_Fiscal_Year__c, MPS_Publish_Date__c,MPS_Status__c,MPS_Total_CB_Posting_Amount__c,
                                                                                                                       MPS_Total_YB_Posting_Amount__c,MPS_Current_Posting_Month__c,MPS_Month__c From MonthlyPostingSummary__c 
                                                                                                                       where MPS_Month__c= :nextMonth AND MPS_Status__c='Not Published'
                                                                                                                       ORDER BY MPS_Fiscal_Year__c ASC]);
                     
                     if(!monthlyPostingSummaryRecords.isEmpty()){
                         MonthlyPostingSummary__c monthlyPostingSummaryRecord = monthlyPostingSummaryRecords.get(0);
                         monthlyPostingSummaryRecord.MPS_Current_Posting_Month__c=true;
                         update monthlyPostingSummaryRecord;
                     }   
                     PageReference pg = new PageReference('/apex/MonthlyPostingSummary_VF?id='+mpsDetails.Id);        
                     pg.setRedirect(true);
                     return pg;
                 }
        
    }
    
    public PageReference cancelPublish()
    {

            Schema.DescribeSObjectResult result = MonthlyPostingSummary__c.SObjectType.getDescribe(); 
            PageReference pageRef = new PageReference('/' + result.getKeyPrefix() + '/o'); 
            pageRef.setRedirect(true); 
            return pageRef; 

        
    }
    
}