force-app/main/default/objects/PMTarget__c/PMTarget__c.object-meta.xml
<CustomObject>
    <label>PM Target</label>
    <nameField>
        <displayFormat>Target - {00000}</displayFormat>
        <label>PM Target No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PM Targets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PMTarget__c/fields/PMTar_CommActual__c.field-meta.xml
<CustomField>
    <fullName>PMTar_CommActual__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Commodity Actual</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PMTarget__c/fields/PMTar_CommTarget__c.field-meta.xml
<CustomField>
    <fullName>PMTar_CommTarget__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Commodity Target</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PMTarget__c/fields/PMTar_CRMActual__c.field-meta.xml
<CustomField>
    <fullName>PMTar_CRMActual__c</fullName>
    <defaultValue>0</defaultValue>
    <label>CRM Actual</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PMTarget__c/fields/PMTar_CRMTarget__c.field-meta.xml
<CustomField>
    <fullName>PMTar_CRMTarget__c</fullName>
    <defaultValue>0</defaultValue>
    <label>CRM Target</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PMTarget__c/fields/PMTar_EndDate__c.field-meta.xml
<CustomField>
    <fullName>PMTar_EndDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Plan End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PMTarget__c/fields/PMTar_FXDirectActual__c.field-meta.xml
<CustomField>
    <fullName>PMTar_FXDirectActual__c</fullName>
    <defaultValue>0</defaultValue>
    <label>FX Direct Actual</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PMTarget__c/fields/PMTar_FXDirectTarget__c.field-meta.xml
<CustomField>
    <fullName>PMTar_FXDirectTarget__c</fullName>
    <defaultValue>0</defaultValue>
    <label>FX Direct Target</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PMTarget__c/fields/PMTar_FXIndirectActual__c.field-meta.xml
<CustomField>
    <fullName>PMTar_FXIndirectActual__c</fullName>
    <defaultValue>0</defaultValue>
    <label>FX Indirect Actual</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PMTarget__c/fields/PMTar_FXIndirectTarget__c.field-meta.xml
<CustomField>
    <fullName>PMTar_FXIndirectTarget__c</fullName>
    <defaultValue>0</defaultValue>
    <label>FX Indirect Target</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PMTarget__c/fields/PMTar_FXRetail__c.field-meta.xml
<CustomField>
    <fullName>PMTar_FXRetail__c</fullName>
    <defaultValue>0</defaultValue>
    <label>FX Retail Target</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PMTarget__c/fields/PMTar_FXRetailActual__c.field-meta.xml
<CustomField>
    <fullName>PMTar_FXRetailActual__c</fullName>
    <defaultValue>0</defaultValue>
    <label>FX Retail Actual</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PMTarget__c/fields/PMTar_IRRMActual__c.field-meta.xml
<CustomField>
    <fullName>PMTar_IRRMActual__c</fullName>
    <defaultValue>0</defaultValue>
    <label>IRRM Actual</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PMTarget__c/fields/PMTar_IRRMTarget__c.field-meta.xml
<CustomField>
    <fullName>PMTar_IRRMTarget__c</fullName>
    <defaultValue>0</defaultValue>
    <label>IRRM Target</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PMTarget__c/fields/PMTar_IsCurrentFY__c.field-meta.xml
<CustomField>
    <fullName>PMTar_IsCurrentFY__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Current FY</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PMTarget__c/fields/PMTar_PMContact__c.field-meta.xml
<CustomField>
    <fullName>PMTar_PMContact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product Manager (Contact)</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Product Manager Contact type should be internal and Contact status should be active</errorMessage>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Internal</value>
        </filterItems>
        <filterItems>
            <field>Contact.Contact_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PM Targets</relationshipLabel>
    <relationshipName>PMTargets</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PMTarget__c/fields/PMTar_PMUser__c.field-meta.xml
<CustomField>
    <fullName>PMTar_PMUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Manager (User)</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PMTargets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PMTarget__c/fields/PMTar_StartDate__c.field-meta.xml
<CustomField>
    <fullName>PMTar_StartDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Plan Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PMTarget__c/fields/PMTar_Status__c.field-meta.xml
<CustomField>
    <fullName>PMTar_Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Ended</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
                <isActive>false</isActive>
                <label>Closed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PMTargetFiscalYearBatch.cls
/*
@Author        : Santhoshan
@Name          : PMTargetFiscalYearBatch
@Created Date  : 28th Feb 2018
@Description   : This is a Batch Class to convert the PM Targets to the Current Fiscal Year
@version       : 1.0
*/
global class PMTargetFiscalYearBatch implements Database.Batchable<sObject>{
    global Database.QueryLocator start(Database.BatchableContext BC){
        
        String query = 'SELECT PMTar_PMContact__c, Owner.Id,'+ 
            'PMTar_StartDate__c,PMTar_PMUser__c, PMTar_IsCurrentFY__c,'+
            'PMTar_EndDate__c, PMTar_FXDirectTarget__c,'+
            'PMTar_CRMTarget__c, PMTar_CommTarget__c, PMTar_IRRMTarget__c,'+
            'PMTar_FXIndirectTarget__c, PMTar_FXRetail__c,'+
            'PMTar_FXIndirectActual__c, PMTar_FXRetailActual__c,'+
            'PMTar_FXDirectActual__c, PMTar_CRMActual__c,'+
            'PMTar_CommActual__c, PMTar_IRRMActual__c,'+
            'PMTar_Status__c FROM PMTarget__c '+
            'WHERE PMTar_Status__c != \'Inactive\'';
        
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<PMTarget__c> scope){
        List<PMTarget__c> PMTarList = new List<PMTarget__c>();
        Integer fyStartMonth = CYBGUtilClass.fiscalYearStartMonth();
        Date startDate = CYBGUtilClass.findStartDateOfFY(System.Today(), fyStartMonth); 
        Date endDate = CYBGUtilClass.findEndDateOfFY(System.Today(), fyStartMonth);
        
        for(PMTarget__c eachRecPM : scope){
            if(eachRecPM.PMTar_Status__c.equals(System.Label.Active) || eachRecPM.PMTar_Status__c.equals(System.Label.Ended))
            {
                PMTarget__c newPMTar = new PMTarget__c();
                newPMTar.PMTar_PMContact__c = eachRecPM.PMTar_PMContact__c;
                newPMTar.OwnerId = eachRecPM.Owner.Id;
                newPMTar.PMTar_PMUser__c = eachRecPM.PMTar_PMUser__c;
                newPMTar.PMTar_StartDate__c = startDate;
                newPMTar.PMTar_EndDate__c = endDate;
                newPMTar.PMTar_IsCurrentFY__c = true;
                newPMTar.PMTar_FXDirectTarget__c = eachRecPM.PMTar_FXDirectTarget__c;
                newPMTar.PMTar_CRMTarget__c = eachRecPM.PMTar_CRMTarget__c;
                newPMTar.PMTar_CommTarget__c = eachRecPM.PMTar_CommTarget__c;
                newPMTar.PMTar_IRRMTarget__c = eachRecPM.PMTar_IRRMTarget__c;   
                newPMTar.PMTar_FXIndirectTarget__c = eachRecPM.PMTar_FXIndirectTarget__c; 
                newPMTar.PMTar_FXRetail__c = eachRecPM.PMTar_FXRetail__c; 
                newPMTar.PMTar_Status__c = System.Label.Active;
                PMTarList.add(newPMTar);
                eachRecPM.PMTar_IsCurrentFY__c = false;
                eachRecPM.PMTar_Status__c = System.Label.Inactive;
            }
            //else if(eachRecPM.PMTar_Status__c.equals(System.Label.Terminated))
            else{
                eachRecPM.PMTar_IsCurrentFY__c = false;
                eachRecPM.PMTar_Status__c = System.Label.Inactive;
            }
            
        }                                   
        if(!scope.isEmpty()){     
        	Database.SaveResult[] urList = Database.update(scope,false);
          	/*for (Database.SaveResult sr : urList) {
                if (sr.isSuccess()) {
                    System.debug('Successfully Inserted New PM Target. PM Target ID: ' + sr.getId());
                }
                else {
                    for(Database.Error err : sr.getErrors()) {
                        System.debug('The following error has occurred.');                    
                        System.debug(err.getStatusCode() + ': ' + err.getMessage());
                        System.debug('PM Target fields that affected this error: ' + err.getFields());
                    }
                }
            }*/
        }
        if(!PMTarList.isEmpty()){
        	Database.SaveResult[] srList = Database.insert(PMTarList,false);
        	/*for (Database.SaveResult ur : srList) {
                if (ur.isSuccess()) {
                    System.debug('Successfully Updated Old PM Target. PM Target ID: ' + ur.getId());
                }
                else {
                    for(Database.Error err : ur.getErrors()) {
                        System.debug('The following error has occurred.');                    
                        System.debug(err.getStatusCode() + ': ' + err.getMessage());
                        System.debug('PM Target fields that affected this error: ' + err.getFields());
                    }
                }
            }*/
        }                       
    }
    
    global void finish(Database.BatchableContext BC){
    }
}