force-app/main/default/objects/PMTarget__c/PMTarget__c.object-meta.xml
<CustomObject>
    <label>PM Target</label>
    <nameField>
        <displayFormat>Target - {00000}</displayFormat>
        <label>PM Target No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PM Targets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PMTarget__c/fields/PMTar_FiscalYear__c.field-meta.xml
<CustomField>
    <fullName>PMTar_FiscalYear__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Fiscal Year</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMTarget__c/fields/PMTar_FYEndDate__c.field-meta.xml
<CustomField>
    <fullName>PMTar_FYEndDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>FY End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PMTarget__c/fields/PMTar_FYStartDate__c.field-meta.xml
<CustomField>
    <fullName>PMTar_FYStartDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>FY Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PMTarget__c/fields/PMTar_PMContact__c.field-meta.xml
<CustomField>
    <fullName>PMTar_PMContact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product Manager (Contact)</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Product Manager Contact type should be internal and Contact status should be active</errorMessage>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Internal</value>
        </filterItems>
        <filterItems>
            <field>Contact.Contact_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PM Targets</relationshipLabel>
    <relationshipName>PMTargets</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PMTarget__c/fields/PMTar_Status__c.field-meta.xml
<CustomField>
    <fullName>PMTar_Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Ended</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
                <isActive>false</isActive>
                <label>Closed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PMTargetTriggerHandler.cls
/*
@Author        : Ramkumar M B
@Name          : PMTargetTriggerHandler
@Created Date  : 5th March 2018
@Description   : This is a Handler for PMTargetTrigger 
@version       : 1.0
*/
public class PMTargetTriggerHandler 
{
/**
* @description       Method to process and Validate the PM Target before Insert 
* @name              onAfterInsert
* @param             List<PMTarget__c>
* @return            void
* @throws            NA
*/ 
     Public static Void onBeforeInsert(List<PMTarget__c>pmTargetList)
    {
        Integer fyStartMonth = CYBGUtilClass.fiscalYearStartMonth(); 
        List<Id>pmIdList = new List<Id>();
        Map<Id,PMTarget__c> allActivePMTargetMap = activePMTargets();
        
        For(PMTarget__c eachPMTarget:pmTargetList)
        {
            eachPMTarget.PMTar_FiscalYear__c = CYBGUtilClass.findCurrentFY(System.Today(), fyStartMonth);
            eachPMTarget.PMTar_FYStartDate__c = CYBGUtilClass.findStartDateOfFY(System.Today(), fyStartMonth);        
            eachPMTarget.PMTar_FYEndDate__c = CYBGUtilClass.findEndDateOfFY(System.Today(), fyStartMonth);
            pmIdList.add(eachPMTarget.PMTar_PMContact__c);
            If(allActivePMTargetMap.containsKey(eachPMTarget.PMTar_PMContact__c))
            {
                eachPMTarget.adderror(Label.PMTargetDuplicateError+
                                      allActivePMTargetMap.get(eachPMTarget.PMTar_PMContact__c).Name);
            }
        }
        List<PMTarget__c> updatedList = WorkingDaysCalUtil.CalWorkingDaysForPMTarget(pmTargetList);        
    }
    public static Map<Id,PMTarget__c> activePMTargets(){
        Map<Id,PMTarget__c> pmTargetMap = new Map<Id,PMTarget__c>();
        For(PMTarget__c eachPMTarget :[Select PMTar_PMContact__c, Name, PMTar_Status__c
                                       From PMTarget__c where PMTar_Status__c =:System.Label.Active])
        {      
            pmTargetMap.put(eachPMTarget.PMTar_PMContact__c,eachPMTarget); 
        }
        return pmTargetMap;
    }
/**
* @description       Method to process and Validate the PM Target before Insert 
* @name              onBeforeUpdate
* @param             List<PMTarget__c>
* @return            void
* @throws            NA
*/  
    public static void onBeforeUpdate(List<PMTarget__c> pmTargetsList){
        List<PMTarget__c> updatedList = WorkingDaysCalUtil.CalWorkingDaysForPMTarget(pmTargetsList);        
    }

}