force-app/main/default/objects/PMTarget__c/PMTarget__c.object-meta.xml
<CustomObject>
    <label>PM Target</label>
    <nameField>
        <displayFormat>Target - {00000}</displayFormat>
        <label>PM Target No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PM Targets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PMTarget__c/fields/PMTar_CommTarget__c.field-meta.xml
<CustomField>
    <fullName>PMTar_CommTarget__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Commodity Target</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PMTarget__c/fields/PMTar_CommTargetTillDate__c.field-meta.xml
<CustomField>
    <fullName>PMTar_CommTargetTillDate__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Commodity Target To Date</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PMTarget__c/fields/PMTar_CommTarRemainAtClosure__c.field-meta.xml
<CustomField>
    <fullName>PMTar_CommTarRemainAtClosure__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Commodity Target Remaining At Closure</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PMTarget__c/fields/PMTar_CRMTarget__c.field-meta.xml
<CustomField>
    <fullName>PMTar_CRMTarget__c</fullName>
    <defaultValue>0</defaultValue>
    <label>CRM Target</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PMTarget__c/fields/PMTar_CRMTargetTillDate__c.field-meta.xml
<CustomField>
    <fullName>PMTar_CRMTargetTillDate__c</fullName>
    <defaultValue>0</defaultValue>
    <label>CRM Target To Date</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PMTarget__c/fields/PMTar_CRMTarRemainAtClosure__c.field-meta.xml
<CustomField>
    <fullName>PMTar_CRMTarRemainAtClosure__c</fullName>
    <defaultValue>0</defaultValue>
    <label>CRM Target Remaining At Closure</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PMTarget__c/fields/PMTar_EndDate__c.field-meta.xml
<CustomField>
    <fullName>PMTar_EndDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Plan End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PMTarget__c/fields/PMTar_FXDirectTarget__c.field-meta.xml
<CustomField>
    <fullName>PMTar_FXDirectTarget__c</fullName>
    <defaultValue>0</defaultValue>
    <label>FX Direct Target</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PMTarget__c/fields/PMTar_FXDirectTargetTillDate__c.field-meta.xml
<CustomField>
    <fullName>PMTar_FXDirectTargetTillDate__c</fullName>
    <defaultValue>0</defaultValue>
    <label>FX Direct Target To Date</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PMTarget__c/fields/PMTar_FXDirectTarRemainAtClosure__c.field-meta.xml
<CustomField>
    <fullName>PMTar_FXDirectTarRemainAtClosure__c</fullName>
    <defaultValue>0</defaultValue>
    <label>FX Direct Target Remaining At Closure</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PMTarget__c/fields/PMTar_FXIndirectTarget__c.field-meta.xml
<CustomField>
    <fullName>PMTar_FXIndirectTarget__c</fullName>
    <defaultValue>0</defaultValue>
    <label>FX Indirect Target</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PMTarget__c/fields/PMTar_FXIndirectTarRemainAtClosure__c.field-meta.xml
<CustomField>
    <fullName>PMTar_FXIndirectTarRemainAtClosure__c</fullName>
    <defaultValue>0</defaultValue>
    <label>FX Indirect Target Remaining At Closure</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PMTarget__c/fields/PMTar_FXIndirerctTargetTillDate__c.field-meta.xml
<CustomField>
    <fullName>PMTar_FXIndirerctTargetTillDate__c</fullName>
    <defaultValue>0</defaultValue>
    <label>FX Indirect Target To Date</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PMTarget__c/fields/PMTar_FXRetail__c.field-meta.xml
<CustomField>
    <fullName>PMTar_FXRetail__c</fullName>
    <defaultValue>0</defaultValue>
    <label>FX Retail Target</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PMTarget__c/fields/PMTar_FXRetailRemainingAtClosure__c.field-meta.xml
<CustomField>
    <fullName>PMTar_FXRetailRemainingAtClosure__c</fullName>
    <defaultValue>0</defaultValue>
    <label>FX Retail Target Remaining At Closure</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PMTarget__c/fields/PMTar_FXRetailTillDate__c.field-meta.xml
<CustomField>
    <fullName>PMTar_FXRetailTillDate__c</fullName>
    <defaultValue>0</defaultValue>
    <label>FX Retail Target To Date</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PMTarget__c/fields/PMTar_IRRMTarget__c.field-meta.xml
<CustomField>
    <fullName>PMTar_IRRMTarget__c</fullName>
    <defaultValue>0</defaultValue>
    <label>IRRM Target</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PMTarget__c/fields/PMTar_IRRMTargetTillDate__c.field-meta.xml
<CustomField>
    <fullName>PMTar_IRRMTargetTillDate__c</fullName>
    <defaultValue>0</defaultValue>
    <label>IRRM Target To Date</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PMTarget__c/fields/PMTar_IRRMTarRemainAtClosure__c.field-meta.xml
<CustomField>
    <fullName>PMTar_IRRMTarRemainAtClosure__c</fullName>
    <defaultValue>0</defaultValue>
    <label>IRRM Target Remaining At Closure</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PMTarget__c/fields/PMTar_Location__c.field-meta.xml
<CustomField>
    <fullName>PMTar_Location__c</fullName>
    <formula>TEXT(PMTar_PMUser__r.Location__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PM Location</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PMTarget__c/fields/PMTar_PMUser__c.field-meta.xml
<CustomField>
    <fullName>PMTar_PMUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Manager (User)</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PMTargets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PMTarget__c/fields/PMTar_StartDate__c.field-meta.xml
<CustomField>
    <fullName>PMTar_StartDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Plan Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PMTarget__c/fields/PMTar_Status__c.field-meta.xml
<CustomField>
    <fullName>PMTar_Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Ended</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
                <isActive>false</isActive>
                <label>Closed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PMTarget__c/fields/PMTar_Terminated__c.field-meta.xml
<CustomField>
    <fullName>PMTar_Terminated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Terminated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PMTarget__c/fields/PMTar_TerminationDate__c.field-meta.xml
<CustomField>
    <fullName>PMTar_TerminationDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Termination Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PMTarget__c/fields/PMTar_TotalWorkingDays__c.field-meta.xml
<CustomField>
    <fullName>PMTar_TotalWorkingDays__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total # Working Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PMTarget__c/fields/PMTar_WorkingDays__c.field-meta.xml
<CustomField>
    <fullName>PMTar_WorkingDays__c</fullName>
    <label># Working Days To Date</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/PMTargetWorkingDays.cls
/*
@Author        : Sushant
@Name          : PMTargetWorkingDays 
@Created Date  : 28th Feb 2018
@Description   : This is a Batch Class to get the # working days for PM Target
@version       : 1.0
*/
global class PMTargetWorkingDays implements Database.Batchable<sObject>{
/**
* @description       Method to get all Active and Closed PM target records where End date is greater than Today
* @name              start
* @param             Database.BatchableContext
* @return            Database.QueryLocator
* @throws            NA
*/     
    global Database.QueryLocator start(Database.BatchableContext BC){
		String query =  'SELECT ID, PMTar_PMUser__c, PMTar_Location__c, PMTar_StartDate__c, '+
                        'PMTar_TotalWorkingDays__c, PMTar_WorkingDays__c, PMTar_Terminated__c, '+
                        'PMTar_Status__c, PMTar_EndDate__c , PMTar_FXDirectTarget__c, '+
            			'PMTar_FXDirectTargetTillDate__c, PMTar_TerminationDate__c, '+
            			'PMTar_CRMTarget__c, PMTar_CRMTargetTillDate__c, PMTar_CommTarget__c, '+
            			'PMTar_CommTargetTillDate__c, PMTar_IRRMTarget__c, PMTar_IRRMTargetTillDate__c, '+
             			'PMTar_FXIndirectTarget__c, PMTar_FXIndirerctTargetTillDate__c,' +
            			'PMTar_FXRetail__c, PMTar_FXRetailTillDate__c,'+
            			'PMTar_FXDirectTarRemainAtClosure__c, PMTar_IRRMTarRemainAtClosure__c, '+
            			'PMTar_CRMTarRemainAtClosure__c, PMTar_CommTarRemainAtClosure__c, '+
            			'PMTar_FXIndirectTarRemainAtClosure__c, PMTar_FXRetailRemainingAtClosure__c '+
                        'FROM PMTarget__c WHERE PMTar_Status__c != \'Inactive\' AND PMTar_Terminated__c = false';        
               
        return Database.getQueryLocator(query);
    }
/**
* @description       Method to calculate No of working days till and Total No of working days .
* @name              execute
* @param             Database.BatchableContext,List<PMTarget__c>
* @return            Void
* @throws            NA
*/     
    global void execute(Database.BatchableContext BC, List<PMTarget__c> scope){
        List<PMTarget__c> updatePMTarList = WorkingDaysCalUtil.CalWorkingDaysForPMTarget(scope);
        Database.SaveResult[] urList = Database.update(updatePMTarList);                
        /*for (Database.SaveResult ur : urList) {
            if (ur.isSuccess()) {
                System.debug('Successfully Updated PM Target. PM Target ID: ' + ur.getId());
            }
            else {
                for(Database.Error err : ur.getErrors()) {
                    System.debug('The following error has occurred.');                    
                    System.debug(err.getStatusCode() + ': ' + err.getMessage());
                    System.debug('PM Target fields that affected this error: ' + err.getFields());
                }
            }

        }*/
        
    }
/**
* @description       Finish Method
* @name              finish
* @param             Database.BatchableContext
* @return            Void
* @throws            NA
*/     
    global void finish(Database.BatchableContext BC){
    }
}