force-app/main/default/objects/Account/fields/CIF__c.field-meta.xml
<CustomField>
    <fullName>CIF__c</fullName>
    <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
    <label>CIF</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Product</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/WID__c.field-meta.xml
<CustomField>
    <fullName>WID__c</fullName>
    <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
    <label>WID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Target.recordType-meta.xml
<RecordType>
    <fullName>Target</fullName>
    <active>true</active>
    <label>Target</label>
</RecordType>

force-app/main/default/objects/JournalLineItem__c/JournalLineItem__c.object-meta.xml
<CustomObject>
    <description>Journal Line Item</description>
    <label>Journal Line Item</label>
    <nameField>
        <displayFormat>J-{00000}</displayFormat>
        <label>Journal Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journal Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/JournalLineItem__c/fields/Journal_Amount__c.field-meta.xml
<CustomField>
    <fullName>Journal_Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/JournalLineItem__c/fields/Journal_Banker__c.field-meta.xml
<CustomField>
    <fullName>Journal_Banker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Banker</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Journal Line Items</relationshipLabel>
    <relationshipName>Journal_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/JournalLineItem__c/fields/Journal_BankerName__c.field-meta.xml
<CustomField>
    <fullName>Journal_BankerName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Banker Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JournalLineItem__c/fields/Journal_BankerOfficerCode__c.field-meta.xml
<CustomField>
    <fullName>Journal_BankerOfficerCode__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Banker Officer Code</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JournalLineItem__c/fields/Journal_Centre__c.field-meta.xml
<CustomField>
    <fullName>Journal_Centre__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Region</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JournalLineItem__c/fields/Journal_CIF__c.field-meta.xml
<CustomField>
    <fullName>Journal_CIF__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CIF</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JournalLineItem__c/fields/Journal_CorpCode__c.field-meta.xml
<CustomField>
    <fullName>Journal_CorpCode__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Corp Code</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JournalLineItem__c/fields/Journal_Customer__c.field-meta.xml
<CustomField>
    <fullName>Journal_Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Journal Line Items</relationshipLabel>
    <relationshipName>Journal_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/JournalLineItem__c/fields/Journal_Division__c.field-meta.xml
<CustomField>
    <fullName>Journal_Division__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Group</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JournalLineItem__c/fields/Journal_ETReference__c.field-meta.xml
<CustomField>
    <fullName>Journal_ETReference__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>ET Reference</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JournalLineItem__c/fields/Journal_FiscalYear__c.field-meta.xml
<CustomField>
    <fullName>Journal_FiscalYear__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Fiscal Year</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JournalLineItem__c/fields/Journal_GLAccount__c.field-meta.xml
<CustomField>
    <fullName>Journal_GLAccount__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>GL Account</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JournalLineItem__c/fields/Journal_Group__c.field-meta.xml
<CustomField>
    <fullName>Journal_Group__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Bank</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JournalLineItem__c/fields/Journal_JournalLineItem__c.field-meta.xml
<CustomField>
    <fullName>Journal_JournalLineItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Journal Line Item</label>
    <referenceTo>JournalLineItem__c</referenceTo>
    <relationshipLabel>Journal Line Items</relationshipLabel>
    <relationshipName>Journal_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/JournalLineItem__c/fields/Journal_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Journal_Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Journal Line Items</relationshipLabel>
    <relationshipName>Journal_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/JournalLineItem__c/fields/Journal_PMContact__c.field-meta.xml
<CustomField>
    <fullName>Journal_PMContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Manager(Contact)</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Journal Line Items (Product Manager(Contact))</relationshipLabel>
    <relationshipName>Journal_Line_Items1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/JournalLineItem__c/fields/Journal_PMContactName__c.field-meta.xml
<CustomField>
    <fullName>Journal_PMContactName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Product Manager Name(Contact)</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JournalLineItem__c/fields/Journal_PMTarget__c.field-meta.xml
<CustomField>
    <fullName>Journal_PMTarget__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PM Target</label>
    <referenceTo>PMTarget__c</referenceTo>
    <relationshipLabel>Journal Line Items</relationshipLabel>
    <relationshipName>Journal_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/JournalLineItem__c/fields/Journal_Product__c.field-meta.xml
<CustomField>
    <fullName>Journal_Product__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Product</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JournalLineItem__c/fields/Journal_ProductFamily__c.field-meta.xml
<CustomField>
    <fullName>Journal_ProductFamily__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Product Family</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JournalLineItem__c/fields/Journal_Region__c.field-meta.xml
<CustomField>
    <fullName>Journal_Region__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Division</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JournalLineItem__c/fields/Journal_ReversalReason__c.field-meta.xml
<CustomField>
    <fullName>Journal_ReversalReason__c</fullName>
    <label>Reversal Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trade Updated by Treasury User</fullName>
            </value>
            <value>
                <fullName>Trade Updated by Calypso</fullName>
            </value>
            <value>
                <fullName>Banker changed through TDM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/JournalLineItem__c/fields/Journal_Team__c.field-meta.xml
<CustomField>
    <fullName>Journal_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Centre</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Journal Line Items</relationshipLabel>
    <relationshipName>Journal_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/JournalLineItem__c/fields/Journal_TeamName__c.field-meta.xml
<CustomField>
    <fullName>Journal_TeamName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Business Centre Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JournalLineItem__c/fields/Journal_TradeID__c.field-meta.xml
<CustomField>
    <fullName>Journal_TradeID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Trade ID</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JournalLineItem__c/fields/Journal_TransactionType__c.field-meta.xml
<CustomField>
    <fullName>Journal_TransactionType__c</fullName>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Debit</fullName>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/JournalLineItem__c/fields/Journal_TSM__c.field-meta.xml
<CustomField>
    <fullName>Journal_TSM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FRSM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Journal_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/JournalLineItem__c/fields/Journal_TSMManager__c.field-meta.xml
<CustomField>
    <fullName>Journal_TSMManager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FRSM Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Journal_Line_Items1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/JournalLineItem__c/fields/Journal_TSMManagerName__c.field-meta.xml
<CustomField>
    <fullName>Journal_TSMManagerName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>FRSM Manager Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JournalLineItem__c/fields/Journal_TSMName__c.field-meta.xml
<CustomField>
    <fullName>Journal_TSMName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>FRSM Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/JournalLineItem__c/fields/Journal_TSMTarget__c.field-meta.xml
<CustomField>
    <fullName>Journal_TSMTarget__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FRSM Target</label>
    <referenceTo>TSMTarget__c</referenceTo>
    <relationshipLabel>Journal Line Items</relationshipLabel>
    <relationshipName>Journal_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/JournalLineItem__c/fields/Journal_WID__c.field-meta.xml
<CustomField>
    <fullName>Journal_WID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>WID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/isQ6Available__c.field-meta.xml
<CustomField>
    <fullName>isQ6Available__c</fullName>
    <formula>IF(Account.Officer_Code__c != null, true, false)</formula>
    <label>Is Q6 Available</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opp_CorpCode__c.field-meta.xml
<CustomField>
    <fullName>Opp_CorpCode__c</fullName>
    <formula>IF( NOT( ISBLANK( TEXT(Opp_BankName__c) ) ) , TEXT(Opp_BankName__c) , 
IF( NOT( ISBLANK( TEXT(Account.Branch__c ) ) ), 
IF(TEXT(Account.Branch__c) = &#39;Clydesdale Bank&#39; , &#39;CB&#39;, 
IF(TEXT(Account.Branch__c) = &#39;Yorkshire Bank&#39; , &#39;YB&#39;, &#39;&#39;)), &#39;&#39;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Corp Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opp_ETRef__c.field-meta.xml
<CustomField>
    <fullName>Opp_ETRef__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ET Ref</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opp_GLAccountNumber__c.field-meta.xml
<CustomField>
    <fullName>Opp_GLAccountNumber__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>GL Account Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Product.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Vanilla Option</fullName>
    </customValue>
    <customValue>
        <fullName>Participating Forward</fullName>
    </customValue>
    <customValue>
        <fullName>Partial Forward</fullName>
    </customValue>
    <customValue>
        <fullName>Advantage Forward</fullName>
    </customValue>
    <customValue>
        <fullName>Dynamic Forward</fullName>
    </customValue>
    <customValue>
        <fullName>Bonus Forward</fullName>
    </customValue>
    <customValue>
        <fullName>Leverage Product</fullName>
    </customValue>
    <customValue>
        <fullName>Knock Out Forward</fullName>
    </customValue>
    <customValue>
        <fullName>Dual Currency Deposit (DCD)</fullName>
    </customValue>
    <customValue>
        <fullName>Non- Deliverable Forward (NDF)</fullName>
    </customValue>
    <customValue>
        <fullName>Commodity Price Cap</fullName>
    </customValue>
    <customValue>
        <fullName>Commodity Price Swap</fullName>
    </customValue>
    <customValue>
        <fullName>Interest Rate Cap</fullName>
    </customValue>
    <customValue>
        <fullName>Interest Rate Collar</fullName>
    </customValue>
    <customValue>
        <fullName>Interest Rate Swap</fullName>
    </customValue>
    <customValue>
        <fullName>Floating Rate Loan</fullName>
    </customValue>
    <customValue>
        <fullName>Fixed Rate Loan</fullName>
    </customValue>
    <customValue>
        <fullName>Vanilla Spot</fullName>
    </customValue>
    <customValue>
        <fullName>Vanilla Forward</fullName>
    </customValue>
    <customValue>
        <fullName>Aluminium Swap</fullName>
    </customValue>
    <customValue>
        <fullName>Aluminium Cap</fullName>
    </customValue>
    <customValue>
        <fullName>Copper Swap</fullName>
    </customValue>
    <customValue>
        <fullName>Copper Cap</fullName>
    </customValue>
    <customValue>
        <fullName>Nickel Swap</fullName>
    </customValue>
    <customValue>
        <fullName>Nickel Cap</fullName>
    </customValue>
    <customValue>
        <fullName>Zinc Swap</fullName>
    </customValue>
    <customValue>
        <fullName>Zinc Cap</fullName>
    </customValue>
    <customValue>
        <fullName>Gas Oil Swap</fullName>
    </customValue>
    <customValue>
        <fullName>Gas Oil Cap</fullName>
    </customValue>
    <customValue>
        <fullName>Jet Fuel Swap</fullName>
    </customValue>
    <customValue>
        <fullName>FX</fullName>
    </customValue>
    <customValue>
        <fullName>FXForward</fullName>
    </customValue>
    <customValue>
        <fullName>FXSwap</fullName>
    </customValue>
    <customValue>
        <fullName>FXFlexiForward</fullName>
    </customValue>
    <masterLabel>Product</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CYBGUtilClass.cls
/*
@Author        : Sushant
@Name          : CYBGUtilClass
@Created Date  : 12th Jan 2018
@Description   : This is a Util Class 
@version       : 1.0
*/

Public class CYBGUtilClass
{
    public static boolean runBeforeTrigger = True;
    public static boolean runAfterTrigger = True;
    public static boolean firstRun = true; 
    public static boolean beforeTriggerRun = true;
    public static boolean accountFirstRun = true;   
    
   /**
    * @description       Method to get the Current FY start month
    * @name              fiscalYearStartMonth
    * @param             null
    * @return            Integer
    * @throws            NA
    */ 
    public static Integer fiscalYearStartMonth(){
        Integer fiscalYearStartMonth = [select FiscalYearStartMonth from Organization 
                                        where id=:Userinfo.getOrganizationId()].FiscalYearStartMonth;
        return fiscalYearStartMonth;
    }
    
   /**
    * @description       Method to get the Current FY
    * @name              findCurrentFY
    * @param             Date, Integer
    * @return            String 
    * @throws            NA
    */     
    Public Static String findCurrentFY(Date todayDate, Integer fyStartMonth ){
        Integer currentMonth = todayDate.month();
        Integer currentYear = todayDate.year() ;
        String currentFY;
        if(currentMonth >= fyStartMonth ){            
            currentFY = Label.Fiscal_Year + (String.valueOf(currentYear + 1)).right(2);            
        }
        else{
            currentFY = Label.Fiscal_Year + (String.valueOf(currentYear)).right(2);
        }
        return currentFY;
    }
    
    /**
    * @description       Method to get the Start Date of FY
    * @name              findStartDateOfFy
    * @param             Date, Integer
    * @return            Date 
    * @throws            NA
    */     
    Public Static Date findStartDateOfFY(Date todayDate, Integer fyStartMonth ){
        Integer currentMonth = todayDate.month();
        Integer currentYear = todayDate.year();
        if(currentMonth >= fyStartMonth ){            
            currentYear = currentYear;            
        }
        else{
            currentYear = currentYear - 1;
        }   
        Date StartDate = date.newInstance(currentYear, fyStartMonth , 1 );
        return StartDate;
    }
    
    /**
    * @description       Method to get the Start Date of FY
    * @name              findStartDateOfFy
    * @param             Date, Integer
    * @return            Date 
    * @throws            NA
    */     
    Public Static Date findEndDateOfFY(Date todayDate, Integer fyStartMonth ){
        Integer currentMonth = todayDate.month();
        Integer currentYear = todayDate.year();
        if(currentMonth >= fyStartMonth ){            
            currentYear = currentYear + 1;            
        }
        else{
            currentYear = currentYear;
        }   
        Integer numberOfDays = Date.daysInMonth(currentYear , fyStartMonth -1);
        Date endDate = date.newInstance(currentYear, fyStartMonth -1 , numberOfDays );
        return endDate;
    }
    
   /**
    * @description       This Method will get the object field data for Journal Line Object 
    *                    and create a local copy of Journal and return the same .
    * @name              createJournalLineItemsRecords
    * @param              
    * @return            JournalLineItem__c
    * @throws            NA
    */ 
    Public static JournalLineItem__c createJournalLineItemsRecords(Id opportunityIdValue,Id bankerId,Decimal amount,
                                                                   String creditDebit,Id journalId,String fiscalYear,
                                                                   String tradeID,String bankerName,String bankerOfficerCode,
                                                                   String cif,String corpCode,Id customer,
                                                                   String etReference,String glAccountNo,String product,
                                                                   String productFamily,Id productManagerContact,
                                                                   String productManagerContactName,Id team,
                                                                   String teamName,Id tsm,String TSMName, 
                                                                   Id tsmManager,String tsmManagerName,
                                                                   String wid,String centreName,String regionName,
                                                                   String divisionName,String groupName,Id pmTarget,Id tsmTarget,String reversalReson)
    {
        
        system.debug('Inside Journal Creation');

        String fixGLAccount ='';
        if(productFamily == label.RecordTypeFXCash || 
           productFamily == label.RecordTypeIRRM || productFamily == label.RecordTypeCommodity){
               if(product=='FX' || product=='FXForward'|| product=='FXSwap' ||product=='FXFlexiForward'){
                   fixGLAccount =label.FX_GL_Account; 
                   System.debug('its a Fixed GL Account');
               }else{
                   fixGLAccount =label.Common_GL_Account; 
               } 
           }else{
                fixGLAccount =glAccountNo;
           }
        JournalLineItem__c journalLineItemObject = New JournalLineItem__c();
        journalLineItemObject.Journal_JournalLineItem__c = journalId;
        journalLineItemObject.Journal_Opportunity__c = opportunityIdValue;
        journalLineItemObject.Journal_Banker__c = bankerId;
        system.debug('Journal ******* Banker'+journalLineItemObject.Journal_Banker__c);
        journalLineItemObject.Journal_Amount__c = amount;
        system.debug('Journal ******* Amount'+journalLineItemObject.Journal_Amount__c);
        journalLineItemObject.Journal_TransactionType__c = creditDebit;
        journalLineItemObject.Journal_FiscalYear__c = fiscalYear;       
        journalLineItemObject.Journal_TradeID__c = tradeID;
        journalLineItemObject.Journal_BankerName__c = bankerName;
        journalLineItemObject.Journal_BankerOfficerCode__c = bankerOfficerCode;
        journalLineItemObject.Journal_CIF__c = cif;
        journalLineItemObject.Journal_CorpCode__c = corpCode;
        journalLineItemObject.Journal_Customer__c = customer;
        journalLineItemObject.Journal_ETReference__c = etReference;
        journalLineItemObject.Journal_GLAccount__c = fixGLAccount;
        journalLineItemObject.Journal_Product__c = product;
        journalLineItemObject.Journal_ProductFamily__c = productFamily;
        journalLineItemObject.Journal_PMContact__c = productManagerContact;
        journalLineItemObject.Journal_PMContactName__c = productManagerContactName;        
        journalLineItemObject.Journal_Team__c = team;
        journalLineItemObject.Journal_TeamName__c = teamName;
        journalLineItemObject.Journal_TSM__c = tsm;
        journalLineItemObject.Journal_TSMName__c = TSMName;
        journalLineItemObject.Journal_TSMManager__c = tsmManager;
        journalLineItemObject.Journal_TSMManagerName__c = tsmManagerName;
        journalLineItemObject.Journal_WID__c            = wid;
        journalLineItemObject.Journal_Centre__c         = centreName;
        journalLineItemObject.Journal_Region__c         = regionName;
        journalLineItemObject.Journal_Division__c       = divisionName;
        journalLineItemObject.Journal_Group__c          = groupName;
        journalLineItemObject.Journal_PMTarget__c       = pmTarget;
        journalLineItemObject.Journal_TSMTarget__c      = tsmTarget;
        journalLineItemObject.Journal_ReversalReason__c  = reversalReson;
        
        
        system.debug('Returning this value'+journalLineItemObject);
        return journalLineItemObject;
    }
   /**
    * @description       This Method will fetch and retrun the opportunity details as a Map for the requested Opportunity Ids
    * @name              getOpportunityDetails
    * @param             List<Id>
    * @return            Map<Id,Opportunity>
    * @throws            NA
    */ 
    Public static Map<Id,Opportunity> getOpportunityDetails(List<Id>opportunityIdList){        
        Map<Id,Opportunity> retrunOpportunityMap= new Map<Id,Opportunity>([Select Id,AccountId,Name,Amount,Product__c,RecordType.Name,
                                                                           Owner.id,ownerId,Owner.FirstName,Owner.LastName,
                                                                           Owner.Manager.Id,Opp_CorpCode__c,Opp_ETRef__c,CloseDate,
                                                                           Owner.Manager.FirstName,Opp_GLAccountNumber__c,isQ6Available__c,
                                                                           Owner.Manager.LastName,Opp_TradeID__c,(Select Id,Name,Journal_PMContact__c,Journal_PMContactName__c,
                                                                                                                     Journal_PMTarget__c,Journal_TSMTarget__c ,Journal_Banker__c,
                                                                                                                     Journal_Amount__c,Journal_Team__c,Journal_Centre__c,Journal_Region__c,
                                                                                                                     Journal_TeamName__c,Journal_Division__c,Journal_Group__c From Journal_Line_Items__R 
                                                                                                                     Order By Name DESC) from Opportunity 
                                                                           where Id IN :opportunityIdList]); 
        
        return retrunOpportunityMap;
    }
    
   /**
    * @description       This Method will fetch and retrun the Account details as a Map for the requested 
    *                     Account Ids
    * @name              getAccountDetails
    * @param             List<Id>
    * @return            Map<Id,Account>
    * @throws            NA
    */        
    Public static Map<Id,Account> getAccountDetails(List<Id>accountIdList){        
        Map<Id,Account> retrunAccountMap= new Map<Id,Account>([Select Id,Name,RM_Name__c,FX_Manager__c,
                                                               FX_Manager__r.FirstName,FX_Manager__r.LastName,
                                                               IRRM_Manager__c,IRRM_Manager__r.FirstName,
                                                               IRRM_Manager__r.LastName,WID__c,CIF__c,BankerAdded__c,
                                                               Commodity_Manager__c,Commodity_Manager__r.FirstName,
                                                               Commodity_Manager__r.LastName,RM_Name__r.Officer_Code__c,
                                                               RM_Name__r.Firstname,RM_Name__r.Lastname, 
                                                               RM_Name__r.Con_Team__c,RM_Name__r.Name,
                                                               RM_Name__r.Con_Team__r.Name,
                                                               RM_Name__r.Con_Centre__c,OwnerId,
                                                               RM_Name__r.Con_Region__c,
                                                               RM_Name__r.Con_Division__c,
                                                               RM_Name__r.Con_Group__c
                                                               From Account 
                                                               where Id In :accountIdList]); 
        return retrunAccountMap;
    }
    
   /**
    * @description       This Method will update the PM Target details based on the Journal Amount
    * @name              updatePMTarget
    * @param             PMTarget__c,JournalLineItem__c
    * @return            PMTarget__c
    * @throws            NA
    */        
    public static PMTarget__c updatePMTarget(PMTarget__c pmTargetRecord,JournalLineItem__c journalRecord){
        If(journalRecord.Journal_ProductFamily__c == label.RecordTypeCRM){
            pmTargetRecord.PMTar_CRMActual__c = pmTargetRecord.PMTar_CRMActual__c   + 
                journalRecord.Journal_Amount__c;                
        }
        else if(journalRecord.Journal_ProductFamily__c == label.RecordTypeFXCash){
            
            System.debug('This is inside FX Cash');
              if(journalRecord.Journal_BranchNumber__c==System.Label.CBDirectDealingClient || journalRecord.Journal_BranchNumber__c ==System.Label.YBDirectDealingClient){
            pmTargetRecord.PMTar_FXDirectActual__c = (pmTargetRecord.PMTar_FXDirectActual__c!=Null?pmTargetRecord.PMTar_FXDirectActual__c:0) + 
                journalRecord.Journal_Amount__c;
            }else if((journalRecord.Journal_BranchNumber__c!=System.Label.CBDirectDealingClient || journalRecord.Journal_BranchNumber__c !=System.Label.YBDirectDealingClient) && journalRecord.Journal_IsQ6Available__c==True)
            {     system.debug('Inside Indirect FX');
              
                       if(journalRecord.Journal_Amount__c < 0 && journalRecord.Journal_Banker__c==Null)
                       {
                       pmTargetRecord.PMTar_FXRetailActual__c = pmTargetRecord.PMTar_FXRetailActual__c + journalRecord.Journal_Amount__c;

                       }else
                       {
                            pmTargetRecord.PMTar_FXIndirectActual__c = (pmTargetRecord.PMTar_FXIndirectActual__c!=Null?pmTargetRecord.PMTar_FXIndirectActual__c:0) + 
                            journalRecord.Journal_Amount__c;
                       }             
             
             
               
            }else if((journalRecord.Journal_BranchNumber__c!=System.Label.CBDirectDealingClient || journalRecord.Journal_BranchNumber__c !=System.Label.YBDirectDealingClient) && journalRecord.Journal_IsQ6Available__c==false){
                SYSTEM.debug('Inside Retail');
                //pmTargetRecord.PMTar_FXRetailActual__c = (pmTargetRecord.PMTar_FXRetailActual__c!=Null?pmTargetRecord.PMTar_FXRetailActual__c:0) + 
                pmTargetRecord.PMTar_FXRetailActual__c = pmTargetRecord.PMTar_FXRetailActual__c + journalRecord.Journal_Amount__c;
                system.debug('PM Target After Update'+pmTargetRecord.PMTar_FXRetailActual__c);
            }         
        }
        else if(journalRecord.Journal_ProductFamily__c == label.RecordTypeCommodity){
            pmTargetRecord.PMTar_CommActual__c = pmTargetRecord.PMTar_CommActual__c   + 
                journalRecord.Journal_Amount__c;            
        }
       else if(journalRecord.Journal_ProductFamily__c == label.RecordTypeIRRM)
        {
            pmTargetRecord.PMTar_IRRMActual__c = pmTargetRecord.PMTar_IRRMActual__c  + 
                journalRecord.Journal_Amount__c;     
        }else
        {
            //Do not do anything
        }
        
        system.debug('rETURING THIS Target'+pmTargetRecord);
        return pmTargetRecord;
    }
    
   /**
    * @description       This Method will update the TSM Target details based on the Journal Amount
    * @name              updateTSMTarget
    * @param             TSMTarget__c,JournalLineItem__c
    * @return            TSMTarget__c
    * @throws            NA
    */   
    public static TSMTarget__c updateTSMTarget(TSMTarget__c tsmTargetRecord,JournalLineItem__c journalRecord){ 
        
        system.debug('TSM Target in CYBG Util class'+tsmTargetRecord);
        system.debug('TSM Target in CYBG Util class'+journalRecord);
        system.debug('Banker Updated value is '+journalRecord.Journal_BankerAdded__c);
        If(journalRecord.Journal_ProductFamily__c == label.RecordTypeCRM){
            tsmTargetRecord.TSMTar_CRMActual__c = tsmTargetRecord.TSMTar_CRMActual__c + 
                journalRecord.Journal_Amount__c;
        }
        else if(journalRecord.Journal_ProductFamily__c == label.RecordTypeFXCash)
        {

            if(journalRecord.Journal_BranchNumber__c==System.Label.CBDirectDealingClient || journalRecord.Journal_BranchNumber__c ==System.Label.YBDirectDealingClient){
            tsmTargetRecord.TSMTar_FXDirectActual__c = (tsmTargetRecord.TSMTar_FXDirectActual__c!=Null?tsmTargetRecord.TSMTar_FXDirectActual__c:0) + 
                journalRecord.Journal_Amount__c;
                
                
            }else if((journalRecord.Journal_BranchNumber__c!=System.Label.CBDirectDealingClient || journalRecord.Journal_BranchNumber__c !=System.Label.YBDirectDealingClient) && journalRecord.Journal_IsQ6Available__c==True)
            {
                SYSTEM.debug('Fixed Q6 is under CYBG Utill'+journalRecord.Journal_IsQ6Available__c);
                if(journalRecord.Journal_Amount__c < 0 && journalRecord.Journal_Banker__c==Null)
                {
                    system.debug('Journal Amount is less than zero');
                    system.debug('Each Banker Updated '+journalRecord.Journal_BankerAdded__c);
                  tsmTargetRecord.TSMTar_FXRetailActual__c = (tsmTargetRecord.TSMTar_FXRetailActual__c!=Null?tsmTargetRecord.TSMTar_FXRetailActual__c:0) + 
                  journalRecord.Journal_Amount__c;                    
                }else{
                    system.debug('Positive amount and inside Else Condition');
                    tsmTargetRecord.TSMTar_FXIndirectActual__c = (tsmTargetRecord.TSMTar_FXIndirectActual__c!=Null?tsmTargetRecord.TSMTar_FXIndirectActual__c:0) + 
                    journalRecord.Journal_Amount__c;
                    
                }
                /*tsmTargetRecord.TSMTar_FXIndirectActual__c = (tsmTargetRecord.TSMTar_FXIndirectActual__c!=Null?tsmTargetRecord.TSMTar_FXIndirectActual__c:0) + 
                journalRecord.Journal_Amount__c;*/
            }else if((journalRecord.Journal_BranchNumber__c!=System.Label.CBDirectDealingClient || journalRecord.Journal_BranchNumber__c !=System.Label.YBDirectDealingClient) && journalRecord.Journal_IsQ6Available__c==false){
                
                tsmTargetRecord.TSMTar_FXRetailActual__c = (tsmTargetRecord.TSMTar_FXRetailActual__c!=Null?tsmTargetRecord.TSMTar_FXRetailActual__c:0) + 
                journalRecord.Journal_Amount__c;
            }
        }
        else if(journalRecord.Journal_ProductFamily__c == label.RecordTypeCommodity)
        {
            tsmTargetRecord.TSMTar_CommActual__c = tsmTargetRecord.TSMTar_CommActual__c + 
                journalRecord.Journal_Amount__c;
        }
        else if(journalRecord.Journal_ProductFamily__c == label.RecordTypeIRRM)
        {
            tsmTargetRecord.TSMTar_IRRMActual__c = tsmTargetRecord.TSMTar_IRRMActual__c + 
                journalRecord.Journal_Amount__c;
        }else
        {
            //Do not do anything
        }
        
        
        return tsmTargetRecord;
    }
    
    
}