force-app/main/default/objects/Account/fields/CIF__c.field-meta.xml
<CustomField>
    <fullName>CIF__c</fullName>
    <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
    <label>CIF</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Commodity_Manager__c.field-meta.xml
<CustomField>
    <fullName>Commodity_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Commodity Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Commodity Manager)</relationshipLabel>
    <relationshipName>CommodityManagers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/FX_Manager__c.field-meta.xml
<CustomField>
    <fullName>FX_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FX Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (FX Manager)</relationshipLabel>
    <relationshipName>FXManagers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/IRRM_Manager__c.field-meta.xml
<CustomField>
    <fullName>IRRM_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>IRRM Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (IRRM Manager)</relationshipLabel>
    <relationshipName>IRRMManagers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Officer_Code__c.field-meta.xml
<CustomField>
    <fullName>Officer_Code__c</fullName>
    <formula>RM_Name__r.Officer_Code__c</formula>
    <label>Officer Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/OldCommManagerId__c.field-meta.xml
<CustomField>
    <fullName>OldCommManagerId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Old Commodity Manager Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/OldFXManagerId__c.field-meta.xml
<CustomField>
    <fullName>OldFXManagerId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Old FX Manager Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/OldIRRMManagerId__c.field-meta.xml
<CustomField>
    <fullName>OldIRRMManagerId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Old IRRM Manager Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/OldTSMId__c.field-meta.xml
<CustomField>
    <fullName>OldTSMId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Old TSM Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Product</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/RM_Name__c.field-meta.xml
<CustomField>
    <fullName>RM_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RM Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND 2</booleanFilter>
        <errorMessage>Please select an active Banker of a respective branch.</errorMessage>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Banker</value>
        </filterItems>
        <filterItems>
            <field>Contact.Contact_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Banker)</relationshipLabel>
    <relationshipName>AccountBanker</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/WID__c.field-meta.xml
<CustomField>
    <fullName>WID__c</fullName>
    <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
    <label>WID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Target.recordType-meta.xml
<RecordType>
    <fullName>Target</fullName>
    <active>true</active>
    <label>Target</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Con_Centre__c.field-meta.xml
<CustomField>
    <fullName>Con_Centre__c</fullName>
    <formula>Con_Team__r.Team_Centre__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Con_Division__c.field-meta.xml
<CustomField>
    <fullName>Con_Division__c</fullName>
    <formula>Con_Team__r.Team_Division__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Group</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Con_Group__c.field-meta.xml
<CustomField>
    <fullName>Con_Group__c</fullName>
    <formula>Con_Team__r.Team_Group__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Bank</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Con_Region__c.field-meta.xml
<CustomField>
    <fullName>Con_Region__c</fullName>
    <formula>Con_Team__r.Team_Region__c</formula>
    <label>Division</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Con_Team__c.field-meta.xml
<CustomField>
    <fullName>Con_Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Business Centre</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Bankers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Officer_Code__c.field-meta.xml
<CustomField>
    <fullName>Officer_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Officer Code</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/JournalLineItem__c/JournalLineItem__c.object-meta.xml
<CustomObject>
    <description>Journal Line Item</description>
    <label>Journal Line Item</label>
    <nameField>
        <displayFormat>J-{00000}</displayFormat>
        <label>Journal Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journal Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/JournalLineItem__c/fields/Journal_TransferredforTargtes__c.field-meta.xml
<CustomField>
    <fullName>Journal_TransferredforTargtes__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Transferred for Targets</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/isQ6Available__c.field-meta.xml
<CustomField>
    <fullName>isQ6Available__c</fullName>
    <formula>IF(Account.Officer_Code__c != null, true, false)</formula>
    <label>Is Q6 Available</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Maturity_Date__c.field-meta.xml
<CustomField>
    <fullName>Maturity_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Maturity Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opp_CorpCode__c.field-meta.xml
<CustomField>
    <fullName>Opp_CorpCode__c</fullName>
    <formula>IF( NOT( ISBLANK( TEXT(Opp_BankName__c) ) ) , TEXT(Opp_BankName__c) , 
IF( NOT( ISBLANK( TEXT(Account.Branch__c ) ) ), 
IF(TEXT(Account.Branch__c) = &#39;Clydesdale Bank&#39; , &#39;CB&#39;, 
IF(TEXT(Account.Branch__c) = &#39;Yorkshire Bank&#39; , &#39;YB&#39;, &#39;&#39;)), &#39;&#39;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Corp Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opp_ETRef__c.field-meta.xml
<CustomField>
    <fullName>Opp_ETRef__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ET Ref</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opp_GLAccountNumber__c.field-meta.xml
<CustomField>
    <fullName>Opp_GLAccountNumber__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>GL Account Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opp_OfficerCode__c.field-meta.xml
<CustomField>
    <fullName>Opp_OfficerCode__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Officer Code</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opp_TradeID__c.field-meta.xml
<CustomField>
    <fullName>Opp_TradeID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Trade ID</label>
    <length>35</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PMTarget__c/PMTarget__c.object-meta.xml
<CustomObject>
    <label>PM Target</label>
    <nameField>
        <displayFormat>Target - {00000}</displayFormat>
        <label>PM Target No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PM Targets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PMTarget__c/fields/PMTar_EndDate__c.field-meta.xml
<CustomField>
    <fullName>PMTar_EndDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Plan End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PMTarget__c/fields/PMTar_PMContact__c.field-meta.xml
<CustomField>
    <fullName>PMTar_PMContact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product Manager (Contact)</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Product Manager Contact type should be internal and Contact status should be active</errorMessage>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Internal</value>
        </filterItems>
        <filterItems>
            <field>Contact.Contact_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PM Targets</relationshipLabel>
    <relationshipName>PMTargets</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PMTarget__c/fields/PMTar_Status__c.field-meta.xml
<CustomField>
    <fullName>PMTar_Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Ended</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
                <isActive>false</isActive>
                <label>Closed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Business Centre</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Business Centre Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Centres</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TSMTarget__c/TSMTarget__c.object-meta.xml
<CustomObject>
    <description>To hold the target and actual for a TSM under specific Team</description>
    <label>FRSM Target</label>
    <nameField>
        <displayFormat>Target - {00000}</displayFormat>
        <label>FRSM Target No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FRSM Targets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_EndDate__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_EndDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Plan End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_PseudoTarget__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_PseudoTarget__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Retail Plan</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_Status__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Ended</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
                <isActive>false</isActive>
                <label>Closed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_Team__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_Team__c</fullName>
    <label>Business Centre</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Team status is not active.</errorMessage>
        <filterItems>
            <field>Team__c.Team_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Team__c</referenceTo>
    <relationshipName>TSMTargets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_TSM__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_TSM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Risk Solutions Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>TSMTargets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Product.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Vanilla Option</fullName>
    </customValue>
    <customValue>
        <fullName>Participating Forward</fullName>
    </customValue>
    <customValue>
        <fullName>Partial Forward</fullName>
    </customValue>
    <customValue>
        <fullName>Advantage Forward</fullName>
    </customValue>
    <customValue>
        <fullName>Dynamic Forward</fullName>
    </customValue>
    <customValue>
        <fullName>Bonus Forward</fullName>
    </customValue>
    <customValue>
        <fullName>Leverage Product</fullName>
    </customValue>
    <customValue>
        <fullName>Knock Out Forward</fullName>
    </customValue>
    <customValue>
        <fullName>Dual Currency Deposit (DCD)</fullName>
    </customValue>
    <customValue>
        <fullName>Non- Deliverable Forward (NDF)</fullName>
    </customValue>
    <customValue>
        <fullName>Commodity Price Cap</fullName>
    </customValue>
    <customValue>
        <fullName>Commodity Price Swap</fullName>
    </customValue>
    <customValue>
        <fullName>Interest Rate Cap</fullName>
    </customValue>
    <customValue>
        <fullName>Interest Rate Collar</fullName>
    </customValue>
    <customValue>
        <fullName>Interest Rate Swap</fullName>
    </customValue>
    <customValue>
        <fullName>Floating Rate Loan</fullName>
    </customValue>
    <customValue>
        <fullName>Fixed Rate Loan</fullName>
    </customValue>
    <customValue>
        <fullName>Vanilla Spot</fullName>
    </customValue>
    <customValue>
        <fullName>Vanilla Forward</fullName>
    </customValue>
    <customValue>
        <fullName>Aluminium Swap</fullName>
    </customValue>
    <customValue>
        <fullName>Aluminium Cap</fullName>
    </customValue>
    <customValue>
        <fullName>Copper Swap</fullName>
    </customValue>
    <customValue>
        <fullName>Copper Cap</fullName>
    </customValue>
    <customValue>
        <fullName>Nickel Swap</fullName>
    </customValue>
    <customValue>
        <fullName>Nickel Cap</fullName>
    </customValue>
    <customValue>
        <fullName>Zinc Swap</fullName>
    </customValue>
    <customValue>
        <fullName>Zinc Cap</fullName>
    </customValue>
    <customValue>
        <fullName>Gas Oil Swap</fullName>
    </customValue>
    <customValue>
        <fullName>Gas Oil Cap</fullName>
    </customValue>
    <customValue>
        <fullName>Jet Fuel Swap</fullName>
    </customValue>
    <masterLabel>Product</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TargetTransferController.cls
public class TargetTransferController 
{
    Public Account acct;   
    Public List<Opportunity> opportunityList ;
    Public List<Opportunity> opportunityForJournal ;    
    Public List<Id>opportunityIdList ; 
    Public List<Id>accountIdList ;
    Public Map<Id,Opportunity> opportunityDetails;
    Public Map<Id,Account> customerDetailsMap ;
    Public Set<Id>productManagerIdsList = new Set<Id>();
    Public Set<Id>tsmIdsList = new Set<Id>();
    Public Map<String,TSMTarget__c> pseudoTargetMap  = new Map<String,TSMTarget__c>();
    Public Map<String,TSMTarget__c> tsmTargetMap   =   new Map<String,TSMTarget__c>();
    Public Map<Id,PMTarget__c> pmTargetMap = new Map<Id,PMTarget__c>();
    Public Map<Id,Contact>oldManagers = new Map<Id,Contact>();
    Public boolean pbMsg {get; set;}
    Public boolean pbOpp {get; set;}
    Id oldTsm;
    public List<OpportunityWrapper> OpportunityWrapperList {get; set;}
    public List<Opportunity> OpportunityToUpdate = new List<Opportunity>();
    Opportunity opportunityRecord = new Opportunity();
    Account customerAccount = new Account();
    Account targetAccount;
    public String oldTSMName {get; set;}
    public String newTSMName {get; set;}
    OpportunityTriggerHandler handlerObject;
    String currentFiscalYear;   
    List<JournalLineItem__c> journalLineList;    
    String officerCode;   
    Id pmTarget;
    Id tsmTarget;
    Id oldTSMId;
    Id oldFXManager;
    Id oldCommodityManager;
    Id oldIRRMMnager;
    Id productManagerContact;    
    String productManagerContactName;    
    Id businessRecordTypeId;
    Id vanillaRecordTypeId;
    Id fxRecordTypeId;
    Id commodityRecordTypeId;
    Id irrmRecordTypeId;
    Id crmRecordTypeId;
    Id oldTSMTarget;
    Id oldPMTarget;
    Public boolean tsmTransfer;
    Public boolean pmTransfer;
    Id oldproductManagerContact;
    String oldproductManagerContactName;
    
    Public TargetTransferController(ApexPages.StandardController stdController)
    {
        opportunityForJournal = new List<opportunity>();
        opportunityList = new List<opportunity>();
        opportunityIdList = new List<Id>();
        accountIdList     = new List<Id>();
        opportunityDetails = new Map<Id,Opportunity>();
        customerDetailsMap = new Map<Id,Account>();
        //pbMsg = false;
        //pbOpp = false;
        currentFiscalYear = CYBGUtilClass.findCurrentFY(System.Today(), CYBGUtilClass.fiscalYearStartMonth());
        OpportunityWrapperList = new List<OpportunityWrapper>();
        journalLineList        = new List<JournalLineItem__c>();
        this.acct = (Account)stdController.getRecord();
        system.debug('Account value'+acct);
        Id AccountidValue = apexpages.currentpage().getparameters().get('id');
        system.debug('Id Value '+AccountidValue);
        handlerObject = new OpportunityTriggerHandler();
        businessRecordTypeId  = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get(label.RecordTypeCRMBusinessLoan).getRecordTypeId();
        vanillaRecordTypeId   = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get(label.RecordTypeVanilaFX).getRecordTypeId();
        fxRecordTypeId        = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get(label.RecordTypeFXCash).getRecordTypeId();        
        commodityRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get(label.RecordTypeCommodity).getRecordTypeId();
        irrmRecordTypeId      = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get(label.RecordTypeIRRM).getRecordTypeId();
        crmRecordTypeId       = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get(label.RecordTypeCRM).getRecordTypeId();
        
        
        system.debug('Old TSM Manager'+oldTsmID);
        opportunityList = [Select Id,Name,Amount,Maturity_Date__c,AccountId,Account.OwnerId
                           ,Product__c,RecordType.Name,Account.OldTSMId__c,Account.OldFXManagerId__c,Owner.id,Owner.FirstName,Owner.LastName,
                            Owner.Manager.Id,Opp_CorpCode__c,Opp_ETRef__c,Account.OldCommManagerId__c,Opp_OfficerCode__c,
                            Owner.Manager.FirstName,Opp_GLAccountNumber__c,isQ6Available__c,Account.OldIRRMManagerId__c,
                            Owner.Manager.LastName,Opp_TradeID__c from Opportunity where Accountid=:acct.id];
        
       targetAccount = [Select OldTSMId__c,OwnerId,OldFXManagerId__c,
                                 OldCommManagerId__c,OldIRRMManagerId__c,Owner.FirstName,Owner.LastName,
                                 Owner.ManagerId,Owner.Manager.FirstName,Owner.Manager.LastName From Account where id=:acct.id];
        
        //oldTSMUser = [Select Id,FirstName,LastName,ManagerId,Manager.FirstName,Manager.LastName from User where ID =:targetAccount.OldTSMId__c];
        oldTSMName = targetAccount.Owner.FirstName + targetAccount.Owner.LastName;
        newTSMName = opportunityList[0].Owner.FirstName + opportunityList[0].Owner.LastName;
        oldTsmID = targetAccount.OldTSMId__c;
        oldFXManager = targetAccount.OldFXManagerId__c;
        system.debug('Old Manager Id in Constructor '+oldFXManager);
        oldCommodityManager = targetAccount.OldCommManagerId__c;
        oldIRRMMnager = targetAccount.OldIRRMManagerId__c;
        tsmIdsList.add(targetAccount.OldTSMId__c);
        tsmIdsList.add(targetAccount.OwnerId);
        productManagerIdsList.add(targetAccount.OldFXManagerId__c);
        productManagerIdsList.add(targetAccount.OldCommManagerId__c);
        productManagerIdsList.add(targetAccount.OldIRRMManagerId__c);
        addToWrapper();
    }
    Public Void addToWrapper()
    {
        For(Opportunity eachOpportunityRecord:opportunityList){
            OpportunityWrapperList.add(new OpportunityWrapper(eachOpportunityRecord));
        }   
    }
    
    
    Public PageReference  processSelectedforTSM()
    {
        pmTransfer = false;
        tsmTransfer = True;
        
        processRecords();
        Database.SaveResult[] updateResults = Database.Update(opportunityToUpdate, False);
        PageReference pf = new PageReference('/'+acct.id);
        pf.setRedirect(true);
        return pf;
        
    }
    Public PageReference  processSelectedforPM()
    {
        tsmTransfer = false;
        pmTransfer = True;
        processRecords();
        PageReference pf = new PageReference('/'+acct.id);
        pf.setRedirect(true);
        return pf;
    }
    
    Public Void processRecords()
    {
        system.debug('Called from the Button');
        for(OpportunityWrapper eachWrapper: OpportunityWrapperList) 
        {
            if(eachWrapper.selected == true) 
            {
                opportunityIdList.add(eachWrapper.opportunityRecord.Id);
                accountIdList.add(eachWrapper.opportunityRecord.Accountid);
                opportunityForJournal.add(eachWrapper.opportunityRecord);
            }
        }
        System.debug('Opportunity for Journal'+opportunityForJournal);
        opportunityDetails     = CYBGUtilClass.getOpportunityDetails(opportunityIdList);
        customerDetailsMap     = CYBGUtilClass.getAccountDetails(accountIdList);
        For(Account eachAccount:customerDetailsMap.values())
        {
            productManagerIdsList.add(eachAccount.FX_Manager__c);
            productManagerIdsList.add(eachAccount.IRRM_Manager__c);
            productManagerIdsList.add(eachAccount.Commodity_Manager__c);
        }
        system.debug('Product Manager Ids'+productManagerIdsList);
        For(TSMTarget__c eachtsmTarget :[Select Id,Name,TSMTar_TSM__c,TSMTar_Team__c,TSMTar_PseudoTarget__c,TSMTar_Team__r.Name from TSMTarget__c
                                         where (TSMTar_Status__c = :System.Label.Active OR (TSMTar_Status__c =:System.label.Terminated And TSMTar_EndDate__c >= Today ))and TSMTar_TSM__c IN :tsmIdsList])
        {
            If(eachtsmTarget.TSMTar_PseudoTarget__c==True && eachtsmTarget.TSMTar_Team__r.Name.Contains('CB'))
            {
                pseudoTargetMap.put((String)eachtsmTarget.TSMTar_TSM__c + 'CB',eachtsmTarget);
            }else if(eachtsmTarget.TSMTar_PseudoTarget__c==True && eachtsmTarget.TSMTar_Team__r.Name.Contains('YB'))
            {
                pseudoTargetMap.put((String)eachtsmTarget.TSMTar_TSM__c + 'YB',eachtsmTarget);
            }else{
                tsmTargetMap.put((String)eachtsmTarget.TSMTar_Team__c + (String)eachtsmTarget.TSMTar_TSM__c, eachtsmTarget);
                
            }
            
            tsmTargetMap.put((String)eachtsmTarget.TSMTar_Team__c + (String)eachtsmTarget.TSMTar_TSM__c, eachtsmTarget);
        }
        
        For(PMTarget__c eachPMTarget :[Select Id,Name,PMTar_PMContact__c from PMTarget__c 
                                       where (PMTar_Status__c = :System.Label.Active OR (PMTar_Status__c =:System.label.Terminated And PMTar_EndDate__c >= Today )) and PMTar_PMContact__c IN :productManagerIdsList])
        {
            pmTargetMap.put(eachPMTarget.PMTar_PMContact__c, eachPMTarget);
            
        }
        
        For(Contact eachContact :[Select Id,FirstName,LastName from Contact where id In:productManagerIdsList])
        {
            oldManagers.put(eachContact.id, eachContact);
        }
        
        system.debug('TSM Target Map'+tsmTargetMap);
        system.debug('PM Target Map'+pmTargetMap);
        integer count = 0;
        For(Opportunity eachOpportunityRecord :opportunityForJournal)
        {  
            Count = count+1;
            System.debug('Count is'+Count);
            customerAccount  = customerDetailsMap.get(eachOpportunityRecord.accountId);       
            opportunityRecord = opportunityDetails.get(eachOpportunityRecord.id);
            system.debug('Customer Account'+customerAccount);
            system.debug('Opportunity Record'+opportunityRecord);
            if((eachOpportunityRecord.RecordTypeId == fxRecordTypeId )||(eachOpportunityRecord.RecordTypeId == crmRecordTypeId))
            {
                system.debug('Inside FX Manager Opp');
                pmTarget = getPMTargetId(customerAccount.FX_Manager__c);
                system.debug('Old FX Manager'+oldFXManager);
                oldpmTarget = getPMTargetId(oldFXManager);
                
                system.debug('OLD PM TARGET ID '+oldpmTarget);
                system.debug('New PM Target Record'+pmTarget);
                system.debug('Current Customer Owner Id'+customerAccount.ownerId);
                tsmTarget = getTSMTargetId(customerAccount.RM_Name__r.Con_Team__c,customerAccount.ownerId,
                                                         opportunityRecord.isQ6Available__c,opportunityRecord.Opp_CorpCode__c);
                system.debug('New value for New TSM'+tsmTarget);
                oldTSMTarget = getTSMTargetId(customerAccount.RM_Name__r.Con_Team__c,oldTSMId,
                                                         opportunityRecord.isQ6Available__c,opportunityRecord.Opp_CorpCode__c);
                system.debug('OLd Tsm Target'+oldTSMTarget);
                productManagerContact = customerAccount.FX_Manager__c;
                oldproductManagerContact     = oldFXManager;
                productManagerContactName    = customerAccount.FX_Manager__r.FirstName +' '+  
                    customerAccount.FX_Manager__r.LastName;
                oldproductManagerContactName   = oldManagers.containsKey(oldFXManager)?(oldManagers.get(oldFXManager).FirstName + oldManagers.get(oldFXManager).LastName):Null; 


            }
            else if(eachOpportunityRecord.RecordTypeId == commodityRecordTypeId) 
            {   system.debug('Inside Commodity Manager Opp');
                pmTarget = getPMTargetId(customerAccount.Commodity_Manager__c);
                oldpmTarget = getPMTargetId(oldCommodityManager);
                tsmTarget = getTSMTargetId(customerAccount.RM_Name__r.Con_Team__c,opportunityRecord.ownerId,
                                                         opportunityRecord.isQ6Available__c,opportunityRecord.Opp_CorpCode__c);
                oldTSMTarget = getTSMTargetId(customerAccount.RM_Name__r.Con_Team__c,oldTSMId,
                                                         opportunityRecord.isQ6Available__c,opportunityRecord.Opp_CorpCode__c);  
             system.debug('OLd Tsm Target'+oldTSMTarget);
                productManagerContact        = customerAccount.Commodity_Manager__c;
                oldproductManagerContact     = oldCommodityManager;
                productManagerContactName    = customerAccount.Commodity_Manager__r.FirstName +' '+  
                    customerAccount.Commodity_Manager__r.LastName;

             oldproductManagerContactName   = oldManagers.containsKey(oldCommodityManager)?(oldManagers.get(oldCommodityManager).FirstName + oldManagers.get(oldCommodityManager).LastName):Null; 

            }
            else 
            { 
                system.debug('Inside IRRM Manager Opp');
                pmTarget = getPMTargetId(customerAccount.IRRM_Manager__c);
                
                oldpmTarget = getPMTargetId(oldIRRMMnager);
                
                tsmTarget = getTSMTargetId(customerAccount.RM_Name__r.Con_Team__c,opportunityRecord.ownerId,
                                                         opportunityRecord.isQ6Available__c,opportunityRecord.Opp_CorpCode__c);
                oldTSMTarget = getTSMTargetId(customerAccount.RM_Name__r.Con_Team__c,oldTSMId,
                                                         opportunityRecord.isQ6Available__c,opportunityRecord.Opp_CorpCode__c);
                system.debug('OLd Tsm Target'+oldTSMTarget);
                productManagerContact        = customerAccount.IRRM_Manager__c;
                oldproductManagerContact     = oldIRRMMnager;
                productManagerContactName    = customerAccount.IRRM_Manager__r.FirstName +' '+  
                    customerAccount.IRRM_Manager__r.LastName;

                oldproductManagerContactName   = oldManagers.containsKey(oldIRRMMnager)?(oldManagers.get(oldIRRMMnager).FirstName + oldManagers.get(oldIRRMMnager).LastName):Null; 
            }
            
            if(customerAccount != null && customerAccount.RM_Name__c != null)
            {
                officerCode = customerAccount.RM_Name__r.Officer_Code__c;
            }
            else
            {
                officerCode = eachOpportunityRecord.Opp_OfficerCode__c;
            }
            
            /*if(eachOpportunityRecord.RecordTypeId == crmRecordTypeId || eachOpportunityRecord.RecordTypeId == vanillaRecordTypeId)
            {*/
                system.debug('Inside the Function------');
                
                JournalLineItem__c journals = CYBGUtilClass.createJournalLineItemsRecords(eachOpportunityRecord.Id,
                                                                                customerAccount.RM_Name__c,
                                                                                eachOpportunityRecord.Amount,Label.Transaction_Type_Debit,NULL,
                                                                                currentFiscalYear,opportunityRecord.Opp_TradeID__c,((customerAccount.RM_Name__r.FirstName!=Null)?customerAccount.RM_Name__r.FirstName:'')+
                                                                                ((customerAccount.RM_Name__r.LastName!=Null)?customerAccount.RM_Name__r.LastName:''),                                              
                                                                                officerCode,customerAccount.CIF__c,
                                                                                opportunityRecord.Opp_CorpCode__c,customerAccount.Id,
                                                                                opportunityRecord.Opp_ETRef__c,opportunityRecord.Opp_GLAccountNumber__c,
                                                                                eachOpportunityRecord.Product__c,opportunityRecord.RecordType.Name,
                                                                                productManagerContact,productManagerContactName,                               
                                                                                customerAccount.RM_Name__r.Con_Team__c,customerAccount.RM_Name__r.Con_Team__r.Name,                                             
                                                                                customerAccount.OwnerId,targetAccount.owner.FirstName + ' '+ 
                                                                                targetAccount.owner.LastName,targetAccount.owner.ManagerId,
                                                                                ((targetAccount.owner.Manager.FirstName!=Null)?targetAccount.owner.Manager.FirstName:'')+
                                                                                ' '+((targetAccount.owner.Manager.LastName!=Null)?targetAccount.owner.Manager.LastName:''),customerAccount.WID__c,
                                                                                customerAccount.RM_Name__r.Con_Centre__c,
                                                                                customerAccount.RM_Name__r.Con_Region__c,
                                                                                customerAccount.RM_Name__r.Con_Division__c,
                                                                                customerAccount.RM_Name__r.Con_Group__c,pmTarget,tsmTarget,Null);
                                    journals.Journal_TransferredforTargtes__c = True;
                                    journalLineList.add(journals);
                
                JournalLineItem__c journal = CYBGUtilClass.createJournalLineItemsRecords(eachOpportunityRecord.Id,
                                                                                customerAccount.RM_Name__c,
                                                                                (eachOpportunityRecord.Amount) *-1,Label.Transaction_Type_Credit,NULL,
                                                                                currentFiscalYear,opportunityRecord.Opp_TradeID__c,((customerAccount.RM_Name__r.FirstName!=Null)?customerAccount.RM_Name__r.FirstName:'')+
                                                                                ((customerAccount.RM_Name__r.LastName!=Null)?customerAccount.RM_Name__r.LastName:''),                                              
                                                                                officerCode,customerAccount.CIF__c,
                                                                                opportunityRecord.Opp_CorpCode__c,customerAccount.Id,
                                                                                opportunityRecord.Opp_ETRef__c,opportunityRecord.Opp_GLAccountNumber__c,
                                                                                eachOpportunityRecord.Product__c,opportunityRecord.RecordType.Name,
                                                                                (pmTransfer==True?oldproductManagerContact:productManagerContact),
                                                                                (pmTransfer==True?oldproductManagerContactName:productManagerContact),                               
                                                                                customerAccount.RM_Name__r.Con_Team__c,customerAccount.RM_Name__r.Con_Team__r.Name,                                             
                                                                                (tsmTransfer==True?oldTSMId:customerAccount.ownerId),opportunityRecord.owner.FirstName + ' '+ 
                                                                                opportunityRecord.owner.LastName,opportunityRecord.owner.ManagerId,
                                                                                ((opportunityRecord.owner.Manager.FirstName!=Null)?opportunityRecord.owner.Manager.FirstName:'')+
                                                                                ' '+((opportunityRecord.owner.Manager.LastName!=Null)?opportunityRecord.owner.Manager.LastName:''),customerAccount.WID__c,
                                                                                customerAccount.RM_Name__r.Con_Centre__c,
                                                                                customerAccount.RM_Name__r.Con_Region__c,
                                                                                customerAccount.RM_Name__r.Con_Division__c,
                                                                                customerAccount.RM_Name__r.Con_Group__c,(pmTransfer==True?oldpmTarget:pmTarget),(tsmTransfer==True?oldtsmTarget:tsmTarget),Null);
              journal.Journal_TransferredforTargtes__c = True;
              journalLineList.add(journal);
                
                
            //}
            
            eachOpportunityRecord.OwnerId = targetAccount.ownerid;
            opportunityToUpdate.add(eachOpportunityRecord);
            
        }
        system.debug('Journal List Values'+journalLineList);
        Database.SaveResult[] updateResult = Database.Insert(journalLineList, False);
        System.debug('Database Result'+updateResult);
        
    }
    
    Public Void ProcessTsm()
    {
        system.debug('This is inside Process Target method');
        pbMsg = True;
    }
    
    public Id getTSMTargetId(Id teamId,Id tsmId,Boolean q6Check,String corpcode)
    {
       SYSTEM.debug('TSM Target Inside Opportunity Handler'+tsmTargetMap);
        if(tsmTargetMap.containsKey((String)teamId+(String)tsmId))
        {
            tsmId = tsmTargetMap.get((String)teamId+(String)tsmId).Id;
            
            
        }else If((pseudoTargetMap.containsKey((String)tsmId+corpcode)) && q6Check !=True) 
        {
            
            tsmId = pseudoTargetMap.get((String)tsmId+corpcode).Id;
        }else{
            tsmId = null;
        }
        return tsmId;
    }
    
    public Id getPMTargetId(Id productManagerId)
    {   
        
        if(pmTargetMap.containsKey(productManagerId))
        {
            productManagerId  = pmTargetMap.get(productManagerId).Id;
        }else 
        {
            productManagerId = Null;
        }
        return productManagerId;
        
    }
    
    public class OpportunityWrapper {
        public Opportunity opportunityRecord {get; set;}
        public Boolean selected {get; set;}
        
        public OpportunityWrapper(Opportunity eachOpportunityRecord) {
            opportunityRecord = eachOpportunityRecord;
            selected = false;
        }
    }
}