force-app/main/default/objects/Account/fields/Commodity_Manager__c.field-meta.xml
<CustomField>
    <fullName>Commodity_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Commodity Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Commodity Manager)</relationshipLabel>
    <relationshipName>CommodityManagers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/FX_Manager__c.field-meta.xml
<CustomField>
    <fullName>FX_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FX Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (FX Manager)</relationshipLabel>
    <relationshipName>FXManagers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/IRRM_Manager__c.field-meta.xml
<CustomField>
    <fullName>IRRM_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>IRRM Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (IRRM Manager)</relationshipLabel>
    <relationshipName>IRRMManagers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/RM_Name__c.field-meta.xml
<CustomField>
    <fullName>RM_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RM Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND 2</booleanFilter>
        <errorMessage>Please select an active Banker of a respective branch.</errorMessage>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Banker</value>
        </filterItems>
        <filterItems>
            <field>Contact.Contact_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Banker)</relationshipLabel>
    <relationshipName>AccountBanker</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/WID__c.field-meta.xml
<CustomField>
    <fullName>WID__c</fullName>
    <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
    <label>WID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Con_Team__c.field-meta.xml
<CustomField>
    <fullName>Con_Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Business Centre</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Bankers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Repository__c/Repository__c.object-meta.xml
<CustomObject>
    <description>An Object to store and manage data for Report.</description>
    <label>Repository</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Repository Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Repositories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Repository__c/fields/Opportunity_RecordType__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_RecordType__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Opportunity RecordType</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Repository__c/fields/Rep_AccountId__c.field-meta.xml
<CustomField>
    <fullName>Rep_AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Id</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Repositories</relationshipLabel>
    <relationshipName>Repositories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Repository__c/fields/Rep_BusinessCentre__c.field-meta.xml
<CustomField>
    <fullName>Rep_BusinessCentre__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Business Centre</label>
    <length>220</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Repository__c/fields/Rep_CombineId__c.field-meta.xml
<CustomField>
    <fullName>Rep_CombineId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Combine Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Repository__c/fields/Rep_PMName__c.field-meta.xml
<CustomField>
    <fullName>Rep_PMName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>PM</label>
    <length>240</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Repository__c/fields/Rep_RMName__c.field-meta.xml
<CustomField>
    <fullName>Rep_RMName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>RM Name</label>
    <length>220</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Repository__c/fields/Rep_TSMName__c.field-meta.xml
<CustomField>
    <fullName>Rep_TSMName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>FRSM</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Repository__c/fields/Rep_WID__c.field-meta.xml
<CustomField>
    <fullName>Rep_WID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>WID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Repository__c/recordTypes/CustomerAndPM.recordType-meta.xml
<RecordType>
    <fullName>CustomerAndPM</fullName>
    <active>true</active>
    <label>CustomerAndPM</label>
</RecordType>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Business Centre</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Business Centre Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Centres</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/PMReportUpdateFRSMAndPM_Sched.cls
global class PMReportUpdateFRSMAndPM_Sched implements Schedulable {
    /**
* @description       Method to Schedule a PMReportUpdateFRSMAndPM_Sched class 
* @name              execute
* @param             SchedulableContext
* @return            Void
* @throws            NA
*/
    global void execute(SchedulableContext ctx) {
        
        List<Repository__c> replist=[select Rep_AccountId__C,Rep_CombineId__c,Opportunity_RecordType__c from repository__c
                                     where recordtype.name='CustomerAndPM' and Rep_TSMName__c=null and Rep_PMName__c=null and Rep_RMName__c=null 
                                     and Rep_BusinessCentre__c=null and Rep_WID__c=null];
        
        System.debug('replist size======>'+replist.size());
        Map<String,List<Repository__c>> repMapList = new Map<String,List<Repository__c>>();
        for(Repository__c rep:replist){
            if(repMapList.containskey(rep.Rep_AccountId__C)){
                repMapList.get(rep.Rep_AccountId__c).add(rep);
            }else{
                repMapList.put(rep.Rep_AccountId__c,new List<Repository__c>{rep});
            }   
        }
        List<Repository__c> repList1 = new List<Repository__c>();
        for(Account acc :[SELECT Id, name, owner.name,RM_Name__r.Name,RM_Name__r.Con_Team__r.Name,WID__c,IRRM_Manager__r.name,Commodity_Manager__r.name,FX_Manager__r.name,recordtype.name
                          FROM Account Where id IN : repMapList.keySet()]){
                              if(repMapList.containskey(acc.id)){
                                  for(Repository__c rep1 : repMapList.get(acc.id)){
                                      if(rep1.Opportunity_RecordType__c=='FX Cash'){
                                          rep1.Rep_PMName__c=acc.FX_Manager__r.name;
                                      }
                                      else if(rep1.Opportunity_RecordType__c=='IRRM'){
                                          rep1.Rep_PMName__C=acc.IRRM_Manager__r.name;
                                      }
                                      else if(rep1.Opportunity_RecordType__c=='Commodity'){
                                          rep1.Rep_PMName__C=acc.Commodity_Manager__r.name;
                                      }
                                      rep1.Rep_TSMName__c = acc.Owner.Name;
                                      rep1.Rep_RMName__c = acc.RM_Name__r.Name;
                                      rep1.Rep_BusinessCentre__c = acc.RM_Name__r.Con_Team__r.Name;
                                      rep1.Rep_WID__c = acc.WID__c;
                                      repList1.add(rep1);
                                  }
                                  
                              }
                              
                          }
        update repList1;  
    }   
}