force-app/main/default/objects/Account/fields/Commodity_Manager__c.field-meta.xml
<CustomField>
    <fullName>Commodity_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Commodity Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Commodity Manager)</relationshipLabel>
    <relationshipName>CommodityManagers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/FX_Manager__c.field-meta.xml
<CustomField>
    <fullName>FX_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FX Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (FX Manager)</relationshipLabel>
    <relationshipName>FXManagers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/IRRM_Manager__c.field-meta.xml
<CustomField>
    <fullName>IRRM_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>IRRM Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (IRRM Manager)</relationshipLabel>
    <relationshipName>IRRMManagers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Product</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/RecordType__c.field-meta.xml
<CustomField>
    <fullName>RecordType__c</fullName>
    <label>Record Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Target</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Internal.recordType-meta.xml
<RecordType>
    <fullName>Internal</fullName>
    <active>true</active>
    <label>Internal</label>
</RecordType>

force-app/main/default/objects/Centre__c/Centre__c.object-meta.xml
<CustomObject>
    <label>Region</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Centre__c/fields/Centre_Region__c.field-meta.xml
<CustomField>
    <fullName>Centre_Region__c</fullName>
    <label>Division</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Region is not active.</errorMessage>
        <filterItems>
            <field>Region__c.Region_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Region__c</referenceTo>
    <relationshipLabel>Regions</relationshipLabel>
    <relationshipName>Centres</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Checklist__c/Checklist__c.object-meta.xml
<CustomObject>
    <label>Checklist</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Checklist Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Checklists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Checklist__c/fields/File_Checker__c.field-meta.xml
<CustomField>
    <fullName>File_Checker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>File Checker</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Form1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Checklist__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FX</fullName>
            </value>
            <value>
                <fullName>Commodity</fullName>
            </value>
            <value>
                <fullName>IRRM</fullName>
            </value>
            <value>
                <fullName>Business Loan</fullName>
            </value>
            <value>
                <fullName>CRM</fullName>
            </value>
            <value>
                <fullName>Vanilla FX</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Con_Team__c.field-meta.xml
<CustomField>
    <fullName>Con_Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Business Centre</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Bankers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Banker.recordType-meta.xml
<RecordType>
    <fullName>Banker</fullName>
    <active>true</active>
    <label>Banker</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Internal.recordType-meta.xml
<RecordType>
    <fullName>Internal</fullName>
    <active>true</active>
    <description>Used for Treasury Solutions employees</description>
    <label>Internal</label>
</RecordType>

force-app/main/default/objects/Division__c/Division__c.object-meta.xml
<CustomObject>
    <label>Group</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Division__c/fields/Div_Group__c.field-meta.xml
<CustomField>
    <fullName>Div_Group__c</fullName>
    <label>Bank</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Group is not active.</errorMessage>
        <filterItems>
            <field>Group__c.Group_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Group__c</referenceTo>
    <relationshipLabel>Groups</relationshipLabel>
    <relationshipName>Divisions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <formula>Account.RM_Name__r.Con_Team__r.Team_Centre__r.Centre_Division__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Group</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opp_BranchNumber__c.field-meta.xml
<CustomField>
    <fullName>Opp_BranchNumber__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Branch Number</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opp_TradeID__c.field-meta.xml
<CustomField>
    <fullName>Opp_TradeID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Trade ID</label>
    <length>35</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PMTarget__c/PMTarget__c.object-meta.xml
<CustomObject>
    <label>PM Target</label>
    <nameField>
        <displayFormat>Target - {00000}</displayFormat>
        <label>PM Target No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PM Targets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PMTarget__c/fields/PMTar_PMContact__c.field-meta.xml
<CustomField>
    <fullName>PMTar_PMContact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product Manager (Contact)</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Product Manager Contact type should be internal and Contact status should be active</errorMessage>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Internal</value>
        </filterItems>
        <filterItems>
            <field>Contact.Contact_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PM Targets</relationshipLabel>
    <relationshipName>PMTargets</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PMTarget__c/fields/PMTar_PMUser__c.field-meta.xml
<CustomField>
    <fullName>PMTar_PMUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Manager (User)</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PMTargets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Region__c/Region__c.object-meta.xml
<CustomObject>
    <label>Division</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Division Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Divisions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Region__c/fields/Region_Division__c.field-meta.xml
<CustomField>
    <fullName>Region_Division__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Group</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Division is not active.</errorMessage>
        <filterItems>
            <field>Division__c.Div_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Division__c</referenceTo>
    <relationshipLabel>Divisions</relationshipLabel>
    <relationshipName>Regions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Business Centre</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Business Centre Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Centres</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Team__c/fields/Team_Centre__c.field-meta.xml
<CustomField>
    <fullName>Team_Centre__c</fullName>
    <label>Region</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Centre is not active.</errorMessage>
        <filterItems>
            <field>Centre__c.Centre_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Centre__c</referenceTo>
    <relationshipLabel>Business Centres</relationshipLabel>
    <relationshipName>Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TSMTarget__c/TSMTarget__c.object-meta.xml
<CustomObject>
    <description>To hold the target and actual for a TSM under specific Team</description>
    <label>FRSM Target</label>
    <nameField>
        <displayFormat>Target - {00000}</displayFormat>
        <label>FRSM Target No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FRSM Targets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_EndDate__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_EndDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Plan End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_StartDate__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_StartDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Plan Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_Team__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_Team__c</fullName>
    <label>Business Centre</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Team status is not active.</errorMessage>
        <filterItems>
            <field>Team__c.Team_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Team__c</referenceTo>
    <relationshipName>TSMTargets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_TSM__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_TSM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Risk Solutions Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>TSMTargets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>England</fullName>
            </value>
            <value>
                <fullName>Scotland</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Product.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Vanilla Option</fullName>
    </customValue>
    <customValue>
        <fullName>Participating Forward</fullName>
    </customValue>
    <customValue>
        <fullName>Partial Forward</fullName>
    </customValue>
    <customValue>
        <fullName>Advantage Forward</fullName>
    </customValue>
    <customValue>
        <fullName>Dynamic Forward</fullName>
    </customValue>
    <customValue>
        <fullName>Bonus Forward</fullName>
    </customValue>
    <customValue>
        <fullName>Leverage Product</fullName>
    </customValue>
    <customValue>
        <fullName>Knock Out Forward</fullName>
    </customValue>
    <customValue>
        <fullName>Dual Currency Deposit (DCD)</fullName>
    </customValue>
    <customValue>
        <fullName>Non- Deliverable Forward (NDF)</fullName>
    </customValue>
    <customValue>
        <fullName>Commodity Price Cap</fullName>
    </customValue>
    <customValue>
        <fullName>Commodity Price Swap</fullName>
    </customValue>
    <customValue>
        <fullName>Interest Rate Cap</fullName>
    </customValue>
    <customValue>
        <fullName>Interest Rate Collar</fullName>
    </customValue>
    <customValue>
        <fullName>Interest Rate Swap</fullName>
    </customValue>
    <customValue>
        <fullName>Floating Rate Loan</fullName>
    </customValue>
    <customValue>
        <fullName>Fixed Rate Loan</fullName>
    </customValue>
    <customValue>
        <fullName>Vanilla Spot</fullName>
    </customValue>
    <customValue>
        <fullName>Vanilla Forward</fullName>
    </customValue>
    <customValue>
        <fullName>Aluminium Swap</fullName>
    </customValue>
    <customValue>
        <fullName>Aluminium Cap</fullName>
    </customValue>
    <customValue>
        <fullName>Copper Swap</fullName>
    </customValue>
    <customValue>
        <fullName>Copper Cap</fullName>
    </customValue>
    <customValue>
        <fullName>Nickel Swap</fullName>
    </customValue>
    <customValue>
        <fullName>Nickel Cap</fullName>
    </customValue>
    <customValue>
        <fullName>Zinc Swap</fullName>
    </customValue>
    <customValue>
        <fullName>Zinc Cap</fullName>
    </customValue>
    <customValue>
        <fullName>Gas Oil Swap</fullName>
    </customValue>
    <customValue>
        <fullName>Gas Oil Cap</fullName>
    </customValue>
    <customValue>
        <fullName>Jet Fuel Swap</fullName>
    </customValue>
    <customValue>
        <fullName>FX</fullName>
    </customValue>
    <masterLabel>Product</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CYBGUtilClass_Test.cls
/*
@Author        : Santhoshan
@Name          : CYBGUtilClass_Test
@Created Date  : 23rd Feb 2018
@Description   : This is a Test Class for CYBGUtilClass
@version       : 1.0
*/
@isTest
public class CYBGUtilClass_Test {
    
    @testSetup static void setup() {
        
        Id RecordTypeIdContactBanker = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Banker').getRecordTypeId();
        Id RecordTypeIdAccountInternal = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Internal').getRecordTypeId();
        Id RecordTypeIdAccountCustomer = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId();
        Id RecordTypeIdContactInternal = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Internal').getRecordTypeId();
        
        User tsmUserManager = TestData.createUser('CYB');
        Insert tsmUserManager;
        User tsmUser = TestData.createUser('System Administrator');
        tsmUser.lastname = 'Tsm User';
        tsmUser.ManagerId = tsmUserManager.id;
        tsmUser.Location__c = 'England';
        tsmUser.Username  = 'tsmuserjournal@testorg.com';

        insert tsmUser;
        system.runAs(tsmUser){
            Group__c testGroup = TestData.createGroup();
            insert testGroup;        
            Division__c testDivision = TestData.createDivision();
            testDivision.Div_Group__c=testGroup.Id;       
            insert testDivision;        
            Region__c testRegion = TestData.createRegion();
            testRegion.Region_Division__c=testDivision.id;        
            insert testRegion;        
            Centre__c testCentre = TestData.createCentre();
            testCentre.Centre_Region__c=testRegion.id;        
            insert testCentre;
            Team__c testTeam = TestData.createTeam();
            testTeam.Team_Centre__c = testCentre.id; 
            insert testTeam;
            Account accint = TestData.createCalypsoAccountInternal('Clydesdale Bank', RecordTypeIdAccountInternal);
            accint.RecordType__c = 'Internal';
            insert accint;
            Contact con = TestData.createContact('1234', RecordTypeIdContactBanker, accint.Id);
            con.Con_Team__c = testTeam.id;
            insert con;
            Account acc = TestData.createCalypsoAccount('Test Acc', '1245', '1234', con.Id, RecordTypeIdAccountCustomer);
            acc.FX_Manager__c=con.Id;
            acc.IRRM_Manager__c=con.Id;
            acc.Commodity_Manager__c = con.Id;
            acc.RecordType__c = 'Customer';
            insert acc;
        }
    }
    
    static TestMethod void fiscalYearCheck() {
        Integer integerReturnValue = 0;
        Date todayDate = Date.Today();
        Integer year = todayDate.year();
        string s1=string.valueof(year).right(2);
        Integer yearvalue = Integer.valueof(s1);
        String currentFiscalYear = 'FY'+yearValue;
        String StringReturnedValue ;
        String StringReturnedValue1 ;
        Date newDate = Date.newInstance(2018, 11, 20);
        Test.startTest();
        integerReturnValue = CYBGUtilClass.fiscalYearStartMonth();
        StringReturnedValue = CYBGUtilClass.findCurrentFY(todayDate,integerReturnValue);
        StringReturnedValue1 = CYBGUtilClass.findCurrentFY(newDate,integerReturnValue);
        Date returnDate1 = CYBGUtilClass.findStartDateOfFY(todayDate,integerReturnValue);
        Date returnDate2 = CYBGUtilClass.findEndDateOfFY(todayDate,integerReturnValue);
        Date returnDate3 = CYBGUtilClass.findStartDateOfFY(newDate,integerReturnValue);
        Date returnDate4 = CYBGUtilClass.findEndDateOfFY(newDate,integerReturnValue);
        Test.stopTest();
        //system.assertEquals(currentFiscalYear,StringReturnedValue);
    }
    static TestMethod void journalprocessData() {
        User tsmUser = [Select id,Name from user where Username = 'tsmuserjournal@testorg.com' Limit 1];
        Id RecordTypeIdAccountCustomer = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId();
        Id RecordTypeIdAccountInternal = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Internal').getRecordTypeId();
        Id RecordTypeIdFXCash= Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('FX Cash').getRecordTypeId();
        Id RecordTypeIdOpportunityCRM = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('CRM').getRecordTypeId();
        Id RecordTypeIdOpportunityCommodity = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Commodity').getRecordTypeId();
        Id RecordTypeIdOpportunityIRRM = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('IRRM').getRecordTypeId(); 
        Id RecordTypeIdContactInternal = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Internal').getRecordTypeId();
        
        User testUser = new user(ID = UserInfo.getUserID());
        
        Account acc = [Select Id,Name from Account where RecordTypeId = :RecordTypeIdAccountCustomer];
        Contact con = [Select Id,FirstName from Contact]; 
        Centre__c centre = [Select Id,Name from Centre__c];
        Division__c division = [Select Id,Name from Division__c];
        Group__c Groupval = [Select Id,Name from Group__c];
        Region__c region = [Select Id,Name from Region__c];
        Account accint = TestData.createCalypsoAccountInternal('Clydesdale Bank Internal', RecordTypeIdAccountInternal);
        accint.RecordType__c = 'Internal';
        insert accint;
        Contact conint = TestData.createContactInternal('2345', RecordTypeIdContactInternal, accint.Id);
        insert conint;
        Checklist__c chkLst = TestData.createChecklist(acc.Id);
        chkLst.File_Checker__c = testUser.Id;
        chkLst.Product__c = 'FX';
        insert chkLst;
        Checklist__c chkLstCommodity = TestData.createChecklist(acc.Id);
        chkLstCommodity.File_Checker__c = testUser.Id;
        chkLstCommodity.Product__c = 'Commodity';
        insert chkLstCommodity;
        Checklist__c chkLstIRRM = TestData.createChecklist(acc.Id);
        chkLstIRRM.File_Checker__c = testUser.Id;
        chkLstIRRM.Product__c = 'IRRM';
        insert chkLstIRRM;
        
        Opportunity opp = TestData.createOpportunity(acc.id, con, chkLst.Id, RecordTypeIdFXCash,200,200);
        opp.StageName = 'Closed Won';
        opp.product__c = 'FX';
        opp.OwnerId   = tsmUser.id;
        opp.Opp_TradeID__c='101010101';
        opp.Opp_BranchNumber__c=System.Label.CBDirectDealingClient;
        insert Opp;
        Opportunity opp1 = TestData.createOpportunity(acc.id, con, chkLst.Id, RecordTypeIdOpportunityCRM,200,200);
        opp1.StageName = 'Closed Won';
        opp1.OwnerId   = tsmUser.id;
        opp1.Opp_BranchNumber__c=System.Label.CBCardedRateSheet;
        opp1.Opp_TradeID__c='101010102';
        insert Opp1;
        Test.startTest(); 
        Opportunity opp2 = TestData.createOpportunity(acc.id, con, chkLstCommodity.Id, RecordTypeIdOpportunityCommodity,200,200);
        opp2.StageName = 'Closed Won';
        opp2.OwnerId   = tsmUser.id;
        opp2.Opp_TradeID__c='101010103';
        insert Opp2;
        Opportunity opp3 = TestData.createOpportunity(acc.id, con, chkLstIRRM.Id, RecordTypeIdOpportunityIRRM,200,200);
        opp3.StageName = 'Closed Won';
        opp3.OwnerId   = tsmUser.id;
        opp3.Opp_TradeID__c='101010104';
        insert Opp3;
        Date todayDate = Date.today();
        Integer yearValue = todayDate.year();
        Integer monthValue = todayDate.month();
        monthValue = monthValue + 1;
        Date newDate = Date.newInstance(yearValue, monthValue, 1);
        Team__c testTeam = [Select Id,Name from Team__c]; 
        TSMTarget__c testTarget = TestData.createTSMTarget();
        testTarget.TSMTar_Team__c = testTeam.id;
        testTarget.TSMTar_TSM__c = tsmUser.Id;
        testTarget.TSMTar_StartDate__c = System.Today();
        testTarget.TSMTar_EndDate__c = System.Today().AddDays(1);
        //testTarget.TSMTar_EndDate__c = newDate;
        insert testTarget;
        PMTarget__c testPMTarget = TestData.createPMMTarget();
        testPMTarget.PMTar_PMUser__c = tsmUser.Id;
        testPMTarget.PMTar_PMContact__c = conint.Id;
        testPMTarget.PMTar_StartDate__c = System.Today();
        testPMTarget.PMTar_EndDate__c = System.Today().AddDays(1);
        //testPMTarget.PMTar_EndDate__c = newDate;
        Insert testPMTarget;
        
        Test.stopTest();
        
        Integer integerReturnValue = CYBGUtilClass.fiscalYearStartMonth();
        String StringReturnedValue = CYBGUtilClass.findCurrentFY(Date.today(),integerReturnValue);
        
        
        JournalLineItem__c jc1 = CYBGUtilClass.createJournalLineItemsRecords(Opp.id,con.id,Opp.Amount,'Debit',Null,StringReturnedValue,Null,
                                                                             con.FirstName,Null,Null,Null,acc.id,Null,Null,'Vanilla Spot','FX Cash',con.id,
                                                                             con.FirstName,testTeam.id,testTeam.Name,tsmuser.id,tsmuser.Name,
                                                                             Null,Null,Null,centre.Name,region.Name,division.Name,groupval.Name,
                                                                             testPMTarget.id,testTarget.id,NULL);
        System.debug('testPMTarget'+testPMTarget);
        System.debug('jc1'+jc1);
        //PMTarget__c pm1 = CYBGUtilClass.updatePMTarget(testPMTarget,jc1);
        //TSMTarget__c tc1 = CYBGUtilClass.updateTSMTarget(testTarget,jc1);
        
        JournalLineItem__c jc2 = CYBGUtilClass.createJournalLineItemsRecords(Opp1.id,con.id,Opp1.Amount,'Debit',Null,StringReturnedValue,Null,
                                                                             con.FirstName,Null,Null,Null,acc.id,Null,Null,'Vanilla Spot','CRM',con.id,
                                                                             con.FirstName,testTeam.id,testTeam.Name,tsmuser.id,tsmuser.Name,
                                                                             Null,Null,Null,centre.Name,region.Name,division.Name,groupval.Name,
                                                                             testPMTarget.id,testTarget.id,NULL);
        JournalLineItem__c jc3 = CYBGUtilClass.createJournalLineItemsRecords(Opp2.id,con.id,Opp2.Amount,'Debit',Null,StringReturnedValue,Null,
                                                                             con.FirstName,Null,Null,Null,acc.id,Null,Null,'Vanilla Spot','Commodity',con.id,
                                                                             con.FirstName,testTeam.id,testTeam.Name,tsmuser.id,tsmuser.Name,
                                                                             Null,Null,Null,centre.Name,region.Name,division.Name,groupval.Name,
                                                                             testPMTarget.id,testTarget.id,NULL);
        
        JournalLineItem__c jc4 = CYBGUtilClass.createJournalLineItemsRecords(Opp3.id,con.id,Opp3.Amount,'Debit',Null,StringReturnedValue,Null,
                                                                             con.FirstName,Null,Null,Null,acc.id,Null,Null,'Vanilla Spot','IRRM',con.id,
                                                                             con.FirstName,testTeam.id,testTeam.Name,tsmuser.id,tsmuser.Name,
                                                                             Null,Null,Null,centre.Name,region.Name,division.Name,groupval.Name,
                                                                             testPMTarget.id,testTarget.id,NULL);
        
        PMTarget__c pm2 = CYBGUtilClass.updatePMTarget(testPMTarget,jc2);
        TSMTarget__c tc2 = CYBGUtilClass.updateTSMTarget(testTarget,jc2);
        PMTarget__c pm3 = CYBGUtilClass.updatePMTarget(testPMTarget,jc3);
        TSMTarget__c tc3 = CYBGUtilClass.updateTSMTarget(testTarget,jc3);
        PMTarget__c pm4 = CYBGUtilClass.updatePMTarget(testPMTarget,jc4);
        TSMTarget__c tc4 = CYBGUtilClass.updateTSMTarget(testTarget,jc4);
        List<JournalLineItem__c>journalList = [Select Id from JournalLineItem__c];
        //system.assertEquals(5, journalList.size());
        
    }
    
    
}