force-app/main/default/objects/Account/fields/Commodity_Manager__c.field-meta.xml
<CustomField>
    <fullName>Commodity_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Commodity Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Commodity Manager)</relationshipLabel>
    <relationshipName>CommodityManagers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/FX_Manager__c.field-meta.xml
<CustomField>
    <fullName>FX_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FX Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (FX Manager)</relationshipLabel>
    <relationshipName>FXManagers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/IRRM_Manager__c.field-meta.xml
<CustomField>
    <fullName>IRRM_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>IRRM Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (IRRM Manager)</relationshipLabel>
    <relationshipName>IRRMManagers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opp_PrimaryAmount__c.field-meta.xml
<CustomField>
    <fullName>Opp_PrimaryAmount__c</fullName>
    <label>Primary Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opp_PrimaryCurrency__c.field-meta.xml
<CustomField>
    <fullName>Opp_PrimaryCurrency__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Primary Currency</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opp_SecondaryAmount__c.field-meta.xml
<CustomField>
    <fullName>Opp_SecondaryAmount__c</fullName>
    <label>Secondary Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opp_SecondaryCurrency__c.field-meta.xml
<CustomField>
    <fullName>Opp_SecondaryCurrency__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Secondary Currency</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Repository__c/Repository__c.object-meta.xml
<CustomObject>
    <description>An Object to store and manage data for Report.</description>
    <label>Repository</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Repository Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Repositories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Repository__c/recordTypes/CustomerAndPM.recordType-meta.xml
<RecordType>
    <fullName>CustomerAndPM</fullName>
    <active>true</active>
    <label>CustomerAndPM</label>
</RecordType>

force-app/main/default/classes/ReportRep_Sched.cls
global class ReportRep_Sched implements Schedulable{

    global void execute (SchedulableContext ctx){ 
        Date endLastYear = System.today().Addyears(-1);
        Date endThisYear = System.today();
        
        Integer startMonth =  CYBGUtilClass.fiscalYearStartMonth();
        
        Date startLastYear = CYBGUtilClass.findStartDateOfFY(endLastYear, startMonth ) ;
        Date startThisYear = CYBGUtilClass.findStartDateOfFY(endThisYear, startMonth ) ;
        
        List<Repository__c> repList = [SELECT Id FROM Repository__c WHERE RecordType.Name = 'CustomerAndPM'];
        if(repList.size() > 0)
            delete repList;
        
        List<AggregateResult> queryLast = [SELECT Count(ID) cnt, SUM(Amount) amt, SUM(Opp_PrimaryAmount__c)prmAmount, SUM(Opp_SecondaryAmount__c) scndAmount,
                                           Opp_PrimaryCurrency__c prmCurr, Opp_SecondaryCurrency__c scndCurr, Account.Name accName, Account.Id accId, 
                                           Account.FX_Manager__c fxm, Account.Commodity_Manager__c commm, Account.IRRM_Manager__c irrmm, RecordType.Name rcd,
                                           MAX(CloseDate) csd
                                           FROM Opportunity WHERE CloseDate >= :startLastYear AND CloseDate <= :endLastYear
                                           AND StageName = 'Closed Won'
                                           GROUP BY Account.Id, Account.Name, RecordType.Name, Account.FX_Manager__c, Account.Commodity_Manager__c, Account.IRRM_Manager__c, Opp_PrimaryCurrency__c, Opp_SecondaryCurrency__c
                                           ORDER BY Account.Id, Account.Name, RecordType.Name, Account.FX_Manager__c, Account.Commodity_Manager__c, Account.IRRM_Manager__c, Opp_PrimaryCurrency__c, Opp_SecondaryCurrency__c]; 
        
        List<AggregateResult> queryCurr = [SELECT Count(ID) cnt, SUM(Amount) amt, SUM(Opp_PrimaryAmount__c)prmAmount, SUM(Opp_SecondaryAmount__c) scndAmount,
                                           Opp_PrimaryCurrency__c prmCurr, Opp_SecondaryCurrency__c scndCurr, Account.Name accName, Account.Id accId, 
                                           Account.FX_Manager__c fxm, Account.Commodity_Manager__c commm, Account.IRRM_Manager__c irrmm, RecordType.Name rcd,
                                           MAX(CloseDate) csd
                                           FROM Opportunity WHERE CloseDate >= :startThisYear AND CloseDate <= :endThisYear
                                           AND StageName = 'Closed Won'
                                           GROUP BY Account.Id, Account.Name, RecordType.Name, Account.FX_Manager__c, Account.Commodity_Manager__c, Account.IRRM_Manager__c, Opp_PrimaryCurrency__c, Opp_SecondaryCurrency__c
                                           ORDER BY Account.Id, Account.Name, RecordType.Name, Account.FX_Manager__c, Account.Commodity_Manager__c, Account.IRRM_Manager__c, Opp_PrimaryCurrency__c, Opp_SecondaryCurrency__c]; 
        
        
        
        ReportRepOld_Batch obj = new ReportRepOld_Batch(queryLast, queryCurr);
        
        Database.executeBatch(obj,50);
    } 
}