force-app/main/default/objects/Account/fields/Commodity_Manager__c.field-meta.xml
<CustomField>
    <fullName>Commodity_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Commodity Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Commodity Manager)</relationshipLabel>
    <relationshipName>CommodityManagers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/FX_Manager__c.field-meta.xml
<CustomField>
    <fullName>FX_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FX Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (FX Manager)</relationshipLabel>
    <relationshipName>FXManagers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/IRRM_Manager__c.field-meta.xml
<CustomField>
    <fullName>IRRM_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>IRRM Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (IRRM Manager)</relationshipLabel>
    <relationshipName>IRRMManagers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/RM_Name__c.field-meta.xml
<CustomField>
    <fullName>RM_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RM Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND 2</booleanFilter>
        <errorMessage>Please select an active Banker of a respective branch.</errorMessage>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Banker</value>
        </filterItems>
        <filterItems>
            <field>Contact.Contact_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Banker)</relationshipLabel>
    <relationshipName>AccountBanker</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/WID__c.field-meta.xml
<CustomField>
    <fullName>WID__c</fullName>
    <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
    <label>WID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Con_Team__c.field-meta.xml
<CustomField>
    <fullName>Con_Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Business Centre</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Bankers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opp_ETBranchNumber__c.field-meta.xml
<CustomField>
    <fullName>Opp_ETBranchNumber__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ET Branch Number</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opp_PrimaryAmount__c.field-meta.xml
<CustomField>
    <fullName>Opp_PrimaryAmount__c</fullName>
    <label>Primary Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opp_PrimaryCurrency__c.field-meta.xml
<CustomField>
    <fullName>Opp_PrimaryCurrency__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Primary Currency</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opp_SecondaryAmount__c.field-meta.xml
<CustomField>
    <fullName>Opp_SecondaryAmount__c</fullName>
    <label>Secondary Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opp_SecondaryCurrency__c.field-meta.xml
<CustomField>
    <fullName>Opp_SecondaryCurrency__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Secondary Currency</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Repository__c/Repository__c.object-meta.xml
<CustomObject>
    <description>An Object to store and manage data for Report.</description>
    <label>Repository</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Repository Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Repositories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Repository__c/fields/Rep_AccountId__c.field-meta.xml
<CustomField>
    <fullName>Rep_AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Id</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Repositories</relationshipLabel>
    <relationshipName>Repositories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Repository__c/fields/Rep_BusinessCentre__c.field-meta.xml
<CustomField>
    <fullName>Rep_BusinessCentre__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Business Centre</label>
    <length>220</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Repository__c/fields/Rep_CombineId__c.field-meta.xml
<CustomField>
    <fullName>Rep_CombineId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Combine Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Repository__c/fields/Rep_ETBranchNumber__c.field-meta.xml
<CustomField>
    <fullName>Rep_ETBranchNumber__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ET Branch Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Repository__c/fields/Rep_PMName__c.field-meta.xml
<CustomField>
    <fullName>Rep_PMName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>PM</label>
    <length>240</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Repository__c/fields/Rep_RMName__c.field-meta.xml
<CustomField>
    <fullName>Rep_RMName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>RM Name</label>
    <length>220</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Repository__c/fields/Rep_TSMName__c.field-meta.xml
<CustomField>
    <fullName>Rep_TSMName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>FRSM</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Repository__c/fields/Rep_WID__c.field-meta.xml
<CustomField>
    <fullName>Rep_WID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>WID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Repository__c/recordTypes/CustomerAndPM.recordType-meta.xml
<RecordType>
    <fullName>CustomerAndPM</fullName>
    <active>true</active>
    <label>CustomerAndPM</label>
</RecordType>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Business Centre</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Business Centre Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Centres</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/RepCustomerAndPmUpdate.cls
global class RepCustomerAndPmUpdate implements Database.Batchable<sObject>{
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator([select Rep_AccountId__c,Rep_CombineId__c from Repository__c
                                         where recordtype.name='CustomerAndPM' and Rep_TSMName__c=null and Rep_PMName__c=null and Rep_RMName__c=null 
                                         and Rep_BusinessCentre__c=null and Rep_WID__c=null]);
    }
    global void execute(Database.BatchableContext BC, List<Repository__c> scope){
        Date endLastYear = System.today().Addyears(-1);
        Date endThisYear = System.today();        
        Integer startMonth =  CYBGUtilClass.fiscalYearStartMonth();        
        Date startLastYear = CYBGUtilClass.findStartDateOfFY(endLastYear, startMonth ) ;
        Date startThisYear = CYBGUtilClass.findStartDateOfFY(endThisYear, startMonth ) ;
        Map<String,List<Repository__c>> repMapList = new Map<String,List<Repository__c>>();
        Map<String,List<Repository__c>> repMapAccountList = new Map<String,List<Repository__c>>();
        for(Repository__c rep:scope){
            if(repMapList.containskey(rep.Rep_CombineId__c)){
                repMapList.get(rep.Rep_CombineId__c).add(rep);
            }else{
                repMapList.put(rep.Rep_CombineId__c,new List<Repository__c>{rep});
            }   
        }
        for(Repository__c rep:scope){
            if(repMapAccountList.containskey(rep.Rep_AccountId__c)){
                repMapAccountList.get(rep.Rep_AccountId__c).add(rep);
            }else{
                repMapAccountList.put(rep.Rep_AccountId__c,new List<Repository__c>{rep});
            }   
        }
        
        List<Repository__c> repList1 = new List<Repository__c>();
        for(Opportunity opp :[SELECT Id,account.id, account.name, account.owner.name, account.Commodity_Manager__c, 
                              account.FX_Manager__c, account.IRRM_Manager__c, RecordType.Name, Opp_ETBranchNumber__c, 
                              Account.RM_Name__r.Name, Account.RM_Name__r.Con_Team__r.Name, Account.WID__c, 
                              Opp_PrimaryCurrency__c, Opp_PrimaryAmount__c, Opp_SecondaryCurrency__c, Opp_SecondaryAmount__c, 
                              account.Commodity_Manager__r.Name, account.FX_Manager__r.Name, account.IRRM_Manager__r.Name 
                              FROM Opportunity WHERE StageName = 'Closed Won' AND CloseDate >= :startThisYear AND CloseDate <= :endThisYear and accountid in : repMapAccountList.keyset()]){
                                  
                                  String pmSuff = '';
                                  String pmId = '';
                                  String pmName = '';
                                  String repcombinedId='';
                                  if(opp.RecordType.Name == 'FX Cash')
                                  {
                                      pmId = opp.account.FX_Manager__c;
                                      pmName = opp.account.FX_Manager__r.Name;
                                      pmSuff = 'FX';
                                  }
                                  else if(opp.RecordType.Name == 'Commodity')
                                  {
                                      pmId = opp.account.Commodity_Manager__c;
                                      pmName = opp.account.Commodity_Manager__r.Name;
                                      pmSuff = 'COMM';
                                  }
                                  else if(opp.RecordType.Name == 'IRRM')
                                  {
                                      pmId = opp.account.IRRM_Manager__c;
                                      pmName = opp.account.IRRM_Manager__r.Name;
                                      pmSuff = 'IRRM';
                                  }
                                  repcombinedId = opp.account.id + pmId +'CP'+pmSuff+opp.Opp_PrimaryCurrency__c+opp.Opp_SecondaryCurrency__c;
                                  if(repMapList.containskey(repcombinedId)){
                                      for(Repository__c rep1 : repMapList.get(repcombinedId)){
                                          rep1.Rep_TSMName__c = opp.Account.Owner.Name;
                                          rep1.Rep_PMName__c = pmName;
                                          rep1.Rep_RMName__c = opp.Account.RM_Name__r.Name;
                                          rep1.Rep_BusinessCentre__c = opp.Account.RM_Name__r.Con_Team__r.Name;
                                          rep1.Rep_WID__c = opp.Account.WID__c;
                                          rep1.Rep_ETBranchNumber__c = opp.Opp_ETBranchNumber__c;
                                          repList1.add(rep1);
                                      }
                                      
                                  }
                                  
                              }
        update repList1;        
    }
    global void finish(Database.BatchableContext BC){ 
        
    } 
    
}