force-app/main/default/objects/Account/fields/Commodity_Manager__c.field-meta.xml
<CustomField>
    <fullName>Commodity_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Commodity Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Commodity Manager)</relationshipLabel>
    <relationshipName>CommodityManagers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/FX_Manager__c.field-meta.xml
<CustomField>
    <fullName>FX_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FX Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (FX Manager)</relationshipLabel>
    <relationshipName>FXManagers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/IRRM_Manager__c.field-meta.xml
<CustomField>
    <fullName>IRRM_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>IRRM Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (IRRM Manager)</relationshipLabel>
    <relationshipName>IRRMManagers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/RecordType__c.field-meta.xml
<CustomField>
    <fullName>RecordType__c</fullName>
    <label>Record Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Target</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Internal.recordType-meta.xml
<RecordType>
    <fullName>Internal</fullName>
    <active>true</active>
    <label>Internal</label>
</RecordType>

force-app/main/default/objects/Centre__c/Centre__c.object-meta.xml
<CustomObject>
    <label>Region</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Centre__c/fields/Centre_Region__c.field-meta.xml
<CustomField>
    <fullName>Centre_Region__c</fullName>
    <label>Division</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Region is not active.</errorMessage>
        <filterItems>
            <field>Region__c.Region_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Region__c</referenceTo>
    <relationshipLabel>Regions</relationshipLabel>
    <relationshipName>Centres</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Con_Team__c.field-meta.xml
<CustomField>
    <fullName>Con_Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Business Centre</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Bankers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Banker.recordType-meta.xml
<RecordType>
    <fullName>Banker</fullName>
    <active>true</active>
    <label>Banker</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Internal.recordType-meta.xml
<RecordType>
    <fullName>Internal</fullName>
    <active>true</active>
    <description>Used for Treasury Solutions employees</description>
    <label>Internal</label>
</RecordType>

force-app/main/default/objects/Division__c/Division__c.object-meta.xml
<CustomObject>
    <label>Group</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Division__c/fields/Div_Group__c.field-meta.xml
<CustomField>
    <fullName>Div_Group__c</fullName>
    <label>Bank</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Group is not active.</errorMessage>
        <filterItems>
            <field>Group__c.Group_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Group__c</referenceTo>
    <relationshipLabel>Groups</relationshipLabel>
    <relationshipName>Divisions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Group__c/Group__c.object-meta.xml
<CustomObject>
    <label>Bank</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Bank Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Banks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Region__c/Region__c.object-meta.xml
<CustomObject>
    <label>Division</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Division Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Divisions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Region__c/fields/Region_Division__c.field-meta.xml
<CustomField>
    <fullName>Region_Division__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Group</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Division is not active.</errorMessage>
        <filterItems>
            <field>Division__c.Div_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Division__c</referenceTo>
    <relationshipLabel>Divisions</relationshipLabel>
    <relationshipName>Regions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Business Centre</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Business Centre Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Centres</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Team__c/fields/Team_Centre__c.field-meta.xml
<CustomField>
    <fullName>Team_Centre__c</fullName>
    <label>Region</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Centre is not active.</errorMessage>
        <filterItems>
            <field>Centre__c.Centre_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Centre__c</referenceTo>
    <relationshipLabel>Business Centres</relationshipLabel>
    <relationshipName>Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TSMTarget__c/TSMTarget__c.object-meta.xml
<CustomObject>
    <description>To hold the target and actual for a TSM under specific Team</description>
    <label>FRSM Target</label>
    <nameField>
        <displayFormat>Target - {00000}</displayFormat>
        <label>FRSM Target No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FRSM Targets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_EndDate__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_EndDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Plan End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_StartDate__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_StartDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Plan Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_Status__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Ended</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
                <isActive>false</isActive>
                <label>Closed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_Team__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_Team__c</fullName>
    <label>Business Centre</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Team status is not active.</errorMessage>
        <filterItems>
            <field>Team__c.Team_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Team__c</referenceTo>
    <relationshipName>TSMTargets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_TerminationDate__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_TerminationDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Termination Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_TSM__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_TSM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Risk Solutions Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>TSMTargets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>England</fullName>
            </value>
            <value>
                <fullName>Scotland</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TSMTargetTriggerHandler_Test.cls
/*
@Author        : Ramkumar M B
@Name          : TSMTargetTriggerHandler_Test
@Created Date  : 6th March 2018
@Description   : This is a test Class for TSMTargetTriggerHandler
@version       : 1.0
*/
@isTest
public class TSMTargetTriggerHandler_Test {
    
    @testSetup static void setup() {
        
        Id RecordTypeIdContactBanker = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Banker').getRecordTypeId();
        Id RecordTypeIdAccountInternal = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Internal').getRecordTypeId();
        Id RecordTypeIdAccountCustomer = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId();
        User tsmUserManager = TestData.createUser('CYB');
        Insert tsmUserManager;
        User tsmUser = TestData.createUser('System Administrator');
        tsmUser.lastname = 'Tsm User';
        tsmUser.ManagerId = tsmUserManager.id;
        tsmUser.Location__c = 'England';
        tsmUser.Username  = 'tsmuserjournal@testorg.com';
        system.debug('---tsmUser.Location__c'+tsmUser.Location__c);
        insert tsmUser;
        system.runAs(tsmUser){
            Group__c testGroup = TestData.createGroup();
            insert testGroup;        
            Division__c testDivision = TestData.createDivision();
            testDivision.Div_Group__c=testGroup.Id;       
            insert testDivision;        
            Region__c testRegion = TestData.createRegion();
            testRegion.Region_Division__c=testDivision.id;        
            insert testRegion;        
            Centre__c testCentre = TestData.createCentre();
            testCentre.Centre_Region__c=testRegion.id;        
            insert testCentre;
            Team__c testTeam = TestData.createTeam();
            testTeam.Team_Centre__c = testCentre.id; 
            insert testTeam;
            Account accint = TestData.createCalypsoAccountInternal('Clydesdale Bank', RecordTypeIdAccountInternal);
            accint.RecordType__c = 'Internal';
            insert accint;
            Contact con = TestData.createContact('1234', RecordTypeIdContactBanker, accint.Id);
            con.Con_Team__c = testTeam.id;
            insert con;
            Account acc = TestData.createCalypsoAccount('Test Acc', '1245', '1234', con.Id, RecordTypeIdAccountCustomer);
            acc.FX_Manager__c=con.Id;
            acc.IRRM_Manager__c=con.Id;
            acc.Commodity_Manager__c = con.Id;
            acc.RecordType__c = 'Customer';
            insert acc;
        }
    }
    
    
    static TestMethod void createTSMRecordsInvalidEndDate() {
        
        User tsmUser = [Select id from user where Username = 'tsmuserjournal@testorg.com' Limit 1];
        System.runAs(tsmUser)
        {
            /* Centre__c centre = [Select Id from Centre__c];
            List<Team__c>teamList = new List<Team__c>();
            For(integer i=0;i<3;i++)
            {
                Team__c testTeam = TestData.createTeam();
                testTeam.Team_Centre__c = centre.id;
                teamList.add(testTeam);
            }
            insert teamList;*/
            List<TSMTarget__c> tsmTargetList = new List<TSMTarget__c>();
            For(Integer i=0;i<3;i++)
            {
                TSMTarget__c testTarget =  new TSMTarget__c();
                testTarget = TestData.createTSMTarget();
                //testTarget.TSMTar_Team__c = teamList[i].id;
                testTarget.TSMTar_TSM__c = tsmUser.Id;
                testTarget.TSMTar_StartDate__c = System.Today();
                testTarget.TSMTar_EndDate__c = System.Today().AddDays(1);
                tsmTargetList.add(testTarget);
                
            }
            
            Test.startTest();
            Database.SaveResult[] insertResultForTSMTarget = Database.Insert(tsmTargetList, False);
            Test.stopTest();
            List<TSMTarget__c> tc = [Select Id,TSMTar_status__c,TSMTar_StartDate__c,TSMTar_EndDate__c from TSMTarget__c];           
            //system.assertEquals(3, tc.size());
            
        }
        
    }
    static TestMethod void createTSMRecords() {
        
        User tsmUser = [Select id from user where Username = 'tsmuserjournal@testorg.com' Limit 1];
        System.runAs(tsmUser)
        {
           /* Centre__c centre = [Select Id from Centre__c];
            List<Team__c>teamList = new List<Team__c>();
            For(integer i=0;i<3;i++)
            {
                Team__c testTeam = TestData.createTeam();
                testTeam.Team_Centre__c = centre.id;
                teamList.add(testTeam);
            }
            insert teamList;*/
            List<TSMTarget__c> tsmTargetList = new List<TSMTarget__c>();
            For(Integer i=0;i<3;i++)
            {
                TSMTarget__c testTarget =  new TSMTarget__c();
                testTarget = TestData.createTSMTarget();
                //testTarget.TSMTar_Team__c = teamList[i].id;
                testTarget.TSMTar_TSM__c = tsmUser.Id;
                tsmTargetList.add(testTarget);
                
            }
            
            Test.startTest();
            Database.SaveResult[] insertResultForTSMTarget = Database.Insert(tsmTargetList, False);
            Test.stopTest();
            List<TSMTarget__c> tc = [Select Id,TSMTar_status__c,TSMTar_StartDate__c,TSMTar_EndDate__c from TSMTarget__c];           
            //system.assertEquals(3, tc.size());
        }
        
    }
    static TestMethod void createTSMRecordsInvalidStartDate() {
        
        User tsmUser = [Select id from user where Username = 'tsmuserjournal@testorg.com' Limit 1];
        System.runAs(tsmUser)
        {
           /* Centre__c centre = [Select Id from Centre__c];
            List<Team__c>teamList = new List<Team__c>();
            For(integer i=0;i<3;i++)
            {
                Team__c testTeam = TestData.createTeam();
                testTeam.Team_Centre__c = centre.id;
                teamList.add(testTeam);
            }
            insert teamList; */
            List<TSMTarget__c> tsmTargetList = new List<TSMTarget__c>();
            For(Integer i=0;i<3;i++)
            {
                TSMTarget__c testTarget =  new TSMTarget__c();
                testTarget = TestData.createTSMTarget();
                //testTarget.TSMTar_Team__c = teamList[i].id;
                testTarget.TSMTar_TSM__c = tsmUser.Id;
                testTarget.TSMTar_StartDate__c = Date.ValueOf('2017-02-02');
                testTarget.TSMTar_EndDate__c = Date.ValueOf('2018-03-21');
                tsmTargetList.add(testTarget);
                
            }
            
            Test.startTest();
            Database.SaveResult[] insertResultForTSMTarget = Database.Insert(tsmTargetList, False);
            Test.stopTest();
            List<TSMTarget__c> tc = [Select Id,TSMTar_status__c,TSMTar_StartDate__c,TSMTar_EndDate__c from TSMTarget__c];           
            system.debug('TSMTarget__c---'+tc);
            //system.assertEquals(0, tc.size());
            
        }
        
    }
    /*static TestMethod void createTSMRecordsForDuplicate() {
        User tsmUser = [Select id,Location__c from user where Username = 'tsmuserjournal@testorg.com' Limit 1];
        
        system.debug('Locationn'+tsmUser.Location__c);
        Team__c team = [Select Id from Team__c Limit 1];
        Team__c team2 = [Select Id from Team__c Limit 1];
        TSMTarget__c testTarget =  new TSMTarget__c();
        testTarget = TestData.createTSMTarget();
        testTarget.TSMTar_Team__c = team.id;        
        testTarget.TSMTar_TSM__c = tsmUser.Id;
        TSMTarget__c testTarget2 =  new TSMTarget__c();
        testTarget2 = TestData.createTSMTarget();
        testTarget2.TSMTar_Team__c = team2.id;
        testTarget2.TSMTar_TSM__c = tsmUser.Id;
        Test.startTest();
        Insert testTarget;
        try {
            Insert testTarget2;
        } catch (Exception e) {
            system.debug('This is in Catch block');
            System.debug('Exception ' + e);
        }
        
        Test.stopTest();
        
        List<TSMTarget__c> tc = [Select Id,TSMTar_status__c,TSMTar_StartDate__c,TSMTar_EndDate__c from TSMTarget__c];           
        system.debug('TSMTarget__c---'+tc);
        //system.assertEquals(1, tc.size());
        
        
    }*/
    static TestMethod void UpdateTSMRecords() {
        User tsmUser = [Select id from user where Username = 'tsmuserjournal@testorg.com' Limit 1];
        System.runAs(tsmUser)
        {
            /*Centre__c centre = [Select Id from Centre__c];
            List<Team__c>teamList = new List<Team__c>();
            For(integer i=0;i<3;i++)
            {
                Team__c testTeam = TestData.createTeam();
                testTeam.Team_Centre__c = centre.id;
                teamList.add(testTeam);
            }
            insert teamList; */
            List<TSMTarget__c> tsmTargetList = new List<TSMTarget__c>();
            For(Integer i=0;i<3;i++)
            {
                TSMTarget__c testTarget =  new TSMTarget__c();
                testTarget = TestData.createTSMTarget();
                //testTarget.TSMTar_Team__c = teamList[i].id;
                testTarget.TSMTar_TSM__c = tsmUser.Id;
                tsmTargetList.add(testTarget);
                
            }
            Database.SaveResult[] insertResultForTSMTarget = Database.Insert(tsmTargetList, False);
            List<TSMTarget__c> tsmTargetList2 = new List<TSMTarget__c>();
            For(TSMTarget__c tsmtar :[Select Id,TSMTar_status__c,TSMTar_EndDate__c from TSMTarget__c]){
                tsmtar.TSMTar_status__c = 'Terminated';
                tsmtar.TSMTar_TerminationDate__c = system.today();
                tsmTargetList2.add(tsmtar);
            }
            Test.startTest();
            Update tsmTargetList2;
            Test.stopTest();
            List<TSMTarget__c> tc = [Select Id,TSMTar_status__c,TSMTar_StartDate__c,TSMTar_EndDate__c from TSMTarget__c 
                                     where TSMTar_status__c = 'Terminated'];           
            system.debug('TSMTarget__c---'+tc);
            //system.assertEquals(3, tc.size());
            
        }
        
    }     
    
}