force-app/main/default/objects/Account/fields/Commodity_Manager__c.field-meta.xml
<CustomField>
    <fullName>Commodity_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Commodity Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Commodity Manager)</relationshipLabel>
    <relationshipName>CommodityManagers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/FX_Manager__c.field-meta.xml
<CustomField>
    <fullName>FX_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FX Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (FX Manager)</relationshipLabel>
    <relationshipName>FXManagers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/IRRM_Manager__c.field-meta.xml
<CustomField>
    <fullName>IRRM_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>IRRM Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (IRRM Manager)</relationshipLabel>
    <relationshipName>IRRMManagers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Officer_Code__c.field-meta.xml
<CustomField>
    <fullName>Officer_Code__c</fullName>
    <formula>RM_Name__r.Officer_Code__c</formula>
    <label>Officer Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Product</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/RecordType__c.field-meta.xml
<CustomField>
    <fullName>RecordType__c</fullName>
    <label>Record Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Target</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/RM_Name__c.field-meta.xml
<CustomField>
    <fullName>RM_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RM Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND 2</booleanFilter>
        <errorMessage>Please select an active Banker of a respective branch.</errorMessage>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Banker</value>
        </filterItems>
        <filterItems>
            <field>Contact.Contact_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Banker)</relationshipLabel>
    <relationshipName>AccountBanker</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Internal.recordType-meta.xml
<RecordType>
    <fullName>Internal</fullName>
    <active>true</active>
    <label>Internal</label>
</RecordType>

force-app/main/default/objects/Centre__c/Centre__c.object-meta.xml
<CustomObject>
    <label>Region</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Centre__c/fields/Centre_Region__c.field-meta.xml
<CustomField>
    <fullName>Centre_Region__c</fullName>
    <label>Division</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Region is not active.</errorMessage>
        <filterItems>
            <field>Region__c.Region_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Region__c</referenceTo>
    <relationshipLabel>Regions</relationshipLabel>
    <relationshipName>Centres</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Checklist__c/Checklist__c.object-meta.xml
<CustomObject>
    <label>Checklist</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Checklist Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Checklists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Checklist__c/fields/File_Checker__c.field-meta.xml
<CustomField>
    <fullName>File_Checker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>File Checker</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Form1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Checklist__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FX</fullName>
            </value>
            <value>
                <fullName>Commodity</fullName>
            </value>
            <value>
                <fullName>IRRM</fullName>
            </value>
            <value>
                <fullName>Business Loan</fullName>
            </value>
            <value>
                <fullName>CRM</fullName>
            </value>
            <value>
                <fullName>Vanilla FX</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Con_Team__c.field-meta.xml
<CustomField>
    <fullName>Con_Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Business Centre</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Bankers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Officer_Code__c.field-meta.xml
<CustomField>
    <fullName>Officer_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Officer Code</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Banker.recordType-meta.xml
<RecordType>
    <fullName>Banker</fullName>
    <active>true</active>
    <label>Banker</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Internal.recordType-meta.xml
<RecordType>
    <fullName>Internal</fullName>
    <active>true</active>
    <description>Used for Treasury Solutions employees</description>
    <label>Internal</label>
</RecordType>

force-app/main/default/objects/Division__c/Division__c.object-meta.xml
<CustomObject>
    <label>Group</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Division__c/fields/Div_Group__c.field-meta.xml
<CustomField>
    <fullName>Div_Group__c</fullName>
    <label>Bank</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Group is not active.</errorMessage>
        <filterItems>
            <field>Group__c.Group_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Group__c</referenceTo>
    <relationshipLabel>Groups</relationshipLabel>
    <relationshipName>Divisions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <formula>Account.RM_Name__r.Con_Team__r.Team_Centre__r.Centre_Division__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Group</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Region__c/Region__c.object-meta.xml
<CustomObject>
    <label>Division</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Division Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Divisions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Region__c/fields/Region_Division__c.field-meta.xml
<CustomField>
    <fullName>Region_Division__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Group</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Division is not active.</errorMessage>
        <filterItems>
            <field>Division__c.Div_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Division__c</referenceTo>
    <relationshipLabel>Divisions</relationshipLabel>
    <relationshipName>Regions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Repository__c/Repository__c.object-meta.xml
<CustomObject>
    <description>An Object to store and manage data for Report.</description>
    <label>Repository</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Repository Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Repositories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Repository__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Product</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Repository__c/fields/Rep_BusinessCentre__c.field-meta.xml
<CustomField>
    <fullName>Rep_BusinessCentre__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Business Centre</label>
    <length>220</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Repository__c/fields/Rep_BusinessCentreId__c.field-meta.xml
<CustomField>
    <fullName>Rep_BusinessCentreId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Business Centre Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Repository__c/recordTypes/BusinessAndTSM.recordType-meta.xml
<RecordType>
    <fullName>BusinessAndTSM</fullName>
    <active>true</active>
    <label>BusinessAndTSM</label>
</RecordType>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Business Centre</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Business Centre Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Centres</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Team__c/fields/Team_Centre__c.field-meta.xml
<CustomField>
    <fullName>Team_Centre__c</fullName>
    <label>Region</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Centre is not active.</errorMessage>
        <filterItems>
            <field>Centre__c.Centre_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Centre__c</referenceTo>
    <relationshipLabel>Business Centres</relationshipLabel>
    <relationshipName>Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TSMTarget__c/TSMTarget__c.object-meta.xml
<CustomObject>
    <description>To hold the target and actual for a TSM under specific Team</description>
    <label>FRSM Target</label>
    <nameField>
        <displayFormat>Target - {00000}</displayFormat>
        <label>FRSM Target No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FRSM Targets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_EndDate__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_EndDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Plan End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_StartDate__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_StartDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Plan Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_Team__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_Team__c</fullName>
    <label>Business Centre</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Team status is not active.</errorMessage>
        <filterItems>
            <field>Team__c.Team_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Team__c</referenceTo>
    <relationshipName>TSMTargets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_TSM__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_TSM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Risk Solutions Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>TSMTargets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>England</fullName>
            </value>
            <value>
                <fullName>Scotland</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Product.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Vanilla Option</fullName>
    </customValue>
    <customValue>
        <fullName>Participating Forward</fullName>
    </customValue>
    <customValue>
        <fullName>Partial Forward</fullName>
    </customValue>
    <customValue>
        <fullName>Advantage Forward</fullName>
    </customValue>
    <customValue>
        <fullName>Dynamic Forward</fullName>
    </customValue>
    <customValue>
        <fullName>Bonus Forward</fullName>
    </customValue>
    <customValue>
        <fullName>Leverage Product</fullName>
    </customValue>
    <customValue>
        <fullName>Knock Out Forward</fullName>
    </customValue>
    <customValue>
        <fullName>Dual Currency Deposit (DCD)</fullName>
    </customValue>
    <customValue>
        <fullName>Non- Deliverable Forward (NDF)</fullName>
    </customValue>
    <customValue>
        <fullName>Commodity Price Cap</fullName>
    </customValue>
    <customValue>
        <fullName>Commodity Price Swap</fullName>
    </customValue>
    <customValue>
        <fullName>Interest Rate Cap</fullName>
    </customValue>
    <customValue>
        <fullName>Interest Rate Collar</fullName>
    </customValue>
    <customValue>
        <fullName>Interest Rate Swap</fullName>
    </customValue>
    <customValue>
        <fullName>Floating Rate Loan</fullName>
    </customValue>
    <customValue>
        <fullName>Fixed Rate Loan</fullName>
    </customValue>
    <customValue>
        <fullName>Vanilla Spot</fullName>
    </customValue>
    <customValue>
        <fullName>Vanilla Forward</fullName>
    </customValue>
    <customValue>
        <fullName>Aluminium Swap</fullName>
    </customValue>
    <customValue>
        <fullName>Aluminium Cap</fullName>
    </customValue>
    <customValue>
        <fullName>Copper Swap</fullName>
    </customValue>
    <customValue>
        <fullName>Copper Cap</fullName>
    </customValue>
    <customValue>
        <fullName>Nickel Swap</fullName>
    </customValue>
    <customValue>
        <fullName>Nickel Cap</fullName>
    </customValue>
    <customValue>
        <fullName>Zinc Swap</fullName>
    </customValue>
    <customValue>
        <fullName>Zinc Cap</fullName>
    </customValue>
    <customValue>
        <fullName>Gas Oil Swap</fullName>
    </customValue>
    <customValue>
        <fullName>Gas Oil Cap</fullName>
    </customValue>
    <customValue>
        <fullName>Jet Fuel Swap</fullName>
    </customValue>
    <customValue>
        <fullName>FX</fullName>
    </customValue>
    <masterLabel>Product</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ytdPerformanceController_Test.cls
/*
@Author        : Santhoshan
@Name          : OpportunityTrigger_Test
@Created Date  : 24th Jan 2018
@Description   : This is a Test Class for OpportunityTriggerHandler
@version       : 1.0
*/

@isTest
public class ytdPerformanceController_Test{  
    /**
     * @description       Test method to check if the Journals are getting created or not.
     * @name              createOpportunity_Test
     * @param             NA 
     * @return            void
     * @throws            NA
     */ 
    static TestMethod void createOpportunity_Test(){
        List<Opportunity> oppList = new List<Opportunity>();
        List<Opportunity> oppListUpdate = new List<Opportunity>();
        Id RecordTypeIdContactBanker = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Banker').getRecordTypeId();
        Id RecordTypeIdAccountInternal = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Internal').getRecordTypeId();
        Id RecordTypeIdAccountCustomer = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId();
        Id RecordTypeIdOpportunityCRM = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('CRM').getRecordTypeId();
        Id RecordTypeIdOpportunityFX = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('FX Cash').getRecordTypeId();
        Id RecordTypeIdOpportunityComm = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Commodity').getRecordTypeId();
        Id RecordTypeIdOpportunityIRRM = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('IRRM').getRecordTypeId();
        Id RecordTypeRepositoryTSM = Schema.SObjectType.Repository__c.getRecordTypeInfosByName().get('BusinessAndTSM').getRecordTypeId();
        
        User testUser = new user(ID = UserInfo.getUserID());
        
        User tsmUserManager = TestData.createUser('CYB');
        Insert tsmUserManager;
        User tsmUser = TestData.createUser('System Administrator');
        tsmUser.lastname = 'Tsm User';
        tsmUser.ManagerId = tsmUserManager.id;
        tsmUser.Location__c = 'England';
        tsmUser.Username  = 'tsmuserjournal@testorg.com';
        system.debug('---tsmUser.Location__c'+tsmUser.Location__c);
        insert tsmUser;
        
            Group__c groups = TestData.createGroup();
            insert groups;
            
            Division__c division = TestData.createDivision();
            division.Div_Group__c = groups.Id;
            insert division;
            
            Region__c region = TestData.createRegion();
            region.Region_Division__c = division.id;
            insert region;
            
            Centre__c centre = TestData.createCentre();
            centre.Centre_Region__c = region.Id;
            insert centre;
            
            Team__c team = TestData.createTeam();
            team.Name = 'Test Team';
            team.Team_Centre__c = centre.Id;
            insert team;
        
        TSMTarget__c testTarget =  new TSMTarget__c();
                testTarget = TestData.createTSMTarget();
                testTarget.TSMTar_Team__c = team.id;
                testTarget.TSMTar_TSM__c = tsmUser.Id;
                testTarget.TSMTar_StartDate__c = System.Today();
                testTarget.TSMTar_EndDate__c = System.Today().AddDays(1);
                insert testTarget;
            
        Account accint = TestData.createCalypsoAccountInternal('Clydesdale Bank', RecordTypeIdAccountInternal);
        accint.RecordType__c = 'Internal';
        
        insert accint;
        
        Contact con = TestData.createContact('1234', RecordTypeIdContactBanker, accint.Id);
        con.Con_Team__c = team.id;
        con.Officer_Code__c = '1234';
        insert con;
        
        Account acc = TestData.createCalypsoAccount('Test Acc', '1245', '1234', con.Id, RecordTypeIdAccountCustomer);
        acc.FX_Manager__c=con.id;
        acc.RM_Name__c = con.id;
        acc.Commodity_Manager__c=con.id;
        acc.IRRM_Manager__c=con.id;
        acc.RecordType__c = 'Customer';
        insert acc;
        
        
        Checklist__c chkList = TestData.createChecklist(acc.id);
        chkList.File_Checker__c = testUser.Id;
            chkList.Product__c = 'FX';
        insert chkList;
        
        
        List<Repository__c> repList = new List<Repository__c>();
        Repository__c rep1 = new Repository__c();
        rep1.Rep_BusinessCentre__c = team.Name;
        rep1.Rep_BusinessCentreId__c = team.Id;
        rep1.Rep_CombineId__c = team.Id+','+con.Id+','+6;
        rep1.Rep_RMName__c = con.Name;
        rep1.Rep_RMId__c = con.id;
        rep1.Rep_Month__c = 6;
        rep1.Rep_MonthText__c = '6';
        rep1.Rep_FXDirectActual__c = 1200;
        rep1.Rep_FXIndirectActual__c = 1200; 
        rep1.Rep_CommodityActual__c = 1200;
        rep1.Rep_IRRMActual__c = 1200;
        rep1.RecordTypeId = RecordTypeRepositoryTSM;
        insert rep1;
        Repository__c each = [SELECT Rep_CombineId__c, Rep_FXDirectActual__c, Rep_FXIndirectActual__c, Rep_CommodityActual__c, Rep_IRRMActual__c FROM Repository__c];
        
           // wholeMap.put(each.Rep_CombineId__c,each);
        Map<String, Repository__c> wholeMap1= new Map<String, Repository__c>();
        wholeMap1.put(team.Id+','+con.Id+','+6, each);
        RepositoryBatch.wholeMap = wholeMap1;
        
        Opportunity opp = new Opportunity();
        for(Integer i=0; i<100; i++)
        {
            
            opp = TestData.createOpportunity(acc.id, con, chkList.Id, RecordTypeIdOpportunityCRM, 1500, 1500);
            opp.StageName = 'Closed Won';
            opp.opp_TradeID__c='1234'+i;
            opp.CreatedDate = Date.newInstance(2018,06,06);
            opp.Deal_Executed_By__c = con.id;
            if(i==1)
                opp.Opp_BranchNumber__c = System.Label.CBDirectDealingClient;
            else if(i==2)
                opp.Opp_BranchNumber__c = System.Label.YBDirectDealingClient;
            else if(i==3)
                opp.Opp_BranchNumber__c = System.Label.CBCardedRateSheet;
            else if(i==4)
                opp.Opp_BranchNumber__c = System.Label.YBCardedRateSheet;
            else if(i==5)
                opp.Opp_BranchNumber__c = System.Label.CBIndirect;
            else if(i==6)
                opp.Opp_BranchNumber__c = System.Label.YBIndirect;
            else if(i==7)
                opp.Opp_BranchNumber__c = System.Label.CBSortingCode;
            else if(i==8)
                opp.Opp_BranchNumber__c = System.Label.YBSortingCode;
            else if(i==9)
                opp.Opp_BranchNumber__c = System.Label.CBGeneric;
            else if(i==10)
                opp.Opp_BranchNumber__c = System.Label.YBGeneric;
            else if(i==11)
                opp.Opp_BranchNumber__c = null;
            
            
            if(i >= 0 && i<= 20)
                opp.RecordTypeId = RecordTypeIdOpportunityFX;
            else if(i > 20 && i<= 30)
                opp.RecordTypeId = RecordTypeIdOpportunityComm;
            else if(i > 30 && i<= 40)
                opp.RecordTypeId = RecordTypeIdOpportunityIRRM;
            else
                opp.RecordTypeId = RecordTypeIdOpportunityFX;
            if(i >= 60 && i<= 70)
            	opp.StageName = 'New Opportunity';
            else
                opp.StageName = 'Closed Won';
            opp.Amount = 1000;
            oppList.add(opp);
        }
        insert oppList;
        
        
        
        
        CYBGUtilClass.firstRun = true;
        opp.StageName='Closed Won';
        oppListUpdate.add(opp);
        update oppListUpdate;
        Test.startTest();
        
        ytdPerformanceController rmObj = new ytdPerformanceController();
        rmObj.downloadReport();
        rmObj.submitBusCen();
        rmObj.submitRegions();
        rmObj.submitDivisions();
        rmObj.submitGroups();
        rmObj.submitBanks();
        
        Test.stopTest();
        
        
        
    }
    
   
}