force-app/main/default/objects/Account/fields/Commodity_Manager__c.field-meta.xml
<CustomField>
    <fullName>Commodity_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Commodity Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Commodity Manager)</relationshipLabel>
    <relationshipName>CommodityManagers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/FX_Manager__c.field-meta.xml
<CustomField>
    <fullName>FX_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FX Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (FX Manager)</relationshipLabel>
    <relationshipName>FXManagers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/IRRM_Manager__c.field-meta.xml
<CustomField>
    <fullName>IRRM_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>IRRM Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (IRRM Manager)</relationshipLabel>
    <relationshipName>IRRMManagers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Product</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/RecordType__c.field-meta.xml
<CustomField>
    <fullName>RecordType__c</fullName>
    <label>Record Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Target</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Internal.recordType-meta.xml
<RecordType>
    <fullName>Internal</fullName>
    <active>true</active>
    <label>Internal</label>
</RecordType>

force-app/main/default/objects/Centre__c/Centre__c.object-meta.xml
<CustomObject>
    <label>Region</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Centre__c/fields/Centre_Region__c.field-meta.xml
<CustomField>
    <fullName>Centre_Region__c</fullName>
    <label>Division</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Region is not active.</errorMessage>
        <filterItems>
            <field>Region__c.Region_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Region__c</referenceTo>
    <relationshipLabel>Regions</relationshipLabel>
    <relationshipName>Centres</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Checklist__c/Checklist__c.object-meta.xml
<CustomObject>
    <label>Checklist</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Checklist Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Checklists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Checklist__c/fields/File_Checker__c.field-meta.xml
<CustomField>
    <fullName>File_Checker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>File Checker</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Form1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Checklist__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FX</fullName>
            </value>
            <value>
                <fullName>Commodity</fullName>
            </value>
            <value>
                <fullName>IRRM</fullName>
            </value>
            <value>
                <fullName>Business Loan</fullName>
            </value>
            <value>
                <fullName>CRM</fullName>
            </value>
            <value>
                <fullName>Vanilla FX</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Con_Team__c.field-meta.xml
<CustomField>
    <fullName>Con_Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Business Centre</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Bankers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Banker.recordType-meta.xml
<RecordType>
    <fullName>Banker</fullName>
    <active>true</active>
    <label>Banker</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Internal.recordType-meta.xml
<RecordType>
    <fullName>Internal</fullName>
    <active>true</active>
    <description>Used for Treasury Solutions employees</description>
    <label>Internal</label>
</RecordType>

force-app/main/default/objects/Division__c/Division__c.object-meta.xml
<CustomObject>
    <label>Group</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Division__c/fields/Div_Group__c.field-meta.xml
<CustomField>
    <fullName>Div_Group__c</fullName>
    <label>Bank</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Group is not active.</errorMessage>
        <filterItems>
            <field>Group__c.Group_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Group__c</referenceTo>
    <relationshipLabel>Groups</relationshipLabel>
    <relationshipName>Divisions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <formula>Account.RM_Name__r.Con_Team__r.Team_Centre__r.Centre_Division__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Group</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Region__c/Region__c.object-meta.xml
<CustomObject>
    <label>Division</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Division Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Divisions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Region__c/fields/Region_Division__c.field-meta.xml
<CustomField>
    <fullName>Region_Division__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Group</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Division is not active.</errorMessage>
        <filterItems>
            <field>Division__c.Div_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Division__c</referenceTo>
    <relationshipLabel>Divisions</relationshipLabel>
    <relationshipName>Regions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Repository__c/Repository__c.object-meta.xml
<CustomObject>
    <description>An Object to store and manage data for Report.</description>
    <label>Repository</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Repository Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Repositories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Repository__c/fields/Opportunity_RecordType__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_RecordType__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Opportunity RecordType</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Repository__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Product</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Repository__c/fields/Rep_AccountId__c.field-meta.xml
<CustomField>
    <fullName>Rep_AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Id</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Repositories</relationshipLabel>
    <relationshipName>Repositories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Repository__c/fields/Rep_BusinessCentre__c.field-meta.xml
<CustomField>
    <fullName>Rep_BusinessCentre__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Business Centre</label>
    <length>220</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Repository__c/fields/Rep_CombineId__c.field-meta.xml
<CustomField>
    <fullName>Rep_CombineId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Combine Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Repository__c/fields/Rep_PMName__c.field-meta.xml
<CustomField>
    <fullName>Rep_PMName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>PM</label>
    <length>240</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Repository__c/fields/Rep_RMName__c.field-meta.xml
<CustomField>
    <fullName>Rep_RMName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>RM Name</label>
    <length>220</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Repository__c/fields/Rep_TSMName__c.field-meta.xml
<CustomField>
    <fullName>Rep_TSMName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>FRSM</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Repository__c/recordTypes/CustomerAndPM.recordType-meta.xml
<RecordType>
    <fullName>CustomerAndPM</fullName>
    <active>true</active>
    <label>CustomerAndPM</label>
</RecordType>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Business Centre</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Business Centre Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Centres</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Team__c/fields/Team_Centre__c.field-meta.xml
<CustomField>
    <fullName>Team_Centre__c</fullName>
    <label>Region</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Centre is not active.</errorMessage>
        <filterItems>
            <field>Centre__c.Centre_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Centre__c</referenceTo>
    <relationshipLabel>Business Centres</relationshipLabel>
    <relationshipName>Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TSMTarget__c/TSMTarget__c.object-meta.xml
<CustomObject>
    <description>To hold the target and actual for a TSM under specific Team</description>
    <label>FRSM Target</label>
    <nameField>
        <displayFormat>Target - {00000}</displayFormat>
        <label>FRSM Target No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FRSM Targets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_EndDate__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_EndDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Plan End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_StartDate__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_StartDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Plan Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_Team__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_Team__c</fullName>
    <label>Business Centre</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Team status is not active.</errorMessage>
        <filterItems>
            <field>Team__c.Team_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Team__c</referenceTo>
    <relationshipName>TSMTargets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_TSM__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_TSM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Risk Solutions Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>TSMTargets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>England</fullName>
            </value>
            <value>
                <fullName>Scotland</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Product.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Vanilla Option</fullName>
    </customValue>
    <customValue>
        <fullName>Participating Forward</fullName>
    </customValue>
    <customValue>
        <fullName>Partial Forward</fullName>
    </customValue>
    <customValue>
        <fullName>Advantage Forward</fullName>
    </customValue>
    <customValue>
        <fullName>Dynamic Forward</fullName>
    </customValue>
    <customValue>
        <fullName>Bonus Forward</fullName>
    </customValue>
    <customValue>
        <fullName>Leverage Product</fullName>
    </customValue>
    <customValue>
        <fullName>Knock Out Forward</fullName>
    </customValue>
    <customValue>
        <fullName>Dual Currency Deposit (DCD)</fullName>
    </customValue>
    <customValue>
        <fullName>Non- Deliverable Forward (NDF)</fullName>
    </customValue>
    <customValue>
        <fullName>Commodity Price Cap</fullName>
    </customValue>
    <customValue>
        <fullName>Commodity Price Swap</fullName>
    </customValue>
    <customValue>
        <fullName>Interest Rate Cap</fullName>
    </customValue>
    <customValue>
        <fullName>Interest Rate Collar</fullName>
    </customValue>
    <customValue>
        <fullName>Interest Rate Swap</fullName>
    </customValue>
    <customValue>
        <fullName>Floating Rate Loan</fullName>
    </customValue>
    <customValue>
        <fullName>Fixed Rate Loan</fullName>
    </customValue>
    <customValue>
        <fullName>Vanilla Spot</fullName>
    </customValue>
    <customValue>
        <fullName>Vanilla Forward</fullName>
    </customValue>
    <customValue>
        <fullName>Aluminium Swap</fullName>
    </customValue>
    <customValue>
        <fullName>Aluminium Cap</fullName>
    </customValue>
    <customValue>
        <fullName>Copper Swap</fullName>
    </customValue>
    <customValue>
        <fullName>Copper Cap</fullName>
    </customValue>
    <customValue>
        <fullName>Nickel Swap</fullName>
    </customValue>
    <customValue>
        <fullName>Nickel Cap</fullName>
    </customValue>
    <customValue>
        <fullName>Zinc Swap</fullName>
    </customValue>
    <customValue>
        <fullName>Zinc Cap</fullName>
    </customValue>
    <customValue>
        <fullName>Gas Oil Swap</fullName>
    </customValue>
    <customValue>
        <fullName>Gas Oil Cap</fullName>
    </customValue>
    <customValue>
        <fullName>Jet Fuel Swap</fullName>
    </customValue>
    <customValue>
        <fullName>FX</fullName>
    </customValue>
    <customValue>
        <fullName>FXFlexiForward</fullName>
    </customValue>
    <masterLabel>Product</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PMReportUpdateFRSMAndPM_Sched_Test.cls
@isTest
public class PMReportUpdateFRSMAndPM_Sched_Test {
    
    public static testMethod void pmAndFRSMTest(){
        List<Opportunity> OpportunityList = new List<Opportunity>();
        List<Repository__c> repositoryList = new List<Repository__c>();
        Id RecordTypeIdContactBanker = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Banker').getRecordTypeId();
        Id RecordTypeIdContactInternal = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Internal').getRecordTypeId();
        Id RecordTypeIdAccountInternal = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Internal').getRecordTypeId();
        Id RecordTypeIdAccountCustomer = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId();  
        Id RecordTypeIdOpportunityCommodity = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Commodity').getRecordTypeId();
        Id RecordTypeIdOpportunityIRRM = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('IRRM').getRecordTypeId();
        Id RecordTypeIdOpportunityFXCash = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('FX Cash').getRecordTypeId();
        Id RecordTypeIdRepositoryCustomerAndPm = Schema.SObjectType.Repository__c.getRecordTypeInfosByName().get('CustomerAndPM').getRecordTypeId();
        
        User tsmUserManager = TestData.createUser('CYB');
        Insert tsmUserManager;
        User tsmUser1 = TestData.createUser('System Administrator');
        tsmUser1.lastname = 'Tsm User';
        tsmUser1.ManagerId = tsmUserManager.id;
        tsmUser1.Location__c = 'England';
        tsmUser1.Username  = 'tsmuserjournaltransfer1@testorg.com';
        system.debug('---tsmUser.Location__c'+tsmUser1.Location__c);
        insert tsmUser1;
        
        User tsmUser2 = TestData.createUser('System Administrator');
        tsmUser2.lastname = 'Tsm User 2';
        tsmUser2.ManagerId = tsmUserManager.id;
        tsmUser2.Location__c = 'England';
        tsmUser2.Username  = 'tsmuserjournaltransfer2@testorg.com';
        system.debug('---tsmUser.Location__c'+tsmUser2.Location__c);
        insert tsmUser2;
        
        
        Group__c testGroup = TestData.createGroup();
        insert testGroup;        
        Division__c testDivision = TestData.createDivision();        
        testDivision.Div_Group__c=testGroup.Id;
        insert testDivision;        
        
        Region__c testRegion = TestData.createRegion();        
        testRegion.Region_Division__c=testDivision.id;        
        insert testRegion;        
        Centre__c testCentre = TestData.createCentre();
        testCentre.Centre_Region__c=testRegion.id;        
        insert testCentre;
        Team__c testTeam = TestData.createTeam();
        testTeam.Team_Centre__c = testCentre.id; 
        insert testTeam;
        Account acct = TestData.createCalypsoAccountInternal('Clydesdale Bank', RecordTypeIdAccountInternal);
        acct.RecordType__c = 'Internal';
        insert acct;
        
        Contact con = TestData.createContact('1234', RecordTypeIdContactBanker, acct.Id);
        con.Con_Team__c = testTeam.id;
        insert con;
        Contact con1 = TestData.createContact('3456', RecordTypeIdContactBanker, acct.Id);
        con1.Con_Team__c = testTeam.id;
        insert con1;
        Contact con3 = TestData.createContact('1345', RecordTypeIdContactInternal, acct.Id);
        con3.Con_Team__c = testTeam.id;
        insert con3;
        Contact con4 = TestData.createContact('1643', RecordTypeIdContactInternal, acct.Id);
        con4.Con_Team__c = testTeam.id;
        insert con4;        
        Account acc = TestData.createCalypsoAccount('Test Acc', '1245', '1234', con.Id, RecordTypeIdAccountCustomer);
        acc.FX_Manager__c=con3.Id;
        acc.IRRM_Manager__c=con3.Id;
        acc.Commodity_Manager__c = con3.Id;
        acc.RecordType__c = 'Customer';
        insert acc;       
        
        Checklist__c chkList = TestData.createChecklist(acc.id);
        chkList.File_Checker__c = tsmUser1.Id;
        chkList.Product__c = 'FX';
        insert chkList;
        Checklist__c chkListIRRM = TestData.createChecklist(acc.id);
        chkListIRRM.File_Checker__c = tsmUser1.Id;
        chkListIRRM.Product__c = 'IRRM';
        insert chkListIRRM;
        
        Checklist__c chkListCommodity = TestData.createChecklist(acc.id);
        chkListCommodity.File_Checker__c = tsmUser1.Id;
        chkListCommodity.Product__c = 'Commodity';
        insert chkListCommodity;
        
        Date todayDate1 = system.today();
        Integer monthval = todayDate1.month();
        Integer yearval = todayDate1.Year();
        Integer nextMonth = monthval+1;
        Date myDate = Date.newInstance(yearval, nextMonth, 1);
        
        List<TSMTarget__c> tsmTargetList = new List<TSMTarget__c>();
        TSMTarget__c testTarget1 =  new TSMTarget__c();
        testTarget1 = TestData.createTSMTarget();
        testTarget1.TSMTar_Team__c = testTeam.id;
        testTarget1.TSMTar_TSM__c = tsmUser1.Id;
        testTarget1.TSMTar_StartDate__c = System.Today();
        testTarget1.TSMTar_EndDate__c = myDate;
        tsmTargetList.add(testTarget1);
        TSMTarget__c testTarget2 =  new TSMTarget__c();
        testTarget2 = TestData.createTSMTarget();
        testTarget2.TSMTar_Team__c = testTeam.id;
        testTarget2.TSMTar_TSM__c = tsmUser2.Id;
        testTarget2.TSMTar_StartDate__c = System.Today();
        testTarget2.TSMTar_EndDate__c = myDate;
        tsmTargetList.add(testTarget2);
        Database.SaveResult[] insertResultForTSMTarget = Database.Insert(tsmTargetList, False); 
        
        for(Integer i=0;i<=5;i++){
            Repository__c rep = new Repository__c();
            rep.Name = 'a0G1x000000nSuV'+i;
            rep.Rep_CombineId__c = '0011v00001pmRYZAA20030Y00001e2glYQAQCPFXGBPUSD'+i;
            rep.Rep_AccountId__c = acc.id;
            rep.Rep_TSMName__c = '';
            rep.Rep_PMName__c = '';
            rep.Rep_RMName__c = '';
            rep.Rep_BusinessCentre__c = '';
            rep.Opportunity_RecordType__c = 'FX Cash';
            rep.RecordTypeId = RecordTypeIdRepositoryCustomerAndPm;
            rep.Rep_WID__c = '';
            repositoryList.add(rep);
        }
        for(Integer j=11;j<=15;j++){
            Repository__c rep = new Repository__c();
            rep.Name = 'a0G1x000000nSuV'+j;
            rep.Rep_CombineId__c = '0011v00001pmRYZAA20030Y00001e2glYQAQCPFXGBPUSD'+j;
            rep.Rep_AccountId__c = acc.id;
            rep.Rep_TSMName__c = '';
            rep.Rep_PMName__c = '';
            rep.Rep_RMName__c = '';
            rep.Rep_BusinessCentre__c = '';
            rep.Opportunity_RecordType__c = 'IRRM';
            rep.RecordTypeId = RecordTypeIdRepositoryCustomerAndPm;
            rep.Rep_WID__c = '';
            repositoryList.add(rep);
        }
        for(Integer k=16;k<=20;k++){
            Repository__c rep = new Repository__c();
            rep.Name = 'a0G1x000000nSuV'+k;
            rep.Rep_CombineId__c = '0011v00001pmRYZAA20030Y00001e2glYQAQCPFXGBPUSD'+k;
            rep.Rep_AccountId__c = acc.id;
            rep.Rep_TSMName__c = '';
            rep.Rep_PMName__c = '';
            rep.Rep_RMName__c = '';
            rep.Rep_BusinessCentre__c = '';
            rep.Opportunity_RecordType__c = 'Commodity';
            rep.RecordTypeId = RecordTypeIdRepositoryCustomerAndPm;
            rep.Rep_WID__c = '';
            repositoryList.add(rep);
        }
        insert repositoryList;
        
        Opportunity opp1 = TestData.createOpportunity(acc.id, con, chkList.Id, RecordTypeIdOpportunityFXCash, 100, 100);
        opp1.opp_TradeID__c='1235';
        opp1.Deal_Executed_By__c = con.id;
        opp1.Opp_BranchNumber__c = System.Label.CBDirectDealingClient;
        opp1.Amount=100;
        opp1.Opp_PrimaryCurrency__c = 'GBP';
        opp1.Opp_SecondaryCurrency__c = 'GBP';
        opp1.Opp_PrimaryAmount__c = 1200;
        opp1.Opp_SecondaryAmount__c = 600;
        opp1.CloseDate = System.today();
        opp1.Product__c = 'FXFlexiForward';
        opp1.StageName = 'Closed Won';
        OpportunityList.add(opp1);
        
        Opportunity opp11 = TestData.createOpportunity(acc.id, con, chkList.Id, RecordTypeIdOpportunityFXCash, 100, 100);
        opp11.opp_TradeID__c='1136';
        opp11.Deal_Executed_By__c = con.id;
        opp11.Opp_BranchNumber__c = System.Label.CBDirectDealingClient;
        opp11.Amount=100;
        opp11.Opp_PrimaryCurrency__c = 'GBP';
        opp11.Opp_SecondaryCurrency__c = 'GBP';
        opp11.Opp_PrimaryAmount__c = 1200;
        opp11.Opp_SecondaryAmount__c = 600;
        opp11.CloseDate = System.today().addYears(-1);
        opp11.Product__c = 'FXFlexiForward';
        opp11.StageName = 'Closed Won';
        OpportunityList.add(opp11);
        
        Opportunity opp2 = TestData.createOpportunity(acc.id, con, chkList.Id, RecordTypeIdOpportunityIRRM, 100, 100);
        opp2.opp_TradeID__c='1462';
        opp2.Deal_Executed_By__c = con.id;
        opp2.Opp_BranchNumber__c = System.Label.CBCardedRateSheet;
        opp2.Amount=100;
        opp2.Opp_PrimaryCurrency__c = 'USD';
        opp2.Opp_SecondaryCurrency__c = 'GBP';
        opp2.Opp_PrimaryAmount__c = 1200;
        opp2.Opp_SecondaryAmount__c = 600;        
        opp2.CloseDate = System.today();
        opp2.StageName = 'Closed Won';
        OpportunityList.add(opp2); 
        
        Opportunity opp22 = TestData.createOpportunity(acc.id, con, chkList.Id, RecordTypeIdOpportunityIRRM, 100, 100);
        opp22.opp_TradeID__c='1182';
        opp22.Deal_Executed_By__c = con.id;
        opp22.Opp_BranchNumber__c = System.Label.CBCardedRateSheet;
        opp22.Amount=100; 
        opp22.Opp_PrimaryCurrency__c = 'USD';
        opp22.Opp_SecondaryCurrency__c = 'GBP'; 
        opp22.Opp_PrimaryAmount__c = 1200;
        opp22.Opp_SecondaryAmount__c = 600; 
        opp22.CloseDate = System.today().addYears(-1);
        opp22.StageName = 'Closed Won';
        OpportunityList.add(opp22); 
        
        Opportunity opp3 = TestData.createOpportunity(acc.id, con, chkList.Id, RecordTypeIdOpportunityCommodity, 100, 100);
        opp3.opp_TradeID__c='1562';
        opp3.Deal_Executed_By__c = con.id;
        opp3.Opp_BranchNumber__c = System.Label.CBCardedRateSheet;
        opp3.Amount=100;
        opp3.Opp_PrimaryCurrency__c = 'USD';
        opp3.Opp_SecondaryCurrency__c = 'USD';
        opp3.Opp_PrimaryAmount__c = 1200;
        opp3.Opp_SecondaryAmount__c = 600; 
        opp3.CloseDate = System.today();
        opp3.StageName = 'Closed Won';
        OpportunityList.add(opp3); 
        
        Opportunity opp33 = TestData.createOpportunity(acc.id, con, chkList.Id, RecordTypeIdOpportunityCommodity, 100, 100);
        opp33.opp_TradeID__c='1112';
        opp33.Deal_Executed_By__c = con.id;
        opp33.Opp_BranchNumber__c = System.Label.CBCardedRateSheet;
        opp33.Amount=100;
        opp33.Opp_PrimaryCurrency__c = 'USD';
        opp33.Opp_SecondaryCurrency__c = 'USD';
        opp33.Opp_PrimaryAmount__c = 1200;
        opp33.Opp_SecondaryAmount__c = 600;        
        opp33.CloseDate = System.today().addYears(-1);
        opp33.StageName = 'Closed Won';
        OpportunityList.add(opp33);
        
        insert OpportunityList;
        Test.startTest();
        PMReportUpdateFRSMAndPM_Sched pmAndFRSMSch = new PMReportUpdateFRSMAndPM_Sched();
        string sch = '0 0 10 * * ?';
        System.schedule('PM Portfolio',sch,pmAndFRSMSch);
        Test.stopTest();        
    }

}