force-app/main/default/objects/Account/fields/Commodity_Manager__c.field-meta.xml
<CustomField>
    <fullName>Commodity_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Commodity Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Commodity Manager)</relationshipLabel>
    <relationshipName>CommodityManagers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/FX_Manager__c.field-meta.xml
<CustomField>
    <fullName>FX_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FX Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (FX Manager)</relationshipLabel>
    <relationshipName>FXManagers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/IRRM_Manager__c.field-meta.xml
<CustomField>
    <fullName>IRRM_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>IRRM Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (IRRM Manager)</relationshipLabel>
    <relationshipName>IRRMManagers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/RM_Name__c.field-meta.xml
<CustomField>
    <fullName>RM_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RM Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND 2</booleanFilter>
        <errorMessage>Please select an active Banker of a respective branch.</errorMessage>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Banker</value>
        </filterItems>
        <filterItems>
            <field>Contact.Contact_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Banker)</relationshipLabel>
    <relationshipName>AccountBanker</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/WID__c.field-meta.xml
<CustomField>
    <fullName>WID__c</fullName>
    <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
    <label>WID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Con_Team__c.field-meta.xml
<CustomField>
    <fullName>Con_Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Business Centre</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Bankers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opp_ETBranchNumber__c.field-meta.xml
<CustomField>
    <fullName>Opp_ETBranchNumber__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ET Branch Number</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opp_PrimaryAmount__c.field-meta.xml
<CustomField>
    <fullName>Opp_PrimaryAmount__c</fullName>
    <label>Primary Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opp_PrimaryCurrency__c.field-meta.xml
<CustomField>
    <fullName>Opp_PrimaryCurrency__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Primary Currency</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opp_SecondaryAmount__c.field-meta.xml
<CustomField>
    <fullName>Opp_SecondaryAmount__c</fullName>
    <label>Secondary Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opp_SecondaryCurrency__c.field-meta.xml
<CustomField>
    <fullName>Opp_SecondaryCurrency__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Secondary Currency</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Business Centre</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Business Centre Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Centres</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/ReportRepOppty_Batch.cls
global class ReportRepOppty_Batch implements Database.Batchable<sObject>, Database.stateful{ 
    
    global List<Opportunity> oppList;
   
    
    global Database.QueryLocator start(Database.BatchableContext BC){ 
        oppList = new List<Opportunity>();
        Date endLastYear = System.today().Addyears(-1);
        Date endThisYear = System.today();
        
        Integer startMonth =  CYBGUtilClass.fiscalYearStartMonth();
        
        Date startLastYear = CYBGUtilClass.findStartDateOfFY(endLastYear, startMonth ) ;
        Date startThisYear = CYBGUtilClass.findStartDateOfFY(endThisYear, startMonth ) ;
        
        /*String query = 'SELECT Id, account.id, account.name, account.owner.name, account.Commodity_Manager__c, '+
                        'account.FX_Manager__c, account.IRRM_Manager__c, RecordType.Name, Opp_ETBranchNumber__c, '+
                        'Account.RM_Name__r.Name, Account.RM_Name__r.Con_Team__r.Name, Account.WID__c, '+
                        'Opp_PrimaryCurrency__c, Opp_PrimaryAmount__c, Opp_SecondaryCurrency__c, Opp_SecondaryAmount__c, '+
                        'account.Commodity_Manager__r.Name, account.FX_Manager__r.Name, account.IRRM_Manager__r.Name '+
                        'FROM Opportunity WHERE StageName = \'Closed Won\' AND CloseDate >= :startLastYear AND CloseDate <= :endThisYear';
                            */
        Database.QueryLocator oppScope = Database.getQueryLocator([SELECT Id, account.id, account.name, account.owner.name, account.Commodity_Manager__c, 
                        account.FX_Manager__c, account.IRRM_Manager__c, RecordType.Name, Opp_ETBranchNumber__c, 
                        Account.RM_Name__r.Name, Account.RM_Name__r.Con_Team__r.Name, Account.WID__c, 
                        Opp_PrimaryCurrency__c, Opp_PrimaryAmount__c, Opp_SecondaryCurrency__c, Opp_SecondaryAmount__c, 
                        account.Commodity_Manager__r.Name, account.FX_Manager__r.Name, account.IRRM_Manager__r.Name 
                        FROM Opportunity WHERE StageName = 'Closed Won' AND CloseDate >= :startLastYear AND CloseDate <= :endThisYear]);
        
        return oppScope; 
     } 
    
    global void execute(Database.BatchableContext BC, List<sObject> scope){ 
        oppList.addAll((List<Opportunity>)scope);
        //System.debug('List '+oppList.size());
    } 
    global void finish(Database.BatchableContext BC){ 
        //System.debug('List Last'+oppList.size());
        ReportRep_Batch obj = new ReportRep_Batch(oppList);
        Database.executeBatch(obj,100);
    } 
}