force-app/main/default/objects/Account/fields/Commodity_Manager__c.field-meta.xml
<CustomField>
    <fullName>Commodity_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Commodity Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Commodity Manager)</relationshipLabel>
    <relationshipName>CommodityManagers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/FX_Manager__c.field-meta.xml
<CustomField>
    <fullName>FX_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FX Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (FX Manager)</relationshipLabel>
    <relationshipName>FXManagers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/IRRM_Manager__c.field-meta.xml
<CustomField>
    <fullName>IRRM_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>IRRM Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (IRRM Manager)</relationshipLabel>
    <relationshipName>IRRMManagers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/RecordType__c.field-meta.xml
<CustomField>
    <fullName>RecordType__c</fullName>
    <label>Record Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Target</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Internal.recordType-meta.xml
<RecordType>
    <fullName>Internal</fullName>
    <active>true</active>
    <label>Internal</label>
</RecordType>

force-app/main/default/objects/Centre__c/Centre__c.object-meta.xml
<CustomObject>
    <label>Region</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Centre__c/fields/Centre_Region__c.field-meta.xml
<CustomField>
    <fullName>Centre_Region__c</fullName>
    <label>Division</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Region is not active.</errorMessage>
        <filterItems>
            <field>Region__c.Region_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Region__c</referenceTo>
    <relationshipLabel>Regions</relationshipLabel>
    <relationshipName>Centres</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Con_Team__c.field-meta.xml
<CustomField>
    <fullName>Con_Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Business Centre</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Bankers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Banker.recordType-meta.xml
<RecordType>
    <fullName>Banker</fullName>
    <active>true</active>
    <label>Banker</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Internal.recordType-meta.xml
<RecordType>
    <fullName>Internal</fullName>
    <active>true</active>
    <description>Used for Treasury Solutions employees</description>
    <label>Internal</label>
</RecordType>

force-app/main/default/objects/Division__c/Division__c.object-meta.xml
<CustomObject>
    <label>Group</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Division__c/fields/Div_Group__c.field-meta.xml
<CustomField>
    <fullName>Div_Group__c</fullName>
    <label>Bank</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Group is not active.</errorMessage>
        <filterItems>
            <field>Group__c.Group_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Group__c</referenceTo>
    <relationshipLabel>Groups</relationshipLabel>
    <relationshipName>Divisions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Group__c/Group__c.object-meta.xml
<CustomObject>
    <label>Bank</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Bank Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Banks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PMTarget__c/PMTarget__c.object-meta.xml
<CustomObject>
    <label>PM Target</label>
    <nameField>
        <displayFormat>Target - {00000}</displayFormat>
        <label>PM Target No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PM Targets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PMTarget__c/fields/PMTar_EndDate__c.field-meta.xml
<CustomField>
    <fullName>PMTar_EndDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Plan End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PMTarget__c/fields/PMTar_PMContact__c.field-meta.xml
<CustomField>
    <fullName>PMTar_PMContact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product Manager (Contact)</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Product Manager Contact type should be internal and Contact status should be active</errorMessage>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Internal</value>
        </filterItems>
        <filterItems>
            <field>Contact.Contact_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PM Targets</relationshipLabel>
    <relationshipName>PMTargets</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PMTarget__c/fields/PMTar_PMUser__c.field-meta.xml
<CustomField>
    <fullName>PMTar_PMUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Manager (User)</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PMTargets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PMTarget__c/fields/PMTar_StartDate__c.field-meta.xml
<CustomField>
    <fullName>PMTar_StartDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Plan Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PMTarget__c/fields/PMTar_Status__c.field-meta.xml
<CustomField>
    <fullName>PMTar_Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Ended</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
                <isActive>false</isActive>
                <label>Closed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Region__c/Region__c.object-meta.xml
<CustomObject>
    <label>Division</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Division Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Divisions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Region__c/fields/Region_Division__c.field-meta.xml
<CustomField>
    <fullName>Region_Division__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Group</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Division is not active.</errorMessage>
        <filterItems>
            <field>Division__c.Div_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Division__c</referenceTo>
    <relationshipLabel>Divisions</relationshipLabel>
    <relationshipName>Regions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Business Centre</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Business Centre Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Centres</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Team__c/fields/Team_Centre__c.field-meta.xml
<CustomField>
    <fullName>Team_Centre__c</fullName>
    <label>Region</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Centre is not active.</errorMessage>
        <filterItems>
            <field>Centre__c.Centre_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Centre__c</referenceTo>
    <relationshipLabel>Business Centres</relationshipLabel>
    <relationshipName>Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>England</fullName>
            </value>
            <value>
                <fullName>Scotland</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PMTargetTriggerHandler_Test.cls
@isTest
public class PMTargetTriggerHandler_Test 
{
    @testSetup 
    static void setup() {
        
        Id RecordTypeIdContactBanker = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Banker').getRecordTypeId();
        Id RecordTypeIdAccountInternal = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Internal').getRecordTypeId();
        Id RecordTypeIdAccountCustomer = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId();
        
        User tsmUserManager = TestData.createUser('CYB');
        Insert tsmUserManager;
        User tsmUser = TestData.createUser('System Administrator');
        tsmUser.lastname = 'Tsm User';
        tsmUser.ManagerId = tsmUserManager.id;
        tsmUser.Location__c = 'England';
        tsmUser.Username  = 'tsmuserjournal@testorg.com';
        system.debug('---tsmUser.Location__c'+tsmUser.Location__c);
        insert tsmUser;
        system.runAs(tsmUser){
            Group__c testGroup = TestData.createGroup();
            insert testGroup;        
            Division__c testDivision = TestData.createDivision();
            testDivision.Div_Group__c=testGroup.Id;       
            insert testDivision;        
            Region__c testRegion = TestData.createRegion();
            testRegion.Region_Division__c=testDivision.id;        
            insert testRegion;        
            Centre__c testCentre = TestData.createCentre();
            testCentre.Centre_Region__c=testRegion.id;        
            insert testCentre;
            Team__c testTeam = TestData.createTeam();
            testTeam.Team_Centre__c = testCentre.id; 
            insert testTeam;
            Account accint = TestData.createCalypsoAccountInternal('Clydesdale Bank', RecordTypeIdAccountInternal);
            accint.RecordType__c = 'Internal';
            insert accint;
            Contact con = TestData.createContact('1234', RecordTypeIdContactBanker, accint.Id);
            con.Con_Team__c = testTeam.id;
            insert con;
            
            
            Account acc = TestData.createCalypsoAccount('Test Acc', '1245', '1234', con.Id, RecordTypeIdAccountCustomer);
            acc.FX_Manager__c=con.Id;
            acc.IRRM_Manager__c=con.Id;
            acc.Commodity_Manager__c = con.Id;
            acc.RecordType__c = 'Customer';
            insert acc;
        }
    }
    
    static TestMethod void createPMMRecordsInvalidEndDate() { 
        Id RecordTypeIdContactInternal = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Internal').getRecordTypeId();
        Id RecordTypeIdAccountInternal = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Internal').getRecordTypeId();
        User tsmUser = [Select id from user where Username = 'tsmuserjournal@testorg.com' Limit 1];
        Contact con = [Select id from Contact]; 
        System.runAs(tsmUser)
        {
            Date todayDate1 = system.today();
            Integer monthval = todayDate1.month();
            Integer yearval = todayDate1.Year();
            yearval = yearval +2;
            Integer nextMonth = monthval+1;
            Date myDate = Date.newInstance(yearval, nextMonth, 1);
            List<PMTarget__c> pmTargetList = new List<PMTarget__c>();
            Account accint = TestData.createCalypsoAccountInternal('Clydesdale Bank1', RecordTypeIdAccountInternal);
            accint.RecordType__c = 'Internal';
            insert accint;
            Contact conint = TestData.createContactInternal('2345', RecordTypeIdContactInternal, accint.Id);
            insert conint;
            
            
            For(Integer i=0;i<3;i++)
            {
                PMTarget__c testTarget = TestData.createPMMTarget();
                testTarget.PMTar_PMUser__c = tsmUser.Id;
                testTarget.PMTar_PMContact__c = conint.Id;
                testTarget.PMTar_StartDate__c = System.Today();
                testTarget.PMTar_EndDate__c = System.Today().AddDays(1);
                testTarget.PMTar_Status__c = System.Label.Active;
                pmTargetList.add(testTarget);
                
            }
            
            Test.startTest();
            //insert pmTargetList;
            Database.SaveResult[] insertResultForPMTarget = Database.Insert(pmTargetList, False);
            For(Integer i=0;i<3;i++)
            {
                PMTarget__c testTarget = TestData.createPMMTarget();
                testTarget.PMTar_PMUser__c = tsmUser.Id;
                testTarget.PMTar_PMContact__c = conint.Id;
                testTarget.PMTar_StartDate__c = System.Today();
                testTarget.PMTar_EndDate__c = System.Today().AddDays(1);
                testTarget.PMTar_Status__c = System.Label.Active;
                pmTargetList.add(testTarget);
                
            }
            Database.SaveResult[] insertResultForPMTargetSec = Database.Insert(pmTargetList, False);
            pmTargetList[0].PMTar_EndDate__c = System.Today().AddDays(2);
            Database.SaveResult[] updateResultForPMTargetSec = Database.Update(pmTargetList, False);
            Test.stopTest();
            List<PMTarget__c> pm = [Select Id,PMTar_status__c,PMTar_StartDate__c,PMTar_EndDate__c from PMTarget__c];  
            System.debug('HEHEH'+pm);
            //system.assertEquals(3, pm.size());
            
        }
    }
    
    
    static TestMethod void createPMRecordsInvalidStartDate() {
        Id RecordTypeIdContactInternal = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Internal').getRecordTypeId();
        Id RecordTypeIdAccountInternal = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Internal').getRecordTypeId();
        User tsmUser = [Select id from user where Username = 'tsmuserjournal@testorg.com' Limit 1];
        Contact con = [Select id from Contact]; 
        System.runAs(tsmUser)
        {
            Date todayDate1 = system.today();
            Integer monthval = todayDate1.month();
            Integer yearval = todayDate1.Year();
            Integer nextMonth = monthval+1;
            Date myDate = Date.newInstance(yearval, nextMonth, 1);
            Account accint = TestData.createCalypsoAccountInternal('Clydesdale Banks', RecordTypeIdAccountInternal);
            accint.RecordType__c = 'Internal';
            insert accint;
            Contact conint = TestData.createContactInternal('2345', RecordTypeIdContactInternal, accint.Id);
            insert conint;
            List<PMTarget__c> pmTargetList = new List<PMTarget__c>();
            For(Integer i=0;i<3;i++)
            {
                PMTarget__c testTarget =  new PMTarget__c();
                testTarget = TestData.createPMMTarget();
                testTarget.PMTar_PMUser__c = tsmUser.Id;
                testTarget.PMTar_PMContact__c = conint.Id;
                testTarget.PMTar_StartDate__c = Date.ValueOf('2017-02-02');
                testTarget.PMTar_EndDate__c = Date.ValueOf('2018-03-21');
                pmTargetList.add(testTarget);
                
            }
            
            Test.startTest();
            Database.SaveResult[] insertResultForPMTarget = Database.Insert(pmTargetList, False);
            Test.stopTest();
            List<PMTarget__c> pm = [Select Id,PMTar_status__c,PMTar_StartDate__c,PMTar_EndDate__c from PMTarget__c]; 
            system.debug('PM Targets---'+pm);
            //system.assertEquals(0, pm.size());
            
        }
    }
    
    static TestMethod void createPMRecordsForDuplicate() {
        Id RecordTypeIdContactInternal = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Internal').getRecordTypeId();
        Id RecordTypeIdAccountInternal = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Internal').getRecordTypeId();
        User tsmUser = [Select id from user where Username = 'tsmuserjournal@testorg.com' Limit 1];
        Contact con = [Select id from Contact]; 
        Account accint = TestData.createCalypsoAccountInternal('Clydesdale Banks', RecordTypeIdAccountInternal);
            accint.RecordType__c = 'Internal';
            insert accint;
            Contact conint = TestData.createContactInternal('2345', RecordTypeIdContactInternal, accint.Id);
            insert conint;
        System.runAs(tsmUser)
        {
            Date todayDate1 = system.today();
            Integer monthval = todayDate1.month();
            Integer yearval = todayDate1.Year();
            Integer nextMonth = monthval+1;
            Date myDate = Date.newInstance(yearval, nextMonth, 1);
            PMTarget__c testTarget1 =  new PMTarget__c();
            testTarget1 = TestData.createPMMTarget();
            testTarget1.PMTar_PMUser__c = tsmUser.Id;
            testTarget1.PMTar_PMContact__c = conint.Id;
            
            Insert testTarget1;
            PMTarget__c testTarget2 =  new PMTarget__c();
            testTarget2 = TestData.createPMMTarget();
            testTarget2.PMTar_PMUser__c = tsmUser.Id;
            testTarget2.PMTar_PMContact__c = con.Id;
            
            
            Test.startTest();
            try {
                Insert testTarget2;
            } catch (Exception e) {
                system.debug('This is in Catch block');
                System.debug('Exception ' + e);
            }
            Test.stopTest();
            List<PMTarget__c> pm = [Select Id,PMTar_status__c,PMTar_StartDate__c,PMTar_EndDate__c from PMTarget__c]; 
            system.debug('PM Targets---'+pm);
            //system.assertEquals(1, pm.size());
        }
    }
    static TestMethod void UpdatePMTarget() {
        Id RecordTypeIdContactInternal = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Internal').getRecordTypeId();
        Id RecordTypeIdAccountInternal = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Internal').getRecordTypeId();
        User tsmUser = [Select id from user where Username = 'tsmuserjournal@testorg.com' Limit 1];
        Contact con = [Select id from Contact]; 
        System.runAs(tsmUser)
        {
            Date todayDate1 = system.today();
            Integer monthval = todayDate1.month();
            Integer yearval = todayDate1.Year();
            Integer nextMonth = monthval+1;
            Date myDate = Date.newInstance(yearval, nextMonth, 1);
            Account accint = TestData.createCalypsoAccountInternal('Clydesdale Banks', RecordTypeIdAccountInternal);
            accint.RecordType__c = 'Internal';
            insert accint;
            Contact conint = TestData.createContactInternal('2345', RecordTypeIdContactInternal, accint.Id);
            insert conint;
            List<PMTarget__c> pmTargetList = new List<PMTarget__c>();
            For(Integer i=0;i<3;i++)
            {
                PMTarget__c testTarget =  new PMTarget__c();
                testTarget = TestData.createPMMTarget();
                testTarget.PMTar_PMUser__c = tsmUser.Id;
                testTarget.PMTar_PMContact__c = conint.Id;
                testTarget.PMTar_StartDate__c = system.today();
                testTarget.PMTar_EndDate__c = myDate;
                pmTargetList.add(testTarget);
                
            }
            Database.SaveResult[] insertResultForPMTarget = Database.Insert(pmTargetList, False);
            List<PMTarget__c> pmTargetupdateList = new List<PMTarget__c>();
            For(PMTarget__c pmtar :[Select Id,PMTar_status__c,PMTar_StartDate__c,PMTar_EndDate__c from PMTarget__c]){
                system.debug('pmtar Value UpdatePMTarget' +pmtar);
                pmtar.PMTar_status__c = 'Closed';
                myDate = Date.newInstance(yearval, nextMonth, 4);
                pmtar.PMTar_EndDate__c = myDate; 
                pmTargetupdateList.add(pmtar);
                system.debug('UpdatePMTarget ---pmTargetupdateList '+pmTargetupdateList);
            }
            Test.startTest();
            Database.SaveResult[] updateResultForPMMTarget = Database.update(pmTargetupdateList, False);
            Test.stopTest();
            List<PMTarget__c> pm = [Select Id,PMTar_status__c,PMTar_StartDate__c,PMTar_EndDate__c from PMTarget__c
                                   ];
            system.debug('PM Targets---'+pm);
            //system.assertEquals(False, pm.size()>1);
            
        }
    }

}