force-app/main/default/objects/Account/fields/Commodity_Manager__c.field-meta.xml
<CustomField>
    <fullName>Commodity_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Commodity Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Commodity Manager)</relationshipLabel>
    <relationshipName>CommodityManagers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/FX_Manager__c.field-meta.xml
<CustomField>
    <fullName>FX_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FX Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (FX Manager)</relationshipLabel>
    <relationshipName>FXManagers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/IRRM_Manager__c.field-meta.xml
<CustomField>
    <fullName>IRRM_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>IRRM Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (IRRM Manager)</relationshipLabel>
    <relationshipName>IRRMManagers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/RecordType__c.field-meta.xml
<CustomField>
    <fullName>RecordType__c</fullName>
    <label>Record Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Target</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Internal.recordType-meta.xml
<RecordType>
    <fullName>Internal</fullName>
    <active>true</active>
    <label>Internal</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Banker.recordType-meta.xml
<RecordType>
    <fullName>Banker</fullName>
    <active>true</active>
    <label>Banker</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Internal.recordType-meta.xml
<RecordType>
    <fullName>Internal</fullName>
    <active>true</active>
    <description>Used for Treasury Solutions employees</description>
    <label>Internal</label>
</RecordType>

force-app/main/default/objects/Division__c/Division__c.object-meta.xml
<CustomObject>
    <label>Group</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Division__c/fields/Div_Group__c.field-meta.xml
<CustomField>
    <fullName>Div_Group__c</fullName>
    <label>Bank</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Group is not active.</errorMessage>
        <filterItems>
            <field>Group__c.Group_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Group__c</referenceTo>
    <relationshipLabel>Groups</relationshipLabel>
    <relationshipName>Divisions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Group__c/Group__c.object-meta.xml
<CustomObject>
    <label>Bank</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Bank Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Banks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PMTarget__c/PMTarget__c.object-meta.xml
<CustomObject>
    <label>PM Target</label>
    <nameField>
        <displayFormat>Target - {00000}</displayFormat>
        <label>PM Target No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PM Targets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PMTarget__c/fields/PMTar_CRMActual__c.field-meta.xml
<CustomField>
    <fullName>PMTar_CRMActual__c</fullName>
    <defaultValue>0</defaultValue>
    <label>CRM Actual</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PMTarget__c/fields/PMTar_CRMTarget__c.field-meta.xml
<CustomField>
    <fullName>PMTar_CRMTarget__c</fullName>
    <defaultValue>0</defaultValue>
    <label>CRM Target</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PMTarget__c/fields/PMTar_EndDate__c.field-meta.xml
<CustomField>
    <fullName>PMTar_EndDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Plan End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PMTarget__c/fields/PMTar_PMContact__c.field-meta.xml
<CustomField>
    <fullName>PMTar_PMContact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product Manager (Contact)</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Product Manager Contact type should be internal and Contact status should be active</errorMessage>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Internal</value>
        </filterItems>
        <filterItems>
            <field>Contact.Contact_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PM Targets</relationshipLabel>
    <relationshipName>PMTargets</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PMTarget__c/fields/PMTar_PMUser__c.field-meta.xml
<CustomField>
    <fullName>PMTar_PMUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Manager (User)</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PMTargets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PMTarget__c/fields/PMTar_StartDate__c.field-meta.xml
<CustomField>
    <fullName>PMTar_StartDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Plan Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PMTarget__c/fields/PMTar_Status__c.field-meta.xml
<CustomField>
    <fullName>PMTar_Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Ended</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
                <isActive>false</isActive>
                <label>Closed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PMTarget__c/fields/PMTar_TerminationDate__c.field-meta.xml
<CustomField>
    <fullName>PMTar_TerminationDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Termination Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Business Centre</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Business Centre Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Centres</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/PMTargetFiscalYearBatch_Test.cls
/*
@Author        : Santhoshan
@Name          : PMTargetFiscalYearBatch_Test
@Created Date  : 28th Feb 2018
@Description   : This is a Test Class for PMTargetFiscalYearBatchClass
@version       : 1.0
*/
@isTest
public class PMTargetFiscalYearBatch_Test {
    /**
* @description       Test method to check if Active PM Targets are cloned to New Fiscal Year.
* @name              PMTargetsToNewFiscalYear
* @param             NA 
* @return            void
* @throws            NA
*/ 
    static testMethod void clonePMTargetToNewFiscalYear() 
    {
        Id RecordTypeIdContact = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Banker').getRecordTypeId();
        Id RecordTypeIdAccountCustomer = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId();
        Id RecordTypeIdAccountInternal = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Internal').getRecordTypeId();
		Id RecordTypeIdContactInternal = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Internal').getRecordTypeId();
        
        Integer countActive = 0;
        Integer countInactive = 0;
        Integer fyStartMonth = CYBGUtilClass.fiscalYearStartMonth();
        Date startDate = CYBGUtilClass.findStartDateOfFY(System.Today(), fyStartMonth); 
        Date endDate = CYBGUtilClass.findEndDateOfFY(System.Today(), fyStartMonth);        
        
        List<PMTarget__c> PMTarList = new List<PMTarget__c>();
        List<Team__c> teamList = new List<Team__c>();
        List<Contact> conList = new List<Contact>();
        List<PMTarget__c> testQueryList = new List<PMTarget__c>();
        
        User mgrUser = TestData.createMGRUser('CYB');
        insert mgrUser;
        
        Group__c groups = TestData.createGroup();
        insert groups;
        
        Division__c division = TestData.createDivision();
        division.Div_Group__c = groups.Id;
        insert division;
        
        Account acc = TestData.createCalypsoAccountInternal('Clydesdale Bank', RecordTypeIdAccountInternal);
        acc.BillingCity = 'Test City';
        acc.BillingStreet = 'Test Street';
        acc.BillingPostalCode = '12345';
        acc.RecordType__c = 'Internal';
        insert acc;
        Account accint = TestData.createCalypsoAccountInternal('Clydesdale Bank Internal', RecordTypeIdAccountInternal);
        accint.RecordType__c = 'Internal';
        insert accint;
        
        for(Integer i=0; i<20; i++)
        {
            Contact con = TestData.createContactContact('Test Contact'+i, RecordTypeIdContact, acc.Id);
            conList.add(con);
        }
        insert conList;
        
        Contact conint = TestData.createContactInternal('2345', RecordTypeIdContactInternal, accint.Id);
        insert conint;
        
            List<Contact> con = [Select Id,LastName from Contact LIMIT 1];
            Account accCus = TestData.createCalypsoAccount('Test Acc', '1245', '1234', con[0].Id, RecordTypeIdAccountCustomer);
            accCus.FX_Manager__c=con[0].Id;
            accCus.IRRM_Manager__c=con[0].Id;
            accCus.Commodity_Manager__c = con[0].Id;
        	accCus.RecordType__c = 'Customer';
            insert accCus;
        
        
        
        User testUser = TestData.createUser('CYB');
        testUser.ManagerId  = mgrUser.id;
        insert testUser;
        
        
        
        for(Integer i=0;i<20;i++)
        {
            PMTarget__c testPMTar  = TestData.createPMMTarget();
            testPMTar.PMTar_PMContact__c = conint.Id;
            testPMTar.OwnerId = testUser.id;
            testPMTar.PMTar_PMUser__c = testUser.Id;
            testPMTar.PMTar_StartDate__c=System.today();
            testPMTar.PMTar_EndDate__c=System.today().AddDays(1);
            //testPMTar.PMTar_EndDate__c=endDate;
            testPMTar.PMTar_Status__c = 'Active';
            PMTarList.add(testPMTar);
        }
        insert PMTarList;
        List<PMTarget__c> newTargetList = [SELECT Id FROM PMTarget__c];
        System.debug('HERE'+newTargetList);
        List<PMTarget__c> newTargetListUpdate = new List<PMTarget__c>();
        for(Integer i=10; i<20; i++)
        {
            newTargetList[i].PMTar_Status__c = 'Terminated';
            newTargetList[i].PMTar_TerminationDate__c = System.today();
            newTargetListUpdate.add(newTargetList[i]);
        }
        update newTargetListUpdate;
        Test.startTest();
        
        PMTargetFiscalYearBatch testObj = new PMTargetFiscalYearBatch();
        DataBase.executeBatch(testObj); 
        
        Test.stopTest();
        
        testQueryList = [SELECT PMTar_CRMTarget__c, PMTar_CRMActual__c, 
                         PMTar_StartDate__c, PMTar_EndDate__c, PMTar_Status__c
                         FROM PMTarget__c];
        
        for(PMTarget__c eachPM : testQueryList)
        {
            if(eachPM.PMTar_Status__c == 'Active')
            {
                System.assertEquals(eachPM.PMTar_CRMTarget__c, 500);
                System.assertEquals(eachPM.PMTar_CRMActual__c, 0);
                System.assertEquals(eachPM.PMTar_StartDate__c, startDate);
                System.assertEquals(eachPM.PMTar_EndDate__c, endDate);
                countActive++;
            }
            else if(eachPM.PMTar_Status__c == 'Inactive')
            {
                countInactive++;
            }
        }
        System.assertEquals(countActive, 10);
        System.assertEquals(countInactive, 20);
    }

}