force-app/main/default/objects/Account/fields/Commodity_Manager__c.field-meta.xml
<CustomField>
    <fullName>Commodity_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Commodity Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Commodity Manager)</relationshipLabel>
    <relationshipName>CommodityManagers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/FX_Manager__c.field-meta.xml
<CustomField>
    <fullName>FX_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FX Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (FX Manager)</relationshipLabel>
    <relationshipName>FXManagers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/IRRM_Manager__c.field-meta.xml
<CustomField>
    <fullName>IRRM_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>IRRM Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (IRRM Manager)</relationshipLabel>
    <relationshipName>IRRMManagers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/RecordType__c.field-meta.xml
<CustomField>
    <fullName>RecordType__c</fullName>
    <label>Record Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Target</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/RM_Name__c.field-meta.xml
<CustomField>
    <fullName>RM_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RM Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND 2</booleanFilter>
        <errorMessage>Please select an active Banker of a respective branch.</errorMessage>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Banker</value>
        </filterItems>
        <filterItems>
            <field>Contact.Contact_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Banker)</relationshipLabel>
    <relationshipName>AccountBanker</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Internal.recordType-meta.xml
<RecordType>
    <fullName>Internal</fullName>
    <active>true</active>
    <label>Internal</label>
</RecordType>

force-app/main/default/objects/CalypsoData__c/CalypsoData__c.object-meta.xml
<CustomObject>
    <label>Calypso Data</label>
    <nameField>
        <displayFormat>CD-{00000}</displayFormat>
        <label>CData No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Calypso Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CalypsoData__c/fields/CD_Banker__c.field-meta.xml
<CustomField>
    <fullName>CD_Banker__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Banker</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Calypso Data</relationshipLabel>
    <relationshipName>Calypso_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CalypsoData__c/fields/CD_BankName__c.field-meta.xml
<CustomField>
    <fullName>CD_BankName__c</fullName>
    <label>Bank Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CB</fullName>
            </value>
            <value>
                <fullName>YB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CalypsoData__c/fields/CD_BaseEquivalent__c.field-meta.xml
<CustomField>
    <fullName>CD_BaseEquivalent__c</fullName>
    <label>Base Equivalent</label>
    <precision>18</precision>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CalypsoData__c/fields/CD_BranchNumber__c.field-meta.xml
<CustomField>
    <fullName>CD_BranchNumber__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Branch Number</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CalypsoData__c/fields/CD_CIF__c.field-meta.xml
<CustomField>
    <fullName>CD_CIF__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Customer CIF</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CalypsoData__c/fields/CD_CurrencyPair__c.field-meta.xml
<CustomField>
    <fullName>CD_CurrencyPair__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Currency Pair</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CalypsoData__c/fields/CD_DealExecutedBy__c.field-meta.xml
<CustomField>
    <fullName>CD_DealExecutedBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal Executed By</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Calypso Data (Deal Executed By)</relationshipLabel>
    <relationshipName>CD_DealExecutedBy</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CalypsoData__c/fields/CD_ETPNLCCY__c.field-meta.xml
<CustomField>
    <fullName>CD_ETPNLCCY__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ET PNL CCY</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CalypsoData__c/fields/CD_ETRef__c.field-meta.xml
<CustomField>
    <fullName>CD_ETRef__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ET Ref</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CalypsoData__c/fields/CD_ETREUTERSPNL__c.field-meta.xml
<CustomField>
    <fullName>CD_ETREUTERSPNL__c</fullName>
    <label>ET REUTERS PNL</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CalypsoData__c/fields/CD_TradeID__c.field-meta.xml
<CustomField>
    <fullName>CD_TradeID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Trade ID</label>
    <length>35</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CalypsoData__c/fields/CD_TradeSettleDate__c.field-meta.xml
<CustomField>
    <fullName>CD_TradeSettleDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Trade Settle Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CalypsoData__c/fields/CD_TradeStatus__c.field-meta.xml
<CustomField>
    <fullName>CD_TradeStatus__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Trade Status</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CalypsoData__c/fields/CD_WID__c.field-meta.xml
<CustomField>
    <fullName>CD_WID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Customer WID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Centre__c/Centre__c.object-meta.xml
<CustomObject>
    <label>Region</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Centre__c/fields/Centre_Region__c.field-meta.xml
<CustomField>
    <fullName>Centre_Region__c</fullName>
    <label>Division</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Region is not active.</errorMessage>
        <filterItems>
            <field>Region__c.Region_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Region__c</referenceTo>
    <relationshipLabel>Regions</relationshipLabel>
    <relationshipName>Centres</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Con_Team__c.field-meta.xml
<CustomField>
    <fullName>Con_Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Business Centre</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Bankers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Banker.recordType-meta.xml
<RecordType>
    <fullName>Banker</fullName>
    <active>true</active>
    <label>Banker</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Internal.recordType-meta.xml
<RecordType>
    <fullName>Internal</fullName>
    <active>true</active>
    <description>Used for Treasury Solutions employees</description>
    <label>Internal</label>
</RecordType>

force-app/main/default/objects/Division__c/Division__c.object-meta.xml
<CustomObject>
    <label>Group</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Division__c/fields/Div_Group__c.field-meta.xml
<CustomField>
    <fullName>Div_Group__c</fullName>
    <label>Bank</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Group is not active.</errorMessage>
        <filterItems>
            <field>Group__c.Group_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Group__c</referenceTo>
    <relationshipLabel>Groups</relationshipLabel>
    <relationshipName>Divisions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Group__c/Group__c.object-meta.xml
<CustomObject>
    <label>Bank</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Bank Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Banks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <formula>Account.RM_Name__r.Con_Team__r.Team_Centre__r.Centre_Division__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Group</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Region__c/Region__c.object-meta.xml
<CustomObject>
    <label>Division</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Division Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Divisions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Region__c/fields/Region_Division__c.field-meta.xml
<CustomField>
    <fullName>Region_Division__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Group</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Division is not active.</errorMessage>
        <filterItems>
            <field>Division__c.Div_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Division__c</referenceTo>
    <relationshipLabel>Divisions</relationshipLabel>
    <relationshipName>Regions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Repository__c/Repository__c.object-meta.xml
<CustomObject>
    <description>An Object to store and manage data for Report.</description>
    <label>Repository</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Repository Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Repositories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Repository__c/recordTypes/GroupAndDivision.recordType-meta.xml
<RecordType>
    <fullName>GroupAndDivision</fullName>
    <active>true</active>
    <label>GroupAndDivision</label>
</RecordType>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Business Centre</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Business Centre Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Centres</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Team__c/fields/Team_Centre__c.field-meta.xml
<CustomField>
    <fullName>Team_Centre__c</fullName>
    <label>Region</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Centre is not active.</errorMessage>
        <filterItems>
            <field>Centre__c.Centre_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Centre__c</referenceTo>
    <relationshipLabel>Business Centres</relationshipLabel>
    <relationshipName>Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>England</fullName>
            </value>
            <value>
                <fullName>Scotland</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SalesforceLoadedTrade_Sched_Test.cls
@isTest
public class SalesforceLoadedTrade_Sched_Test {
    
    public static testMethod void calypsodataInsert(){
        List<Calypsodata__c> calypsoList = new List<Calypsodata__c>();
        Id RecordTypeIdContactBanker = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Banker').getRecordTypeId();
        Id RecordTypeIdContactInternal = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Internal').getRecordTypeId();
        Id RecordTypeIdAccountInternal = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Internal').getRecordTypeId();
        Id RecordTypeIdAccountCustomer = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId();  
        Id RecordTypeIdOpportunityCommodity = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Commodity').getRecordTypeId();
        Id RecordTypeIdOpportunityIRRM = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('IRRM').getRecordTypeId();
        Id RecordTypeIdOpportunityFXCash = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('FX Cash').getRecordTypeId();
        Id RecordTypeIdRepositroyGroupAndDivision = Schema.SObjectType.Repository__c.getRecordTypeInfosByName().get('GroupAndDivision').getRecordTypeId();
        
        User tsmUserManager = TestData.createUser('CYB');
        Insert tsmUserManager;
        User tsmUserManager1 = TestData.createUser('DL Profile');
        tsmUserManager1.Username = 'dlapiusertest@cybg.com.uatp';
        tsmUserManager1.FirstName = 'DLAPI';
        tsmUserManager1.LastName = 'User';
        Insert tsmUserManager1;
        User tsmUser1 = TestData.createUser('System Administrator');
        tsmUser1.lastname = 'Tsm User';
        tsmUser1.ManagerId = tsmUserManager.id;
        tsmUser1.Location__c = 'England';
        tsmUser1.Username  = 'tsmuserjournaltransfer1@testorg.com';
        system.debug('---tsmUser.Location__c'+tsmUser1.Location__c);
        insert tsmUser1;
        
        User tsmUser2 = TestData.createUser('System Administrator');
        tsmUser2.lastname = 'Tsm User 2';
        tsmUser2.ManagerId = tsmUserManager.id;
        tsmUser2.Location__c = 'England';
        tsmUser2.Username  = 'tsmuserjournaltransfer2@testorg.com';
        system.debug('---tsmUser.Location__c'+tsmUser2.Location__c);
        insert tsmUser2;
        
        System.runAs(tsmUserManager1){
            Group__c testGroup = TestData.createGroup();
            insert testGroup;        
            Division__c testDivision = TestData.createDivision();
            testDivision.Div_Group__c=testGroup.Id;       
            insert testDivision;        
            Region__c testRegion = TestData.createRegion();
            testRegion.Region_Division__c=testDivision.id;        
            insert testRegion;        
            Centre__c testCentre = TestData.createCentre();
            testCentre.Centre_Region__c=testRegion.id;        
            insert testCentre;
            Team__c testTeam = TestData.createTeam();
            testTeam.Team_Centre__c = testCentre.id; 
            insert testTeam;
            Account acct = TestData.createCalypsoAccountInternal('Clydesdale Bank', RecordTypeIdAccountInternal);
            acct.RecordType__c = 'Internal';
            insert acct;
            
            Contact con = TestData.createContact('1234', RecordTypeIdContactBanker, acct.Id);
            con.Con_Team__c = testTeam.id;
            insert con;
            Contact con1 = TestData.createContact('3456', RecordTypeIdContactBanker, acct.Id);
            con1.Con_Team__c = testTeam.id;
            insert con1;
            Contact con3 = TestData.createContact('1345', RecordTypeIdContactInternal, acct.Id);
            con3.Con_Team__c = testTeam.id;
            insert con3;
            Contact con4 = TestData.createContact('1643', RecordTypeIdContactInternal, acct.Id);
            con4.Con_Team__c = testTeam.id;
            insert con4;
           
            Account acc = TestData.createCalypsoAccount('Test Acc', '1245', '1234', con.Id, RecordTypeIdAccountCustomer);
            acc.FX_Manager__c=con3.Id;
            acc.IRRM_Manager__c=con3.Id;
            acc.Commodity_Manager__c = con3.Id;
            acc.RecordType__c = 'Customer';
            acc.RM_Name__c = con.Id;       
            insert acc;        
            
            for(Integer i=0;i<= 30;i++){
                Calypsodata__c calp = new Calypsodata__c();                
                calp.CD_Banker__c = con.id;
                calp.CD_ETRef__c = 'ET_967_0_0';
                calp.CD_TradeStatus__c = 'VERIFIED';
                calp.CD_TradeID__c = '45000000'+i;
                calp.CD_ETREUTERSPNL__c = 2300+i;
                calp.CD_BankName__c = 'CB';
                calp.CD_BranchNumber__c = 'CB Carded Ratesheet';
                calp.CD_CIF__c = '1011857364';
                calp.CD_WID__c = '5025542';
                calp.CD_BaseEquivalent__c = -2619.74;
                calp.CD_CurrencyPair__c = '-2619.74';
                calp.CD_DealExecutedBy__c = con.id;
                calp.CD_ETPNLCCY__c = 'GBP';
                calp.CD_TradeSettleDate__c = system.today();
                
                calypsoList.add(calp);
            }
            insert calypsoList;
        }
        Test.startTest();
        SalesforceLoadedTrade_Sched slts = new SalesforceLoadedTrade_Sched();
        string sch = '0 0 10 * * ?';
        System.schedule('Salesforce Trade Status Schedule',sch,slts);
        Test.stopTest();
    }
}