force-app/main/default/objects/Account/fields/Commodity_Manager__c.field-meta.xml
<CustomField>
    <fullName>Commodity_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Commodity Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Commodity Manager)</relationshipLabel>
    <relationshipName>CommodityManagers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/FX_Manager__c.field-meta.xml
<CustomField>
    <fullName>FX_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FX Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (FX Manager)</relationshipLabel>
    <relationshipName>FXManagers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/IRRM_Manager__c.field-meta.xml
<CustomField>
    <fullName>IRRM_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>IRRM Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (IRRM Manager)</relationshipLabel>
    <relationshipName>IRRMManagers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Product</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/RecordType__c.field-meta.xml
<CustomField>
    <fullName>RecordType__c</fullName>
    <label>Record Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Target</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/RM_Name__c.field-meta.xml
<CustomField>
    <fullName>RM_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RM Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND 2</booleanFilter>
        <errorMessage>Please select an active Banker of a respective branch.</errorMessage>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Banker</value>
        </filterItems>
        <filterItems>
            <field>Contact.Contact_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Banker)</relationshipLabel>
    <relationshipName>AccountBanker</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Internal.recordType-meta.xml
<RecordType>
    <fullName>Internal</fullName>
    <active>true</active>
    <label>Internal</label>
</RecordType>

force-app/main/default/objects/Centre__c/Centre__c.object-meta.xml
<CustomObject>
    <label>Region</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Centre__c/fields/Centre_Region__c.field-meta.xml
<CustomField>
    <fullName>Centre_Region__c</fullName>
    <label>Division</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Region is not active.</errorMessage>
        <filterItems>
            <field>Region__c.Region_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Region__c</referenceTo>
    <relationshipLabel>Regions</relationshipLabel>
    <relationshipName>Centres</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Checklist__c/Checklist__c.object-meta.xml
<CustomObject>
    <label>Checklist</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Checklist Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Checklists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Checklist__c/fields/File_Checker__c.field-meta.xml
<CustomField>
    <fullName>File_Checker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>File Checker</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Form1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Checklist__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FX</fullName>
            </value>
            <value>
                <fullName>Commodity</fullName>
            </value>
            <value>
                <fullName>IRRM</fullName>
            </value>
            <value>
                <fullName>Business Loan</fullName>
            </value>
            <value>
                <fullName>CRM</fullName>
            </value>
            <value>
                <fullName>Vanilla FX</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Con_Team__c.field-meta.xml
<CustomField>
    <fullName>Con_Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Business Centre</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Bankers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Banker.recordType-meta.xml
<RecordType>
    <fullName>Banker</fullName>
    <active>true</active>
    <label>Banker</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Internal.recordType-meta.xml
<RecordType>
    <fullName>Internal</fullName>
    <active>true</active>
    <description>Used for Treasury Solutions employees</description>
    <label>Internal</label>
</RecordType>

force-app/main/default/objects/Division__c/Division__c.object-meta.xml
<CustomObject>
    <label>Group</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Division__c/fields/Div_Group__c.field-meta.xml
<CustomField>
    <fullName>Div_Group__c</fullName>
    <label>Bank</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Group is not active.</errorMessage>
        <filterItems>
            <field>Group__c.Group_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Group__c</referenceTo>
    <relationshipLabel>Groups</relationshipLabel>
    <relationshipName>Divisions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <formula>Account.RM_Name__r.Con_Team__r.Team_Centre__r.Centre_Division__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Group</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PMTarget__c/PMTarget__c.object-meta.xml
<CustomObject>
    <label>PM Target</label>
    <nameField>
        <displayFormat>Target - {00000}</displayFormat>
        <label>PM Target No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PM Targets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PMTarget__c/fields/PMTar_PMUser__c.field-meta.xml
<CustomField>
    <fullName>PMTar_PMUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Manager (User)</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PMTargets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PMTarget__c/fields/PMTar_StartDate__c.field-meta.xml
<CustomField>
    <fullName>PMTar_StartDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Plan Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Region__c/Region__c.object-meta.xml
<CustomObject>
    <label>Division</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Division Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Divisions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Region__c/fields/Region_Division__c.field-meta.xml
<CustomField>
    <fullName>Region_Division__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Group</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Division is not active.</errorMessage>
        <filterItems>
            <field>Division__c.Div_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Division__c</referenceTo>
    <relationshipLabel>Divisions</relationshipLabel>
    <relationshipName>Regions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Repository__c/Repository__c.object-meta.xml
<CustomObject>
    <description>An Object to store and manage data for Report.</description>
    <label>Repository</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Repository Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Repositories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Repository__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Product</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Business Centre</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Business Centre Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Centres</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Team__c/fields/Team_Centre__c.field-meta.xml
<CustomField>
    <fullName>Team_Centre__c</fullName>
    <label>Region</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Centre is not active.</errorMessage>
        <filterItems>
            <field>Centre__c.Centre_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Centre__c</referenceTo>
    <relationshipLabel>Business Centres</relationshipLabel>
    <relationshipName>Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TSMTarget__c/TSMTarget__c.object-meta.xml
<CustomObject>
    <description>To hold the target and actual for a TSM under specific Team</description>
    <label>FRSM Target</label>
    <nameField>
        <displayFormat>Target - {00000}</displayFormat>
        <label>FRSM Target No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FRSM Targets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_EndDate__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_EndDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Plan End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_StartDate__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_StartDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Plan Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_Team__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_Team__c</fullName>
    <label>Business Centre</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Team status is not active.</errorMessage>
        <filterItems>
            <field>Team__c.Team_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Team__c</referenceTo>
    <relationshipName>TSMTargets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_TSM__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_TSM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Risk Solutions Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>TSMTargets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>England</fullName>
            </value>
            <value>
                <fullName>Scotland</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Product.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Vanilla Option</fullName>
    </customValue>
    <customValue>
        <fullName>Participating Forward</fullName>
    </customValue>
    <customValue>
        <fullName>Partial Forward</fullName>
    </customValue>
    <customValue>
        <fullName>Advantage Forward</fullName>
    </customValue>
    <customValue>
        <fullName>Dynamic Forward</fullName>
    </customValue>
    <customValue>
        <fullName>Bonus Forward</fullName>
    </customValue>
    <customValue>
        <fullName>Leverage Product</fullName>
    </customValue>
    <customValue>
        <fullName>Knock Out Forward</fullName>
    </customValue>
    <customValue>
        <fullName>Dual Currency Deposit (DCD)</fullName>
    </customValue>
    <customValue>
        <fullName>Non- Deliverable Forward (NDF)</fullName>
    </customValue>
    <customValue>
        <fullName>Commodity Price Cap</fullName>
    </customValue>
    <customValue>
        <fullName>Commodity Price Swap</fullName>
    </customValue>
    <customValue>
        <fullName>Interest Rate Cap</fullName>
    </customValue>
    <customValue>
        <fullName>Interest Rate Collar</fullName>
    </customValue>
    <customValue>
        <fullName>Interest Rate Swap</fullName>
    </customValue>
    <customValue>
        <fullName>Floating Rate Loan</fullName>
    </customValue>
    <customValue>
        <fullName>Fixed Rate Loan</fullName>
    </customValue>
    <customValue>
        <fullName>Vanilla Spot</fullName>
    </customValue>
    <customValue>
        <fullName>Vanilla Forward</fullName>
    </customValue>
    <customValue>
        <fullName>Aluminium Swap</fullName>
    </customValue>
    <customValue>
        <fullName>Aluminium Cap</fullName>
    </customValue>
    <customValue>
        <fullName>Copper Swap</fullName>
    </customValue>
    <customValue>
        <fullName>Copper Cap</fullName>
    </customValue>
    <customValue>
        <fullName>Nickel Swap</fullName>
    </customValue>
    <customValue>
        <fullName>Nickel Cap</fullName>
    </customValue>
    <customValue>
        <fullName>Zinc Swap</fullName>
    </customValue>
    <customValue>
        <fullName>Zinc Cap</fullName>
    </customValue>
    <customValue>
        <fullName>Gas Oil Swap</fullName>
    </customValue>
    <customValue>
        <fullName>Gas Oil Cap</fullName>
    </customValue>
    <customValue>
        <fullName>Jet Fuel Swap</fullName>
    </customValue>
    <customValue>
        <fullName>FX</fullName>
    </customValue>
    <customValue>
        <fullName>FXFlexiForward</fullName>
    </customValue>
    <masterLabel>Product</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/QuarterEndForecasting_Test.cls
@isTest
public class QuarterEndForecasting_Test {

    static testMethod void testclass(){
       Id RecordTypeIdContactBanker = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Banker').getRecordTypeId();
        Id RecordTypeIdContactInternal = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Internal').getRecordTypeId();

        Id RecordTypeIdAccountInternal = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Internal').getRecordTypeId();
        Id RecordTypeIdAccountCustomer = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId();  
        Id RecordTypeIdOpportunityCommodity = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Commodity').getRecordTypeId();
        Id RecordTypeIdOpportunityIRRM = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('IRRM').getRecordTypeId();
        Id RecordTypeIdOpportunityFXCash = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('FX Cash').getRecordTypeId();
        
        User tsmUserManager = TestData.createUser('CYB');
        Insert tsmUserManager;
        User tsmUser1 = TestData.createUser('System Administrator');
        tsmUser1.lastname = 'Tsm User';
        tsmUser1.ManagerId = tsmUserManager.id;
        tsmUser1.Location__c = 'England';
        tsmUser1.Username  = 'tsmuserjournaltransfer1@testorg.com';
        system.debug('---tsmUser.Location__c'+tsmUser1.Location__c);
        insert tsmUser1;
        
        User tsmUser2 = TestData.createUser('System Administrator');
        tsmUser2.lastname = 'Tsm User 2';
        tsmUser2.ManagerId = tsmUserManager.id;
        tsmUser2.Location__c = 'England';
        tsmUser2.Username  = 'tsmuserjournaltransfer2@testorg.com';
        system.debug('---tsmUser.Location__c'+tsmUser2.Location__c);
        insert tsmUser2;
         
        
            Group__c testGroup = TestData.createGroup();
            insert testGroup;        
            Division__c testDivision = TestData.createDivision();
            testDivision.Div_Group__c=testGroup.Id;       
            insert testDivision;        
            Region__c testRegion = TestData.createRegion();
            testRegion.Region_Division__c=testDivision.id;        
            insert testRegion;        
            Centre__c testCentre = TestData.createCentre();
            testCentre.Centre_Region__c=testRegion.id;        
            insert testCentre;
            Team__c testTeam = TestData.createTeam();
            testTeam.Team_Centre__c = testCentre.id; 
            insert testTeam;
            Account acct = TestData.createCalypsoAccountInternal('Clydesdale Bank', RecordTypeIdAccountInternal);
            acct.RecordType__c = 'Internal';
            insert acct;
            
            Contact con = TestData.createContact('1234', RecordTypeIdContactBanker, acct.Id);
            con.Con_Team__c = testTeam.id;
            insert con;
            Contact con1 = TestData.createContact('3456', RecordTypeIdContactBanker, acct.Id);
            con1.Con_Team__c = testTeam.id;
            insert con1;
            Contact con3 = TestData.createContact('1345', RecordTypeIdContactInternal, acct.Id);
            con3.Con_Team__c = testTeam.id;
            insert con3;
            Contact con4 = TestData.createContact('1643', RecordTypeIdContactInternal, acct.Id);
            con4.Con_Team__c = testTeam.id;
            insert con4;
            Account accint = TestData.createCalypsoAccountInternal('Demo Customer', RecordTypeIdAccountCustomer);
            accint.RecordType__c = 'Customer';
            accint.RM_Name__c = con.id;
                
           // insert accint;
            Account acc = TestData.createCalypsoAccount('Test Acc', '1245', '1234', con.Id, RecordTypeIdAccountCustomer);
            acc.FX_Manager__c=con3.Id;
            acc.IRRM_Manager__c=con3.Id;
            acc.Commodity_Manager__c = con3.Id;
            acc.RecordType__c = 'Customer';
            insert acc;
        
        
            Checklist__c chkList = TestData.createChecklist(acc.id);
            chkList.File_Checker__c = tsmUser1.Id;
            chkList.Product__c = 'FX';
            insert chkList;
            Checklist__c chkListIRRM = TestData.createChecklist(acc.id);
            chkListIRRM.File_Checker__c = tsmUser1.Id;
            chkListIRRM.Product__c = 'IRRM';
            insert chkListIRRM;
        
            Checklist__c chkListCommodity = TestData.createChecklist(acc.id);
            chkListCommodity.File_Checker__c = tsmUser1.Id;
            chkListCommodity.Product__c = 'Commodity';
            insert chkListCommodity;
               Date todayDate1 = system.today();
               Integer monthval = todayDate1.month();
               Integer yearval = todayDate1.Year();
               Integer nextMonth = monthval+1;
               Date myDate = Date.newInstance(yearval, nextMonth, 1);
               List<TSMTarget__c> tsmTargetList = new List<TSMTarget__c>();
                TSMTarget__c testTarget1 =  new TSMTarget__c();
                testTarget1 = TestData.createTSMTarget();
                testTarget1.TSMTar_Team__c = testTeam.id;
                testTarget1.TSMTar_TSM__c = tsmUser1.Id;
                testTarget1.TSMTar_StartDate__c = System.Today();
                testTarget1.TSMTar_EndDate__c = myDate;
                tsmTargetList.add(testTarget1);
                TSMTarget__c testTarget2 =  new TSMTarget__c();
                testTarget2 = TestData.createTSMTarget();
                testTarget2.TSMTar_Team__c = testTeam.id;
                testTarget2.TSMTar_TSM__c = tsmUser2.Id;
                testTarget2.TSMTar_StartDate__c = System.Today();
                testTarget2.TSMTar_EndDate__c = myDate;
                tsmTargetList.add(testTarget2);
                Database.SaveResult[] insertResultForTSMTarget = Database.Insert(tsmTargetList, False);
                List<PMTarget__c>pmList = New List<PMTarget__c>();
            PMTarget__c testPMTarget1 = TestData.createPMMTarget();
            testPMTarget1.PMTar_StartDate__c = system.today();
            testPMTarget1.PMTar_PMUser__c = tsmUser1.Id;
            testPMTarget1.PMTar_PMContact__c = con3.Id;
            testPMTarget1.PMTar_EndDate__c = myDate;
            pmList.add(testPMTarget1);
            PMTarget__c testPMTarget2 = TestData.createPMMTarget();
            testPMTarget2.PMTar_StartDate__c = system.today();
            testPMTarget2.PMTar_PMUser__c = tsmUser2.Id;
            testPMTarget2.PMTar_PMContact__c = con4.Id;
            testPMTarget2.PMTar_EndDate__c = myDate;
            pmList.add(testPMTarget2);    
            //Insert pmList;
        
        system.runAs(tsmUser1){
            List<Opportunity>oppList = new List<Opportunity>();
            Opportunity opp1 = TestData.createOpportunity(acc.id, con, chkList.Id, RecordTypeIdOpportunityFXCash, 100, 100);
            opp1.opp_TradeID__c='1235';
            opp1.Deal_Executed_By__c = con.id;
            opp1.Opp_BranchNumber__c = System.Label.CBDirectDealingClient;
            opp1.Amount=100;
            opp1.CloseDate = System.today();
            opp1.Product__c = 'FXFlexiForward';
            opp1.StageName = 'Closed Won';
            oppList.add(opp1);
            Opportunity opp2 = TestData.createOpportunity(acc.id, con, chkList.Id, RecordTypeIdOpportunityFXCash, 100, 100);
            opp2.opp_TradeID__c='1462';
            opp2.Deal_Executed_By__c = con.id;
            opp2.Opp_BranchNumber__c = System.Label.CBCardedRateSheet;
            opp2.Amount=100;
            opp2.Product__c = 'FXFlexiForward';
            opp2.CloseDate = System.today().AddMonths(1);
            opp2.StageName = 'Closed Won';
            oppList.add(opp2);
            Insert oppList;
            
    }
        

        system.runAs(tsmUser2){
            
            List<Opportunity>oppList = new List<Opportunity>();
        Opportunity opp6 = TestData.createOpportunity(acc.id, con, chkList.Id, RecordTypeIdOpportunityFXCash, 100, 100);
            opp6.opp_TradeID__c='1469';
            opp6.Deal_Executed_By__c = con.id;
            opp6.Opp_BranchNumber__c = null;
            opp6.Product__c = 'FXFlexiForward';
            opp6.CloseDate = System.today();
            opp6.Amount=100;
            opp6.StageName = 'Closed Won';
            oppList.add(opp6);
            Opportunity opp7 = TestData.createOpportunity(acc.id, con, chkList.Id, RecordTypeIdOpportunityFXCash, 100, 100);
            opp7.opp_TradeID__c='146911';
            opp7.Deal_Executed_By__c = con.id;
            opp7.Opp_BranchNumber__c = null;
            opp7.Product__c = 'FXFlexiForward';
            opp7.CloseDate = System.today().addMonths(1);
            opp7.Amount=100;
            opp7.StageName = 'Closed Won';
            oppList.add(opp7);
            Opportunity opp3 = TestData.createOpportunity(acc.id, con, chkListIRRM.Id, RecordTypeIdOpportunityIRRM, 1500, 1500);
            opp3.opp_TradeID__c='175634';
            opp3.Deal_Executed_By__c = con.id;
            opp3.StageName = 'Closed Won';
            oppList.add(opp3);
            Opportunity opp4 = TestData.createOpportunity(acc.id, con, chkListCommodity.Id, RecordTypeIdOpportunityCommodity, 110,110);
            opp4.opp_TradeID__c='12754';
            opp4.Deal_Executed_By__c = con.id;
            opp4.Amount=0;
            opp4.StageName = 'Closed Won';
            oppList.add(opp4);
            
            Insert oppList;
        }
        List<Repository__c> repList = new List<Repository__c>();
        Repository__c rep1 = new Repository__c();
        rep1.Rep_BusinessCentre__c = '1234';
        rep1.Rep_BusinessCentreId__c = '1234';
        rep1.Rep_CombineId__c = '12341234';
        rep1.Rep_RMName__c = '2344';
        rep1.Rep_RMId__c = '2344';
        rep1.Rep_Month__c = 6;
        rep1.Rep_MonthText__c = '6';
        rep1.Rep_FXDirectActual__c = 1200;
        rep1.Rep_FXIndirectActual__c = 1200; 
        rep1.Rep_CommodityActual__c = 1200;
        rep1.Rep_IRRMActual__c = 1200;
        insert rep1;
        
        
		Test.startTest();
        QuarterEndForecasting rmObj = new QuarterEndForecasting();
        rmObj.downloadReport();
        Test.stopTest();
        
  
    }
    
    
      
     

}