force-app/main/default/objects/Account/fields/FX_Manager__c.field-meta.xml
<CustomField>
    <fullName>FX_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FX Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (FX Manager)</relationshipLabel>
    <relationshipName>FXManagers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
    <label>Product</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/RecordType__c.field-meta.xml
<CustomField>
    <fullName>RecordType__c</fullName>
    <label>Record Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Target</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Internal.recordType-meta.xml
<RecordType>
    <fullName>Internal</fullName>
    <active>true</active>
    <label>Internal</label>
</RecordType>

force-app/main/default/objects/CalypsoData__c/CalypsoData__c.object-meta.xml
<CustomObject>
    <label>Calypso Data</label>
    <nameField>
        <displayFormat>CD-{00000}</displayFormat>
        <label>CData No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Calypso Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CalypsoData__c/fields/CD_BankName__c.field-meta.xml
<CustomField>
    <fullName>CD_BankName__c</fullName>
    <label>Bank Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CB</fullName>
            </value>
            <value>
                <fullName>YB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CalypsoData__c/fields/CD_BranchNumber__c.field-meta.xml
<CustomField>
    <fullName>CD_BranchNumber__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Branch Number</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CalypsoData__c/fields/CD_CIF__c.field-meta.xml
<CustomField>
    <fullName>CD_CIF__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Customer CIF</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CalypsoData__c/fields/CD_ConversionStatus__c.field-meta.xml
<CustomField>
    <fullName>CD_ConversionStatus__c</fullName>
    <label>Conversion Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Converted</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Discarded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CalypsoData__c/fields/CD_Customer__c.field-meta.xml
<CustomField>
    <fullName>CD_Customer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Calypso Data</relationshipLabel>
    <relationshipName>CalypsoData</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CalypsoData__c/fields/CD_DealExecutedBy__c.field-meta.xml
<CustomField>
    <fullName>CD_DealExecutedBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal Executed By</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Calypso Data (Deal Executed By)</relationshipLabel>
    <relationshipName>CD_DealExecutedBy</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CalypsoData__c/fields/CD_ErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>CD_ErrorMessage__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Error Message</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CalypsoData__c/fields/CD_ETRef__c.field-meta.xml
<CustomField>
    <fullName>CD_ETRef__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ET Ref</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CalypsoData__c/fields/CD_ETREUTERSPNL__c.field-meta.xml
<CustomField>
    <fullName>CD_ETREUTERSPNL__c</fullName>
    <label>ET REUTERS PNL</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CalypsoData__c/fields/CD_ETTraderID__c.field-meta.xml
<CustomField>
    <fullName>CD_ETTraderID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ET Trader ID</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CalypsoData__c/fields/CD_HasDuplicate__c.field-meta.xml
<CustomField>
    <fullName>CD_HasDuplicate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Duplicate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CalypsoData__c/fields/CD_TradeID__c.field-meta.xml
<CustomField>
    <fullName>CD_TradeID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Trade ID</label>
    <length>35</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CalypsoData__c/fields/CD_TradeStatus__c.field-meta.xml
<CustomField>
    <fullName>CD_TradeStatus__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Trade Status</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CalypsoData__c/fields/CD_UserAction__c.field-meta.xml
<CustomField>
    <fullName>CD_UserAction__c</fullName>
    <label>User Action</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Save</fullName>
            </value>
            <value>
                <fullName>Discard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CalypsoData__c/fields/CD_WID__c.field-meta.xml
<CustomField>
    <fullName>CD_WID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Customer WID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Centre__c/Centre__c.object-meta.xml
<CustomObject>
    <label>Region</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Centre__c/fields/Centre_Region__c.field-meta.xml
<CustomField>
    <fullName>Centre_Region__c</fullName>
    <label>Division</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Region is not active.</errorMessage>
        <filterItems>
            <field>Region__c.Region_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Region__c</referenceTo>
    <relationshipLabel>Regions</relationshipLabel>
    <relationshipName>Centres</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Checklist__c/Checklist__c.object-meta.xml
<CustomObject>
    <label>Checklist</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Checklist Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Checklists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Checklist__c/fields/File_Checker__c.field-meta.xml
<CustomField>
    <fullName>File_Checker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>File Checker</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Form1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Checklist__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FX</fullName>
            </value>
            <value>
                <fullName>Commodity</fullName>
            </value>
            <value>
                <fullName>IRRM</fullName>
            </value>
            <value>
                <fullName>Business Loan</fullName>
            </value>
            <value>
                <fullName>CRM</fullName>
            </value>
            <value>
                <fullName>Vanilla FX</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Con_Team__c.field-meta.xml
<CustomField>
    <fullName>Con_Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Business Centre</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Bankers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Banker.recordType-meta.xml
<RecordType>
    <fullName>Banker</fullName>
    <active>true</active>
    <label>Banker</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Internal.recordType-meta.xml
<RecordType>
    <fullName>Internal</fullName>
    <active>true</active>
    <description>Used for Treasury Solutions employees</description>
    <label>Internal</label>
</RecordType>

force-app/main/default/objects/Division__c/Division__c.object-meta.xml
<CustomObject>
    <label>Group</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Division__c/fields/Div_Group__c.field-meta.xml
<CustomField>
    <fullName>Div_Group__c</fullName>
    <label>Bank</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Group is not active.</errorMessage>
        <filterItems>
            <field>Group__c.Group_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Group__c</referenceTo>
    <relationshipLabel>Groups</relationshipLabel>
    <relationshipName>Divisions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Group__c/Group__c.object-meta.xml
<CustomObject>
    <label>Bank</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Bank Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Banks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/JournalLineItem__c/JournalLineItem__c.object-meta.xml
<CustomObject>
    <description>Journal Line Item</description>
    <label>Journal Line Item</label>
    <nameField>
        <displayFormat>J-{00000}</displayFormat>
        <label>Journal Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journal Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <formula>Account.RM_Name__r.Con_Team__r.Team_Centre__r.Centre_Division__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Group</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Region__c/Region__c.object-meta.xml
<CustomObject>
    <label>Division</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Division Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Divisions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Region__c/fields/Region_Division__c.field-meta.xml
<CustomField>
    <fullName>Region_Division__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Group</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Division is not active.</errorMessage>
        <filterItems>
            <field>Division__c.Div_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Division__c</referenceTo>
    <relationshipLabel>Divisions</relationshipLabel>
    <relationshipName>Regions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Business Centre</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Business Centre Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Centres</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Team__c/fields/Team_Centre__c.field-meta.xml
<CustomField>
    <fullName>Team_Centre__c</fullName>
    <label>Region</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Centre is not active.</errorMessage>
        <filterItems>
            <field>Centre__c.Centre_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Centre__c</referenceTo>
    <relationshipLabel>Business Centres</relationshipLabel>
    <relationshipName>Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Product.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Vanilla Option</fullName>
    </customValue>
    <customValue>
        <fullName>Participating Forward</fullName>
    </customValue>
    <customValue>
        <fullName>Partial Forward</fullName>
    </customValue>
    <customValue>
        <fullName>Advantage Forward</fullName>
    </customValue>
    <customValue>
        <fullName>Dynamic Forward</fullName>
    </customValue>
    <customValue>
        <fullName>Bonus Forward</fullName>
    </customValue>
    <customValue>
        <fullName>Leverage Product</fullName>
    </customValue>
    <customValue>
        <fullName>Knock Out Forward</fullName>
    </customValue>
    <customValue>
        <fullName>Dual Currency Deposit (DCD)</fullName>
    </customValue>
    <customValue>
        <fullName>Non- Deliverable Forward (NDF)</fullName>
    </customValue>
    <customValue>
        <fullName>Commodity Price Cap</fullName>
    </customValue>
    <customValue>
        <fullName>Commodity Price Swap</fullName>
    </customValue>
    <customValue>
        <fullName>Interest Rate Cap</fullName>
    </customValue>
    <customValue>
        <fullName>Interest Rate Collar</fullName>
    </customValue>
    <customValue>
        <fullName>Interest Rate Swap</fullName>
    </customValue>
    <customValue>
        <fullName>Floating Rate Loan</fullName>
    </customValue>
    <customValue>
        <fullName>Fixed Rate Loan</fullName>
    </customValue>
    <customValue>
        <fullName>Vanilla Spot</fullName>
    </customValue>
    <customValue>
        <fullName>Vanilla Forward</fullName>
    </customValue>
    <customValue>
        <fullName>Aluminium Swap</fullName>
    </customValue>
    <customValue>
        <fullName>Aluminium Cap</fullName>
    </customValue>
    <customValue>
        <fullName>Copper Swap</fullName>
    </customValue>
    <customValue>
        <fullName>Copper Cap</fullName>
    </customValue>
    <customValue>
        <fullName>Nickel Swap</fullName>
    </customValue>
    <customValue>
        <fullName>Nickel Cap</fullName>
    </customValue>
    <customValue>
        <fullName>Zinc Swap</fullName>
    </customValue>
    <customValue>
        <fullName>Zinc Cap</fullName>
    </customValue>
    <customValue>
        <fullName>Gas Oil Swap</fullName>
    </customValue>
    <customValue>
        <fullName>Gas Oil Cap</fullName>
    </customValue>
    <customValue>
        <fullName>Jet Fuel Swap</fullName>
    </customValue>
    <customValue>
        <fullName>FX</fullName>
    </customValue>
    <masterLabel>Product</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CalypsoDataTriggerHandler_Test.cls
/*
@Author        : Santhoshan
@Name          : CalypsoDataTriggerHandler_Test
@Created Date  : 21st Jan 2018
@Description   : This is a Test Class for CalypsoDataTriggerHandler
@version       : 1.0
*/

@isTest
public class CalypsoDataTriggerHandler_Test { 
    /**
* @description       Test method to check if Customer is updated if the valid WID is provided.
* @name              createOpportunity_Test
* @param             NA 
* @return            void
* @throws            NA
*/ 
    static testMethod void CalypsoDataTriggerHandler_TestMethodWID() {
        
        List<CalypsoData__c> calypsoDataList = new List<CalypsoData__c>();
        List<CalypsoData__c> calypsoQueryList = new List<CalypsoData__c>();
        
        Id RecordTypeIdContactBanker = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Banker').getRecordTypeId();
        Id RecordTypeIdAccountInternal = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Internal').getRecordTypeId();
        Id RecordTypeIdAccountCustomer = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId();
        Id RecordTypeIdOpportunityCRM = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('CRM').getRecordTypeId();
        User testUser = new user(ID = UserInfo.getUserID());
        //insert testUser;
        system.runAs(testUser)
        {            
            Group__c groups = TestData.createGroup();
            insert groups;
            
            Division__c division = TestData.createDivision();
            division.Div_Group__c = groups.Id;
            insert division;
            
            Region__c region = TestData.createRegion();
            region.Region_Division__c = division.id;
            insert region;
            
            Centre__c centre = TestData.createCentre();
            centre.Centre_Region__c = region.Id;
            insert centre;
            
            Team__c team = TestData.createTeam();
            team.Name = 'Test Team';
            team.Team_Centre__c = centre.Id;
            insert team;
            
            Account accint = TestData.createCalypsoAccountInternal('Clydesdale Bank', RecordTypeIdAccountInternal);
            accint.RecordType__c='Internal';
            insert accint;
            
            Contact con = TestData.createContact('1234', RecordTypeIdContactBanker, accint.Id);
            con.Con_Team__C = team.id;
            insert con;
            
            Account acc = TestData.createCalypsoAccount('Test Acc', '1245', '1234', con.Id, RecordTypeIdAccountCustomer);
            acc.FX_Manager__c=con.id;
            acc.RecordType__c='Customer';
            insert acc;
            
            Checklist__c chkLst = TestData.createChecklist(acc.Id);
            chkLst.File_Checker__c = testUser.Id;
            chkLst.Product__c = 'FX';
            insert chkLst;
            
            Opportunity opp = TestData.createOpportunity(acc.id, con, chkLst.Id, RecordTypeIdOpportunityCRM, 1500, 1500);
            
            opp.StageName='Closed Won';
            insert opp;
            
            for(Integer i=0;i<100;i++)
            {
                CalypsoData__c cdTestWID = TestData.createCalypsoData();
                cdTestWID.CD_WID__c='1245'; 
                cdTestWID.CD_TradeID__c=String.valueOf(10101010+i);
                cdTestWID.CD_TradeStatus__c='Verified';
                if(i==2)
                {
                    cdTestWID.CD_UserAction__c = System.Label.Save;
                    cdTestWID.CD_HasDuplicate__c = false;
                    cdTestWID.CD_ETTraderID__c = con.Name;
                }
                calypsoDataList.add(cdTestWID);
            }            
            Test.startTest();
            insert calypsoDataList;
            Test.stopTest();            
            calypsoQueryList = [SELECT CD_Customer__c FROM CalypsoData__c];            
            for(CalypsoData__c calypsoData : calypsoQueryList){                
                //System.assertEquals(acc.id, calypsoData.CD_Customer__c);
            }
            
        }    
    }
    
    
    /**
* @description       Test method to check if Customer is updated if the valid CIF is provided.
* @name              createOpportunity_Test
* @param             NA 
* @return            void
* @throws            NA
*/ 
    static testMethod void CalypsoDataTriggerHandler_TestMethodCIF() {
        List<CalypsoData__c> calypsoDataList = new List<CalypsoData__c>();
        List<CalypsoData__c> calypsoQueryList = new List<CalypsoData__c>();        
        Id RecordTypeIdContactBanker = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Banker').getRecordTypeId();
        Id RecordTypeIdAccountInternal = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Internal').getRecordTypeId();
        Id RecordTypeIdAccountCustomer = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId();
        Id RecordTypeIdOpportunityCRM = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('CRM').getRecordTypeId();
        User testUser = new user(ID = UserInfo.getUserID());
        
        system.runAs(testUser)
        {
            Group__c groups = TestData.createGroup();
            insert groups;
            
            Division__c division = TestData.createDivision();
            division.Div_Group__c = groups.Id;
            insert division;
            
            Region__c region = TestData.createRegion();
            region.Region_Division__c = division.id;
            insert region;
            
            Centre__c centre = TestData.createCentre();
            centre.Centre_Region__c = region.Id;
            insert centre;
            
            Team__c team = TestData.createTeam();
            team.Name = 'Test Team';
            team.Team_Centre__c = centre.Id;
            insert team;
            
            Account accint = TestData.createCalypsoAccountInternal('Clydesdale Bank', RecordTypeIdAccountInternal);
            accint.RecordType__c='Internal';
            insert accint;
            
            Contact con = TestData.createContact('1234', RecordTypeIdContactBanker, accint.Id);
            con.con_team__c = team.id;
            insert con;
            
            Account acc = TestData.createCalypsoAccount('Test Acc', '1245', '1234', con.Id, RecordTypeIdAccountCustomer);
            acc.FX_Manager__c=con.id;
            acc.RecordType__c='Customer';
            insert acc;
            
            Checklist__c chkLst = TestData.createChecklist(acc.Id);
            chkLst.File_Checker__c = testUser.Id;
            chkLst.Product__c = 'FX';
            insert chkLst;
            
            Opportunity opp = TestData.createOpportunity(acc.id, con, chkLst.Id, RecordTypeIdOpportunityCRM,1500,1500);
            opp.StageName = 'Closed Won';
            insert opp;
            
            for(Integer i=0;i<100;i++){
                CalypsoData__c cdTestCIF = TestData.createCalypsoData();
                cdTestCIF.CD_CIF__c='1234'; 
                cdTestCIF.CD_TradeID__c=String.valueOf(10101010+i);
                cdTestCIF.CD_TradeStatus__c='Verified';
                cdTestCIF.CD_BranchNumber__c = 'CB Direct Dealing Client';
                cdTestCIF.CD_ETTraderID__c = con.id;
                calypsoDataList.add(cdTestCIF);
            }
            Test.startTest();
            insert calypsoDataList;
            Test.stopTest();
            calypsoQueryList = [SELECT CD_Customer__c FROM CalypsoData__c];            
            for(CalypsoData__c calypsoData : calypsoQueryList){                
                //System.assertEquals(acc.id, calypsoData.CD_Customer__c);
            }            
        }
    }
    
    
    /**
* @description       Test method to check all the Error Conditions.
* @name              createOpportunity_Test
* @param             NA 
* @return            void
* @throws            NA
*/ 
    static testMethod void CalypsoDataTriggerHandler_TestMethodErrorCustomer() {
        List<CalypsoData__c> calypsoDataList = new List<CalypsoData__c>();
        List<CalypsoData__c> calypsoDataListUpdate = new List<CalypsoData__c>();
        List<CalypsoData__c> calypsoQueryList = new List<CalypsoData__c>();
        
        Id RecordTypeIdContactBanker = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Banker').getRecordTypeId();
        Id RecordTypeIdAccountInternal = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Internal').getRecordTypeId();
        Id RecordTypeIdAccountCustomer = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId();
        Id RecordTypeIdOpportunityCRM = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('CRM').getRecordTypeId();
        User testUser = new user(ID = UserInfo.getUserID());
        system.runAs(testUser)
        {
            Group__c groups = TestData.createGroup();
            insert groups;
            
            Division__c division = TestData.createDivision();
            division.Div_Group__c = groups.Id;
            insert division;
            
            Region__c region = TestData.createRegion();
            region.Region_Division__c = division.id;
            insert region;
            
            Centre__c centre = TestData.createCentre();
            centre.Centre_Region__c = region.Id;
            insert centre;
            
            Team__c team = TestData.createTeam();
            team.Name = 'Test Team';
            team.Team_Centre__c = centre.Id;
            insert team;
            
            Account accint = TestData.createCalypsoAccountInternal('Clydesdale Bank', RecordTypeIdAccountInternal);
            accint.RecordType__c='Internal';
            insert accint;
            
            Contact con = TestData.createContact('1234', RecordTypeIdContactBanker, accint.Id);
            con.Con_Team__c = team.id;
            insert con;
            
            Account acc = TestData.createCalypsoAccount('Test Acc', '1245', '1234', con.Id, RecordTypeIdAccountCustomer);
            acc.FX_Manager__c=con.Id;
            acc.RecordType__c='Customer';
            insert acc;
            
            Checklist__c chkLst = TestData.createChecklist(acc.Id);
            chkLst.File_Checker__c = testUser.Id;
            chkLst.Product__c = 'FX';
            insert chkLst;
            
            Opportunity opp = TestData.createOpportunity(acc.id, con, chkLst.Id, RecordTypeIdOpportunityCRM,1500,1500);
            opp.StageName = 'Closed Won';
            insert opp;
            CalypsoData__c cdTestError = TestData.createCalypsoData();
            cdTestError.CD_CIF__c='1234';
            cdTestError.CD_UserAction__c = System.Label.Discard;
            cdTestError.CD_TradeID__c=String.valueOf(10101910);
            cdTestError.CD_TradeStatus__c='Verified';
            
            calypsoDataList.add(cdTestError);      
            
            CalypsoData__c cdTestErrorFail = TestData.createCalypsoData();
            cdTestErrorFail.CD_CIF__c='1234';
            cdTestErrorFail.CD_UserAction__c = System.Label.Discard;
            cdTestErrorFail.CD_TradeID__c=String.valueOf(10109910);
            cdTestErrorFail.CD_ConversionStatus__c=System.Label.Failed;
            cdTestErrorFail.CD_TradeStatus__c='Verified';
            calypsoDataList.add(cdTestErrorFail);                        
            
            for(Integer i=0;i<50;i++)
            {
                CalypsoData__c cdTestError2 = TestData.createCalypsoData();
                cdTestError2.CD_CIF__c='1234';
                cdTestError2.CD_Customer__c=acc.Id;
                cdTestError2.CD_HasDuplicate__c=true;
                cdTestError2.CD_TradeID__c=String.valueOf(10101010+i);
                cdTestError2.CD_TradeStatus__c='Verified';
                calypsoDataList.add(cdTestError2);
            }
            
            insert calypsoDataList;
            
            cdTestError.CD_ETREUTERSPNL__c=2500; 
            calypsoDataListUpdate.add(cdTestError);
            
            Test.startTest();
            CYBGUtilClass.runBeforeTrigger=true;
            update calypsoDataListUpdate;            
            Test.stopTest();
            
            calypsoQueryList = [SELECT CD_ETREUTERSPNL__c FROM CalypsoData__c WHERE 
                                Id=:cdTestError.Id];
            
            for(CalypsoData__c calypsoData : calypsoQueryList)
            {
                //System.assertEquals(2500, calypsoData.CD_ETREUTERSPNL__c);
            }
            
        }
    }
    static testMethod void CalypsoDataTriggerHandler_TradeKeyword() {
        
		List<CalypsoData__c> calypsoDataListError = new List<CalypsoData__c>();
        List<CalypsoData__c> calypsoDataList = new List<CalypsoData__c>();
        List<CalypsoData__c> calypsoQueryList = new List<CalypsoData__c>();
        List<JournalLineItem__c> journalQueryList = new List<JournalLineItem__c>();
        
        Id RecordTypeIdContactBanker = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Banker').getRecordTypeId();
        Id RecordTypeIdAccountInternal = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Internal').getRecordTypeId();
        Id RecordTypeIdAccountCustomer = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId();
        Id RecordTypeIdOpportunityCRM = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('CRM').getRecordTypeId();
        User testUser = new user(ID = UserInfo.getUserID());
        
        system.runAs(testUser)
        {        
           
            Account accint = TestData.createCalypsoAccountInternal('Clydesdale Bank', RecordTypeIdAccountInternal);
            accint.RecordType__c='Internal';
            insert accint;
            
            Contact con = TestData.createContact('1234', RecordTypeIdContactBanker, accint.Id);
            insert con;
            
            Account acc = TestData.createCalypsoAccount('Test Acc', '1245', '1234', null, RecordTypeIdAccountCustomer);
            acc.FX_Manager__c=con.id;
            acc.RecordType__c='Customer';
            insert acc;
            
            for(Integer i=0;i<9;i++)
            {
                CalypsoData__c cdTestWID = TestData.createCalypsoData();
                cdTestWID.CD_WID__c='1245';
                cdTestWID.CD_BankName__c = 'CB';
                cdTestWID.CD_ETRef__c = String.valueOf(10+i);
                cdTestWID.CD_TradeID__c=String.valueOf(10101010+i);
                cdTestWID.CD_TradeStatus__c='Verified';
                cdTestWID.CD_DealExecutedBy__c = con.Id;
                cdTestWID.CD_ETREUTERSPNL__c = 2000;
                
                if(math.mod(i, 2) == 0)
                    cdTestWID.CD_BranchNumber__c='CB Carded Ratesheet';
                else
                    cdTestWID.CD_BranchNumber__c='CB Direct Dealing Client';
                calypsoDataList.add(cdTestWID);
            }    
            
            for(Integer i=5;i<9;i++)
            {
				CalypsoData__c cdTestWID = TestData.createCalypsoData();
                cdTestWID.CD_WID__c='1245';
                cdTestWID.CD_BankName__c = 'CB';
                cdTestWID.CD_ETRef__c = String.valueOf(10+i);
                cdTestWID.CD_TradeID__c=String.valueOf(10101010+i);
                cdTestWID.CD_TradeStatus__c='Verified';
                cdTestWID.CD_DealExecutedBy__c = con.Name;
                cdTestWID.CD_ETREUTERSPNL__c = 2000;
                
                if(math.mod(i, 2) == 0)
                    cdTestWID.CD_BranchNumber__c='CB Carded Ratesheet';
                else
                    cdTestWID.CD_BranchNumber__c='CB Direct Dealing Client';
                calypsoDataList.add(cdTestWID);
            } 
            Test.startTest();
            insert calypsoDataList;
			
            Test.stopTest();            
            calypsoQueryList = [SELECT CD_Customer__c, CD_TradeID__c, CD_ConversionStatus__c, CD_ErrorMessage__c FROM CalypsoData__c];            
            for(CalypsoData__c calypsoData : calypsoQueryList){                
                //System.assertEquals(acc.id, calypsoData.CD_Customer__c);
            }
            
            AggregateResult[] arOpp = [SELECT Count(ID)total FROM Opportunity];
            System.assertEquals(0, arOpp[0].get('total'));
            
            AggregateResult[] arJnl = [SELECT Count(ID)total FROM JournalLineItem__c];
            //System.assertEquals(0, arJnl[0].get('total'));
        }    
    }
}