force-app/main/default/objects/Account/fields/FX_Manager__c.field-meta.xml
<CustomField>
    <fullName>FX_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FX Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (FX Manager)</relationshipLabel>
    <relationshipName>FXManagers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Officer_Code__c.field-meta.xml
<CustomField>
    <fullName>Officer_Code__c</fullName>
    <formula>RM_Name__r.Officer_Code__c</formula>
    <label>Officer Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/RM_Name__c.field-meta.xml
<CustomField>
    <fullName>RM_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RM Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND 2</booleanFilter>
        <errorMessage>Please select an active Banker of a respective branch.</errorMessage>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Banker</value>
        </filterItems>
        <filterItems>
            <field>Contact.Contact_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Banker)</relationshipLabel>
    <relationshipName>AccountBanker</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Con_Centre__c.field-meta.xml
<CustomField>
    <fullName>Con_Centre__c</fullName>
    <formula>Con_Team__r.Team_Centre__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Con_Division__c.field-meta.xml
<CustomField>
    <fullName>Con_Division__c</fullName>
    <formula>Con_Team__r.Team_Division__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Group</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Con_Group__c.field-meta.xml
<CustomField>
    <fullName>Con_Group__c</fullName>
    <formula>Con_Team__r.Team_Group__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Bank</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Con_Region__c.field-meta.xml
<CustomField>
    <fullName>Con_Region__c</fullName>
    <formula>Con_Team__r.Team_Region__c</formula>
    <label>Division</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Con_Team__c.field-meta.xml
<CustomField>
    <fullName>Con_Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Business Centre</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Bankers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Officer_Code__c.field-meta.xml
<CustomField>
    <fullName>Officer_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Officer Code</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/isQ6Available__c.field-meta.xml
<CustomField>
    <fullName>isQ6Available__c</fullName>
    <formula>IF(Account.Officer_Code__c != null, true, false)</formula>
    <label>Is Q6 Available</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opp_BranchNumber__c.field-meta.xml
<CustomField>
    <fullName>Opp_BranchNumber__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Branch Number</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opp_CorpCode__c.field-meta.xml
<CustomField>
    <fullName>Opp_CorpCode__c</fullName>
    <formula>IF( NOT( ISBLANK( TEXT(Opp_BankName__c) ) ) , TEXT(Opp_BankName__c) , 
IF( NOT( ISBLANK( TEXT(Account.Branch__c ) ) ), 
IF(TEXT(Account.Branch__c) = &#39;Clydesdale Bank&#39; , &#39;CB&#39;, 
IF(TEXT(Account.Branch__c) = &#39;Yorkshire Bank&#39; , &#39;YB&#39;, &#39;&#39;)), &#39;&#39;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Corp Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Repository__c/Repository__c.object-meta.xml
<CustomObject>
    <description>An Object to store and manage data for Report.</description>
    <label>Repository</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Repository Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Repositories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Repository__c/fields/Rep_BankName__c.field-meta.xml
<CustomField>
    <fullName>Rep_BankName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Bank Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Repository__c/fields/Rep_BusinessActual__c.field-meta.xml
<CustomField>
    <fullName>Rep_BusinessActual__c</fullName>
    <label>Business Loan Actual</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Repository__c/fields/Rep_BusinessCentre__c.field-meta.xml
<CustomField>
    <fullName>Rep_BusinessCentre__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Business Centre</label>
    <length>220</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Repository__c/fields/Rep_BusinessCentreId__c.field-meta.xml
<CustomField>
    <fullName>Rep_BusinessCentreId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Business Centre Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Repository__c/fields/Rep_CombineId__c.field-meta.xml
<CustomField>
    <fullName>Rep_CombineId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Combine Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Repository__c/fields/Rep_CommodityActual__c.field-meta.xml
<CustomField>
    <fullName>Rep_CommodityActual__c</fullName>
    <label>Commodity Actual</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Repository__c/fields/Rep_CustomerName__c.field-meta.xml
<CustomField>
    <fullName>Rep_CustomerName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Customer Name</label>
    <length>220</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Repository__c/fields/Rep_DivisionName__c.field-meta.xml
<CustomField>
    <fullName>Rep_DivisionName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Division Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Repository__c/fields/Rep_FX_Manager__c.field-meta.xml
<CustomField>
    <fullName>Rep_FX_Manager__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>FX Manager</label>
    <length>220</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Repository__c/fields/Rep_FXDirectActual__c.field-meta.xml
<CustomField>
    <fullName>Rep_FXDirectActual__c</fullName>
    <label>FX Direct Actual</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Repository__c/fields/Rep_FXIndirectActual__c.field-meta.xml
<CustomField>
    <fullName>Rep_FXIndirectActual__c</fullName>
    <label>FX Indirect Actual</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Repository__c/fields/Rep_GroupName__c.field-meta.xml
<CustomField>
    <fullName>Rep_GroupName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Group Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Repository__c/fields/Rep_IRRMActual__c.field-meta.xml
<CustomField>
    <fullName>Rep_IRRMActual__c</fullName>
    <label>IRRM Actual</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Repository__c/fields/Rep_Month__c.field-meta.xml
<CustomField>
    <fullName>Rep_Month__c</fullName>
    <label>Month</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Repository__c/fields/Rep_MonthText__c.field-meta.xml
<CustomField>
    <fullName>Rep_MonthText__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Month Text</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Repository__c/fields/Rep_Q6Code__c.field-meta.xml
<CustomField>
    <fullName>Rep_Q6Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Q6 Code</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Repository__c/fields/Rep_RegionName__c.field-meta.xml
<CustomField>
    <fullName>Rep_RegionName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Region Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Repository__c/fields/Rep_RetailActual__c.field-meta.xml
<CustomField>
    <fullName>Rep_RetailActual__c</fullName>
    <label>Retail Actual</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Repository__c/fields/Rep_RMId__c.field-meta.xml
<CustomField>
    <fullName>Rep_RMId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>RM Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Repository__c/fields/Rep_RMName__c.field-meta.xml
<CustomField>
    <fullName>Rep_RMName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>RM Name</label>
    <length>220</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Repository__c/fields/Rep_Total__c.field-meta.xml
<CustomField>
    <fullName>Rep_Total__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Repository__c/fields/Rep_TSMName__c.field-meta.xml
<CustomField>
    <fullName>Rep_TSMName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>FRSM</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Business Centre</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Business Centre Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Centres</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/RespsitoryData_PSD2.cls
public class RespsitoryData_PSD2 {
    
    Public static Map<String, Repository__c> wholeMap= new Map<String, Repository__c>();
    Public static Map<String, Repository__c> wholeMap1= new Map<String, Repository__c>();
    Public static Map<String, Repository__c> wholeMapUpdatedList= new Map<String, Repository__c>();
    
    Public Static List<Map<String, Repository__c>> dataInsert(Map<String, Repository__c> map1,Map<String, Repository__c> map2,Opportunity eachopp,String combineId, String recId)
    {    
      Map<String, Repository__c> wholeMap= new Map<String, Repository__c>();
      Map<String, Repository__c> wholeMap1= new Map<String, Repository__c>();
      List<Map<String, Repository__c>>wholemapList = new List<Map<String, Repository__c>>();  
        wholeMap = map1;
        wholeMap1 = map2;
        Repository__c reposObj = new Repository__c();
            if(wholeMap.containsKey(combineId))
            {
                reposObj = wholeMap.get(combineId);
                if(eachOpp.RecordType.Name == 'FX Cash')    
                {
                    if(eachOpp.Opp_BranchNumber__c == System.Label.CBDirectDealingClient || 
                       eachOpp.Opp_BranchNumber__c == System.Label.YBDirectDealingClient)
                    {
                        if(eachOpp.isQ6Available__c == true)
                        {
                            Decimal tempVar = 0.00;
                            if(reposObj.Rep_FXDirectActual__c != null)
                                tempVar = tempVar + reposObj.Rep_FXDirectActual__c;
                            
                            system.debug('This is Check Query Before  PQR '+reposObj.Rep_FXDirectActual__c);
                            //reposObj.Rep_FXDirectActual__c = reposObj.Rep_FXDirectActual__c!=null?reposObj.Rep_FXDirectActual__c:0 + eachOpp.Amount;
                            System.debug('INN AMount>>>>'+eachOpp.Amount);
                            System.debug('INN FXDirect>>>>'+reposObj.Rep_FXDirectActual__c);
                            if(eachOpp.Amount != null)
                            reposObj.Rep_FXDirectActual__c = tempVar + eachOpp.Amount;
                            system.debug('INN FXDirect After '+reposObj.Rep_FXDirectActual__c);
                            
                        }
                        
                            
                    }
                    else if(eachOpp.Opp_BranchNumber__c == System.Label.CBCardedRateSheet || eachOpp.Opp_BranchNumber__c == System.Label.YBCardedRateSheet ||
                            eachOpp.Opp_BranchNumber__c == System.Label.CBIndirect || eachOpp.Opp_BranchNumber__c == System.Label.YBIndirect ||
                            eachOpp.Opp_BranchNumber__c == System.Label.CBSortingCode || eachOpp.Opp_BranchNumber__c == System.Label.YBSortingCode ||
                            eachOpp.Opp_BranchNumber__c == System.Label.CBGeneric || eachOpp.Opp_BranchNumber__c == System.Label.YBGeneric)
                    {
                        if(eachOpp.isQ6Available__c == true)
                        {
                            
                            //fxIndirectActuals = fxIndirectActuals + ags.get('amount');
                            //indirectSum = indirectSum + (Decimal)eachOpp.get('amount');
                            //fxInDirectActualMap.put((String)combineId, indirectSum);
                            Decimal tempVar = 0.00;
                            if(reposObj.Rep_FXIndirectActual__c != null)
                                tempVar = tempVar + reposObj.Rep_FXIndirectActual__c;
                            system.debug('This is Check Query Before  PQR '+reposObj.Rep_FXIndirectActual__c);
                            //reposObj.Rep_FXDirectActual__c = reposObj.Rep_FXDirectActual__c!=null?reposObj.Rep_FXDirectActual__c:0 + eachOpp.Amount;
                            System.debug('INN AMount>>>>'+eachOpp.Amount);
                            System.debug('INN FXIndirect>>>>'+reposObj.Rep_FXDirectActual__c);
                            if(eachOpp.Amount != null)
                            reposObj.Rep_FXIndirectActual__c = tempVar + eachOpp.Amount;
                            system.debug('INN FXIndirect '+reposObj.Rep_FXIndirectActual__c);
                            //reposObj.Rep_FXIndirectActual__c = reposObj.Rep_FXIndirectActual__c!=null?reposObj.Rep_FXIndirectActual__c:0 + eachOpp.Amount;
                        }
                        else
                        {
                            Decimal tempVar = 0.00;
                            if(reposObj.Rep_RetailActual__c != null)
                                tempVar = tempVar + reposObj.Rep_RetailActual__c;
                            system.debug('This is Check Query Before  PQR '+reposObj.Rep_RetailActual__c);
                            //reposObj.Rep_FXDirectActual__c = reposObj.Rep_FXDirectActual__c!=null?reposObj.Rep_FXDirectActual__c:0 + eachOpp.Amount;
                            System.debug('INN AMount>>>>'+eachOpp.Amount);
                            System.debug('INN FXIndirect>>>>'+reposObj.Rep_RetailActual__c);
                            if(eachOpp.Amount != null)
                            reposObj.Rep_RetailActual__c = tempVar + eachOpp.Amount;
                        }
                        
                    }
                    else if(eachOpp.Opp_BranchNumber__c == null)
                    {
                        //indirectSum = indirectSum + (Decimal)ags.get('amount');
                        // fxInDirectActualMap.put((String)combineId, indirectSum);
                        Decimal tempVar = 0.00;
                            if(reposObj.Rep_FXIndirectActual__c != null)
                                tempVar = tempVar + reposObj.Rep_FXIndirectActual__c;
                            system.debug('This is Check Query Before  PQR '+reposObj.Rep_FXIndirectActual__c);
                            //reposObj.Rep_FXDirectActual__c = reposObj.Rep_FXDirectActual__c!=null?reposObj.Rep_FXDirectActual__c:0 + eachOpp.Amount;
                            System.debug('INN AMount>>>>'+eachOpp.Amount);
                            System.debug('INN FXIndirect>>>>'+reposObj.Rep_FXIndirectActual__c);
                            if(eachOpp.Amount != null)
                            reposObj.Rep_FXIndirectActual__c = tempVar + eachOpp.Amount;
                            system.debug('INN This is Check Query After  PQR '+reposObj.Rep_FXIndirectActual__c); 
                        //reposObj.Rep_FXIndirectActual__c = reposObj.Rep_FXIndirectActual__c!=null?reposObj.Rep_FXIndirectActual__c:0 + eachOpp.Amount;
                    }
                }
                else if(eachOpp.RecordType.Name == 'Commodity') 
                {
                    //commSum = commSum + (Decimal)ags.get('amount');
                    //commActualMap.put((String)combineId, commSum);
                    Decimal tempVar = 0.00;
                            if(reposObj.Rep_CommodityActual__c != null)
                                tempVar = tempVar + reposObj.Rep_CommodityActual__c;
                            system.debug('This is Check Query Before  PQR '+reposObj.Rep_CommodityActual__c);
                            //reposObj.Rep_FXDirectActual__c = reposObj.Rep_FXDirectActual__c!=null?reposObj.Rep_FXDirectActual__c:0 + eachOpp.Amount;
                            System.debug('INN AMount>>>>'+eachOpp.Amount);
                            System.debug('INN FXCommodity>>>>'+reposObj.Rep_CommodityActual__c);
                            if(eachOpp.Amount != null)
                            reposObj.Rep_CommodityActual__c = tempVar + eachOpp.Amount;
                    
                            system.debug('INN This is Check Query After  PQR '+reposObj.Rep_CommodityActual__c);
                    //reposObj.Rep_CommodityActual__c = reposObj.Rep_CommodityActual__c!=null?reposObj.Rep_CommodityActual__c:0 + eachOpp.Amount;
                }
                
                else if(eachOpp.RecordType.Name == 'IRRM')  
                {
                    //irrmSum = irrmSum + (Decimal)ags.get('amount');
                    //irrmActualMap.put((String)combineId, irrmSum);
                    Decimal tempVar = 0.00;
                            if(reposObj.Rep_IRRMActual__c != null)
                                tempVar = tempVar + reposObj.Rep_IRRMActual__c;
                            system.debug('This is Check Query Before  PQR '+reposObj.Rep_IRRMActual__c);
                            //reposObj.Rep_FXDirectActual__c = reposObj.Rep_FXDirectActual__c!=null?reposObj.Rep_FXDirectActual__c:0 + eachOpp.Amount;
                            System.debug('INN AMount>>>>'+eachOpp.Amount);
                            System.debug('INN IRRM>>>>'+reposObj.Rep_IRRMActual__c);
                            if(eachOpp.Amount != null)
                            reposObj.Rep_IRRMActual__c = tempVar + eachOpp.Amount;
                            system.debug('INN This is Check Query After  PQR '+reposObj.Rep_IRRMActual__c);
                   // reposObj.Rep_IRRMActual__c = reposObj.Rep_IRRMActual__c!=null?reposObj.Rep_IRRMActual__c:0 + eachOpp.Amount;
                }
                else if(eachOpp.RecordType.Name == 'Business Loan')  
                {
                    //irrmSum = irrmSum + (Decimal)ags.get('amount');
                    //irrmActualMap.put((String)combineId, irrmSum);
                    Decimal tempVar = 0.00;
                            if(reposObj.Rep_BusinessActual__c != null)
                                tempVar = tempVar + reposObj.Rep_BusinessActual__c;
                            system.debug('This is Check Query Before  PQR '+reposObj.Rep_BusinessActual__c);
                            //reposObj.Rep_FXDirectActual__c = reposObj.Rep_FXDirectActual__c!=null?reposObj.Rep_FXDirectActual__c:0 + eachOpp.Amount;
                            System.debug('INN AMount>>>>'+eachOpp.Amount);
                            System.debug('INN Rep_BusinessActual__c>>>>'+reposObj.Rep_BusinessActual__c);
                            if(eachOpp.Amount != null)
                            reposObj.Rep_BusinessActual__c = tempVar + eachOpp.Amount;
                            system.debug('INN This is Check Query After  PQR '+reposObj.Rep_BusinessActual__c);
                   // reposObj.Rep_BusinessActual__c = reposObj.Rep_BusinessActual__c!=null?reposObj.Rep_BusinessActual__c:0 + eachOpp.Amount;
                }
                System.debug('Rep_Total__c>>>>>&& '+reposObj.Rep_Total__c);
                System.debug('Amount>>>>>&& '+eachOpp.Amount);
                if(reposObj.Rep_Total__c != null)
                	reposObj.Rep_Total__c = reposObj.Rep_Total__c + eachOpp.Amount;
                
                System.debug('This is a check RESPOBJ'+reposObj);
                System.debug('This is a check Rep . reposObj'+reposObj.Rep_FXDirectActual__c);
                System.debug('INN WHOLE Map'+ wholeMap.get(combineId));
                //wholeMap.put(combineId, reposObj);
                wholeMapUpdatedList.put(combineId, reposObj);
                System.debug('INN Whole Map Ltr'+ wholeMap.get(combineId));
                
            wholemapList.add(wholeMapUpdatedList);
                System.debug('WHOLEMAP>>>>>>>>>>>>>>>>'+wholeMap);
            }   
        ////////////////////////////////////////
            else if(wholeMap1.containsKey(combineId))
            {
                System.debug('HERE IN ELSE IF>>>>>>>>>>>>>>>');
                reposObj = wholeMap1.get(combineId);
                if(eachOpp.RecordType.Name == 'FX Cash')    
                {
                    if(eachOpp.Opp_BranchNumber__c == System.Label.CBDirectDealingClient || 
                       eachOpp.Opp_BranchNumber__c == System.Label.YBDirectDealingClient)
                    {
                        if(eachOpp.isQ6Available__c == true)
                        {
                            //fxDirectActuals = fxDirectActuals + ags.get('amount');
                            //directSum = directSum + (Decimal)eachOpp.Amount;
                            
                             //   fxDirectActualMap.put(combineId, (Decimal)eachOpp.Amount + (Decimal)fxDirectActualMap.get(combineId));
                            Decimal tempVar = 0.00;
                            if(reposObj.Rep_FXDirectActual__c != null)
                                tempVar = tempVar + reposObj.Rep_FXDirectActual__c;
                            system.debug('This is Check Query Before  PQR '+reposObj.Rep_FXDirectActual__c);
                            //reposObj.Rep_FXDirectActual__c = reposObj.Rep_FXDirectActual__c!=null?reposObj.Rep_FXDirectActual__c:0 + eachOpp.Amount;
                            System.debug('INN AMount>>>>'+eachOpp.Amount);
                            System.debug('INN FXIndirect>>>>'+reposObj.Rep_FXDirectActual__c);
                            if(eachOpp.Amount != null)
                            reposObj.Rep_FXDirectActual__c = tempVar + eachOpp.Amount;
                            system.debug(' INN This is Check Query After  PQR '+reposObj.Rep_FXDirectActual__c);
                            //reposObj.Rep_FXDirectActual__c = reposObj.Rep_FXDirectActual__c!=null?reposObj.Rep_FXDirectActual__c:0 + eachOpp.Amount;
                            
                        }
                        
                    }
                    else if(eachOpp.Opp_BranchNumber__c == System.Label.CBCardedRateSheet || eachOpp.Opp_BranchNumber__c == System.Label.YBCardedRateSheet ||
                            eachOpp.Opp_BranchNumber__c == System.Label.CBIndirect || eachOpp.Opp_BranchNumber__c == System.Label.YBIndirect ||
                            eachOpp.Opp_BranchNumber__c == System.Label.CBSortingCode || eachOpp.Opp_BranchNumber__c == System.Label.YBSortingCode ||
                            eachOpp.Opp_BranchNumber__c == System.Label.CBGeneric || eachOpp.Opp_BranchNumber__c == System.Label.YBGeneric)
                    {
                        if(eachOpp.isQ6Available__c == true)
                        {
                            
                            Decimal tempVar = 0.00;
                            if(reposObj.Rep_FXIndirectActual__c != null)
                                tempVar = tempVar + reposObj.Rep_FXIndirectActual__c;
                            system.debug('This is Check Query Before  PQR '+reposObj.Rep_FXIndirectActual__c);
                            //reposObj.Rep_FXDirectActual__c = reposObj.Rep_FXDirectActual__c!=null?reposObj.Rep_FXDirectActual__c:0 + eachOpp.Amount;
                            System.debug('INN AMount>>>>'+eachOpp.Amount);
                            System.debug('INN FXIndirect>>>>'+reposObj.Rep_FXIndirectActual__c);
                            if(eachOpp.Amount != null)
                            reposObj.Rep_FXIndirectActual__c = tempVar + eachOpp.Amount;
                            system.debug('INN This is Check Query After  PQR '+reposObj.Rep_FXIndirectActual__c);
                            //reposObj.Rep_FXIndirectActual__c = reposObj.Rep_FXIndirectActual__c!=null?reposObj.Rep_FXIndirectActual__c:0 + eachOpp.Amount;
                        }
                        else
                        {
                            Decimal tempVar = 0.00;
                            if(reposObj.Rep_RetailActual__c != null)
                                tempVar = tempVar + reposObj.Rep_RetailActual__c;
                            system.debug('This is Check Query Before  PQR '+reposObj.Rep_RetailActual__c);
                            //reposObj.Rep_FXDirectActual__c = reposObj.Rep_FXDirectActual__c!=null?reposObj.Rep_FXDirectActual__c:0 + eachOpp.Amount;
                            System.debug('INN AMount>>>>'+eachOpp.Amount);
                            System.debug('INN FXIndirect>>>>'+reposObj.Rep_RetailActual__c);
                            if(eachOpp.Amount != null)
                            reposObj.Rep_RetailActual__c = tempVar + eachOpp.Amount;
                            system.debug('INN This is Check Query After  PQR '+reposObj.Rep_RetailActual__c);
                        }
                        
                    }
                    else if(eachOpp.Opp_BranchNumber__c == null)
                    {
                        //indirectSum = indirectSum + (Decimal)ags.get('amount');
                        // fxInDirectActualMap.put((String)combineId, indirectSum);
                        Decimal tempVar = 0.00;
                            if(reposObj.Rep_FXIndirectActual__c != null)
                                tempVar = tempVar + reposObj.Rep_FXIndirectActual__c;
                            system.debug('This is Check Query Before  PQR '+reposObj.Rep_FXIndirectActual__c);
                            //reposObj.Rep_FXDirectActual__c = reposObj.Rep_FXDirectActual__c!=null?reposObj.Rep_FXDirectActual__c:0 + eachOpp.Amount;
                            System.debug('INN AMount>>>>'+eachOpp.Amount);
                            System.debug('INN FXIndirect>>>>'+reposObj.Rep_FXIndirectActual__c);
                            if(eachOpp.Amount != null)
                            reposObj.Rep_FXIndirectActual__c = tempVar + eachOpp.Amount;
                            system.debug('INN This is Check Query After  PQR '+reposObj.Rep_FXIndirectActual__c);
                        //reposObj.Rep_FXIndirectActual__c = reposObj.Rep_FXIndirectActual__c!=null?reposObj.Rep_FXIndirectActual__c:0 + eachOpp.Amount;
                    }
                }
                else if(eachOpp.RecordType.Name == 'Commodity') 
                {
                    //commSum = commSum + (Decimal)ags.get('amount');
                    //commActualMap.put((String)combineId, commSum);
                    Decimal tempVar = 0.00;
                            if(reposObj.Rep_CommodityActual__c != null)
                                tempVar = tempVar + reposObj.Rep_CommodityActual__c;
                            system.debug('This is Check Query Before  PQR '+reposObj.Rep_CommodityActual__c);
                            //reposObj.Rep_FXDirectActual__c = reposObj.Rep_FXDirectActual__c!=null?reposObj.Rep_FXDirectActual__c:0 + eachOpp.Amount;
                            System.debug('INN AMount>>>>'+eachOpp.Amount);
                            System.debug('INN FXIndirect>>>>'+reposObj.Rep_CommodityActual__c);
                            if(eachOpp.Amount != null)
                            reposObj.Rep_CommodityActual__c = tempVar + eachOpp.Amount;
                            system.debug('INN This is Check Query After  PQR '+reposObj.Rep_CommodityActual__c);
                    //reposObj.Rep_CommodityActual__c = reposObj.Rep_CommodityActual__c!=null?reposObj.Rep_CommodityActual__c:0 + eachOpp.Amount;
                }
                
                else if(eachOpp.RecordType.Name == 'IRRM')  
                {
                    //irrmSum = irrmSum + (Decimal)ags.get('amount');
                    //irrmActualMap.put((String)combineId, irrmSum);
                    Decimal tempVar = 0.00;
                            if(reposObj.Rep_IRRMActual__c != null)
                                tempVar = tempVar + reposObj.Rep_IRRMActual__c;
                            system.debug('This is Check Query Before  PQR '+reposObj.Rep_IRRMActual__c);
                            //reposObj.Rep_FXDirectActual__c = reposObj.Rep_FXDirectActual__c!=null?reposObj.Rep_FXDirectActual__c:0 + eachOpp.Amount;
                            System.debug('INN AMount>>>>'+eachOpp.Amount);
                            System.debug('INN FXIndirect>>>>'+reposObj.Rep_IRRMActual__c);
                            if(eachOpp.Amount != null)
                            reposObj.Rep_IRRMActual__c = tempVar + eachOpp.Amount;
                            system.debug('Inn This is Check Query After  PQR '+reposObj.Rep_IRRMActual__c);
                    //reposObj.Rep_IRRMActual__c = reposObj.Rep_IRRMActual__c!=null?reposObj.Rep_IRRMActual__c:0 + eachOpp.Amount;
                }
                else if(eachOpp.RecordType.Name == 'Business Loan')  
                {
                    //irrmSum = irrmSum + (Decimal)ags.get('amount');
                    //irrmActualMap.put((String)combineId, irrmSum);
                    Decimal tempVar = 0.00;
                            if(reposObj.Rep_BusinessActual__c != null)
                                tempVar = tempVar + reposObj.Rep_BusinessActual__c;
                            system.debug('This is Check Query Before  PQR '+reposObj.Rep_BusinessActual__c);
                            //reposObj.Rep_FXDirectActual__c = reposObj.Rep_FXDirectActual__c!=null?reposObj.Rep_FXDirectActual__c:0 + eachOpp.Amount;
                            System.debug('INN AMount>>>>'+eachOpp.Amount);
                            System.debug('INN FXIndirect>>>>'+reposObj.Rep_BusinessActual__c);
                            if(eachOpp.Amount != null)
                            reposObj.Rep_BusinessActual__c = tempVar + eachOpp.Amount;
                            system.debug('Inn This is Check Query After  PQR '+reposObj.Rep_BusinessActual__c);
                    //reposObj.Rep_BusinessActual__c = reposObj.Rep_BusinessActual__c!=null?reposObj.Rep_BusinessActual__c:0 + eachOpp.Amount;
                }
                
                if(reposObj.Rep_Total__c != null)
                	reposObj.Rep_Total__c = reposObj.Rep_Total__c + eachOpp.Amount;
                
                System.debug('INN WholeMap 1'+wholeMap1.get(combineId));
                wholeMap1.put(combineId, reposObj);
                System.debug('INN WholeMap 1 Aftr'+wholeMap1.get(combineId));
                wholemapList.add(wholeMap1);
                System.debug('WHOLEMAP>>>>>>>>>>>>>>>>'+wholeMap1);
            
            }
             /////////////////////// 
            else
            {
                System.debug('HERE IN ELSE>>>>>>>>>>>>>>>');
                //reposObj.Rep_CombineId__c = combineId;
                reposObj.Rep_Month__c = eachOpp.CloseDate.month();
                reposObj.Rep_BusinessCentreId__c = (String)eachOpp.Account.RM_Name__r.Con_Team__c;
                reposObj.Rep_RMId__c = (String)eachOpp.Account.RM_Name__c;
                reposObj.Rep_BusinessCentre__c = (String)eachOpp.Account.RM_Name__r.Con_Team__r.Name;
                reposObj.Rep_RMName__c = (String)eachOpp.Account.RM_Name__r.Name;
                reposObj.Rep_MonthText__c = String.valueOf(eachOpp.CloseDate.month());
                reposObj.Rep_TSMName__c = eachOpp.Owner.Name;
                reposObj.Rep_RegionName__c = eachOpp.Account.RM_Name__r.Con_Centre__c;
                reposObj.Rep_CustomerName__c = eachOpp.Account.Name;
                reposObj.Rep_FX_Manager__c = eachOpp.Account.FX_Manager__r.Name;
                reposObj.Rep_Total__c = 0.00;
                
                if(eachOpp.Account.RM_Name__r.Con_Region__c != null)
                    reposObj.Rep_DivisionName__c = eachOpp.Account.RM_Name__r.Con_Region__c;
                else if(eachOpp.Account.RM_Name__r.Con_Region__c == null  && eachOpp.Opp_CorpCode__c == System.Label.CB_Corp_Code)
                    reposObj.Rep_DivisionName__c = System.Label.Retail_Division;
                else if(eachOpp.Opp_CorpCode__c == System.Label.YB_Corp_Code)
                    reposObj.Rep_DivisionName__c = System.Label.YB_Retail_Division;
                
                if(eachOpp.Account.RM_Name__r.Con_Division__c != null)
                    reposObj.Rep_GroupName__c =  eachOpp.Account.RM_Name__r.Con_Division__c;
                else if(eachOpp.Account.RM_Name__r.Con_Division__c == null  && eachOpp.Opp_CorpCode__c == System.Label.CB_Corp_Code)
                    reposObj.Rep_GroupName__c = System.Label.Retail_Group;
                else if(eachOpp.Opp_CorpCode__c == System.Label.YB_Corp_Code)
                    reposObj.Rep_GroupName__c = System.Label.YB_Retail_Group;
                
                if(eachOpp.Account.RM_Name__r.Con_Group__c != null)
                    reposObj.Rep_BankName__c =  eachOpp.Account.RM_Name__r.Con_Group__c;
                else
                    reposObj.Rep_BankName__c = System.Label.Retail_Bank;
                
                reposObj.Rep_CombineId__c = combineId;
                reposObj.RecordTypeId = recId;
                reposObj.Rep_Q6Code__c = eachOpp.Account.RM_Name__r.Officer_Code__c;
                
                if(eachOpp.RecordType.Name == 'FX Cash')    
                {
                    if(eachOpp.Opp_BranchNumber__c == System.Label.CBDirectDealingClient || 
                       eachOpp.Opp_BranchNumber__c == System.Label.YBDirectDealingClient)
                    {
                        if(eachOpp.isQ6Available__c == true)
                        {
                            //fxDirectActuals = fxDirectActuals + ags.get('amount');
                            //directSum = directSum + (Decimal)eachOpp.Amount;
                            
                             //   fxDirectActualMap.put(combineId, (Decimal)eachOpp.Amount + (Decimal)fxDirectActualMap.get(combineId));
                             //   
                         
                            reposObj.Rep_FXDirectActual__c = eachOpp.Amount;
                            
                        }
                        
                    }
                    else if(eachOpp.Opp_BranchNumber__c == System.Label.CBCardedRateSheet || eachOpp.Opp_BranchNumber__c == System.Label.YBCardedRateSheet ||
                            eachOpp.Opp_BranchNumber__c == System.Label.CBIndirect || eachOpp.Opp_BranchNumber__c == System.Label.YBIndirect ||
                            eachOpp.Opp_BranchNumber__c == System.Label.CBSortingCode || eachOpp.Opp_BranchNumber__c == System.Label.YBSortingCode ||
                            eachOpp.Opp_BranchNumber__c == System.Label.CBGeneric || eachOpp.Opp_BranchNumber__c == System.Label.YBGeneric)
                    {
                        if(eachOpp.isQ6Available__c == true)
                        {
                            
                            //fxIndirectActuals = fxIndirectActuals + ags.get('amount');
                            //indirectSum = indirectSum + (Decimal)eachOpp.get('amount');
                            //fxInDirectActualMap.put((String)combineId, indirectSum);
                            reposObj.Rep_FXIndirectActual__c = eachOpp.Amount;
                            
                        }
                        else
                        {
                            System.debug('<<<<<<<<<<,HERE I AM >>>>>>>>>>>>');
                            reposObj.Rep_RetailActual__c = eachOpp.Amount;
                        }
                        
                    }
                    else if(eachOpp.Opp_BranchNumber__c == null)
                    {
                        //indirectSum = indirectSum + (Decimal)ags.get('amount');
                        // fxInDirectActualMap.put((String)combineId, indirectSum);
                        reposObj.Rep_FXIndirectActual__c = eachOpp.Amount;
                        
                    }
                }
                else if(eachOpp.RecordType.Name == 'Commodity') 
                {
                    //commSum = commSum + (Decimal)ags.get('amount');
                    //commActualMap.put((String)combineId, commSum);
                    reposObj.Rep_CommodityActual__c = eachOpp.Amount;
                    
                }
                
                else if(eachOpp.RecordType.Name == 'IRRM')  
                {
                    //irrmSum = irrmSum + (Decimal)ags.get('amount');
                    //irrmActualMap.put((String)combineId, irrmSum);
                    reposObj.Rep_IRRMActual__c = eachOpp.Amount;
                    
                }
                else if(eachOpp.RecordType.Name == 'Business Loan')  
                {
                    //irrmSum = irrmSum + (Decimal)ags.get('amount');
                    //irrmActualMap.put((String)combineId, irrmSum);
                    reposObj.Rep_BusinessActual__c = eachOpp.Amount;
                    
                }
                
                if(reposObj.Rep_Total__c != null)
                	reposObj.Rep_Total__c = reposObj.Rep_Total__c + eachOpp.Amount;
                
                wholeMap1.put(combineId, reposObj);
                wholemapList.add(wholeMap1);
                System.debug('wholeMap1'+wholeMap1);
            }
          
            // Condition checking ending Here
            //reposList.add(wholeMap);
        
        System.debug('WHOLEMAPLIST'+wholemapList);

        return wholemapList;
    }
}