force-app/main/default/objects/Account/fields/Officer_Code__c.field-meta.xml
<CustomField>
    <fullName>Officer_Code__c</fullName>
    <formula>RM_Name__r.Officer_Code__c</formula>
    <label>Officer Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/RM_Name__c.field-meta.xml
<CustomField>
    <fullName>RM_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RM Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND 2</booleanFilter>
        <errorMessage>Please select an active Banker of a respective branch.</errorMessage>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Banker</value>
        </filterItems>
        <filterItems>
            <field>Contact.Contact_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Banker)</relationshipLabel>
    <relationshipName>AccountBanker</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CalypsoData__c/CalypsoData__c.object-meta.xml
<CustomObject>
    <label>Calypso Data</label>
    <nameField>
        <displayFormat>CD-{00000}</displayFormat>
        <label>CData No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Calypso Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CalypsoData__c/fields/CD_BranchNumber__c.field-meta.xml
<CustomField>
    <fullName>CD_BranchNumber__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Branch Number</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CalypsoData__c/fields/CD_Customer__c.field-meta.xml
<CustomField>
    <fullName>CD_Customer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Calypso Data</relationshipLabel>
    <relationshipName>CalypsoData</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CalypsoData__c/fields/CD_ETBranchNumber__c.field-meta.xml
<CustomField>
    <fullName>CD_ETBranchNumber__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ET Branch Number</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CalypsoData__c/fields/CD_TradeID__c.field-meta.xml
<CustomField>
    <fullName>CD_TradeID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Trade ID</label>
    <length>35</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Con_Team__c.field-meta.xml
<CustomField>
    <fullName>Con_Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Business Centre</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Bankers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Officer_Code__c.field-meta.xml
<CustomField>
    <fullName>Officer_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Officer Code</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opp_BaseEquivalent__c.field-meta.xml
<CustomField>
    <fullName>Opp_BaseEquivalent__c</fullName>
    <label>Base Equivalent</label>
    <precision>18</precision>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opp_BranchNumber__c.field-meta.xml
<CustomField>
    <fullName>Opp_BranchNumber__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Branch Number</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opp_ETBranchNumber__c.field-meta.xml
<CustomField>
    <fullName>Opp_ETBranchNumber__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ET Branch Number</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opp_ETRef__c.field-meta.xml
<CustomField>
    <fullName>Opp_ETRef__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ET Ref</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opp_TradeID__c.field-meta.xml
<CustomField>
    <fullName>Opp_TradeID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Trade ID</label>
    <length>35</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Q6Values__mdt/Q6Values__mdt.object-meta.xml
<CustomObject>
    <label>Q6 Value</label>
    <pluralLabel>Q6 Values</pluralLabel>
</CustomObject>

force-app/main/default/objects/Q6Values__mdt/fields/Q6Value__c.field-meta.xml
<CustomField>
    <fullName>Q6Value__c</fullName>
    <label>Q6 Value</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Q6Values__mdt/fields/TradeKeyword__c.field-meta.xml
<CustomField>
    <fullName>TradeKeyword__c</fullName>
    <label>Trade Keyword</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Business Centre</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Business Centre Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Centres</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/DealReportSummaryFRSM.cls
public class DealReportSummaryFRSM {
    Integer fyStartMonth;
    Date fyStartDate;
    Date fyEndDate;
    Date pfyStartDate;
    Date pfyEndDate;
    //String fyStartDateString;
    //String fyEndDateString;
    
    
    Public List<WrapperClass> wrappedDataList{get; set;}
    
    public Map<String, String> branchNumwithQ6Map = new Map<String, String>();
    public List<Q6Values__mdt> Q6ValueList = new List<Q6Values__mdt>();
    
    
    Public Map<String, String> oppMap= new Map<String, String>();
    Public Map<String, String> accMap= new Map<String, String>();
    Public Map<String, String> recMap= new Map<String, String>();
    Public Map<String, String> ownMap= new Map<String, String>();
    Public Map<String, String> etbMap= new Map<String, String>();
    Public Map<String, String> baseMap= new Map<String, String>();
    Public Map<String, String> bankerMap= new Map<String, String>();
    Public Map<String, String> teamMap= new Map<String, String>();
    Public Map<String, String> q6Map= new Map<String, String>();
    Public Map<String, String> brnoMap= new Map<String, String>();
    Public Map<String, String> etrMap= new Map<String, String>();
    Public Map<String, String> datMap= new Map<String, String>();
    Public Map<String, String> cidMap= new Map<String, String>();
    Public Map<String, String> tidMap= new Map<String, String>();
    
    Public Set<String> tradeSet= new Set<String>();
    
    //List<T> fullList = new List<T>();
    
    public DealReportSummaryFRSM(){
        
        wrappedDataList = new List<WrapperClass>();
        
        fyStartMonth = CYBGUtilClass.fiscalYearStartMonth();
        fyStartDate = CYBGUtilClass.findStartDateOfFY(System.Today(), fyStartMonth); 
        fyEndDate = CYBGUtilClass.findEndDateOfFY(System.Today(), fyStartMonth);
        fetchData();
    }
    
    Public void fetchData(){
        for(Q6Values__mdt q6 : [SELECT Q6Value__c, TradeKeyword__c FROM Q6Values__mdt]){
            branchNumwithQ6Map.put(q6.TradeKeyword__c, q6.Q6Value__c);        
        }

        for(Opportunity opptyList : [SELECT Account.Name,Amount,CloseDate, RecordType.Name, OwnerId, Owner.Name, Opp_ETBranchNumber__c, Opp_BaseEquivalent__c,
                                     Account.RM_Name__r.Officer_Code__c,
                                     Opp_BranchNumber__c, LastModifiedDate,Opp_ETRef__c, Opp_TradeID__c, Account.RM_Name__r.Name,
                                     Account.RM_Name__r.Con_Team__r.Name FROM Opportunity
                                     WHERE CloseDate >= :fyStartDate AND CloseDate <= :fyEndDate 
                                     ORDER BY CloseDate ASC])
        {
            system.debug('rm name-->'+ opptyList.Account.RM_Name__r.Name);
            accMap.put(opptyList.OwnerId, opptyList.Account.Name);
            recMap.put(opptyList.OwnerId, opptyList.RecordType.Name);
            ownMap.put(opptyList.OwnerId, opptyList.Owner.Name);
            baseMap.put(opptyList.OwnerId, String.valueOf(opptyList.Amount));
            bankerMap.put(opptyList.OwnerId, opptyList.Account.RM_Name__r.Name);
            teamMap.put(opptyList.OwnerId, opptyList.Account.RM_Name__r.Con_Team__r.Name);
            brnoMap.put(opptyList.OwnerId, opptyList.Opp_BranchNumber__c);
            etrMap.put(opptyList.OwnerId, opptyList.Opp_ETRef__c);
            datMap.put(opptyList.OwnerId, String.valueOf(opptyList.CloseDate));
            tidMap.put(opptyList.OwnerId, opptyList.Opp_TradeID__c);
            System.debug('Trade'+(opptyList.Opp_TradeID__c));
            if(opptyList.Opp_TradeID__c != null)
            {
                tradeSet.add(opptyList.Opp_TradeID__c);
            }
            if(opptyList.Account.RM_Name__r.Officer_Code__c != null)
            {
                q6Map.put(opptyList.OwnerId, opptyList.Account.RM_Name__r.Officer_Code__c);
            }
            
            
            
        }
        System.debug('Trade'+tradeSet);
       
        for(CalypsoData__c keys: [SELECT Name, CD_Customer__r.OwnerId, CD_TradeID__c, 
                                  CD_ETBranchNumber__c, CD_BranchNumber__c, CD_Customer__r.Officer_Code__c FROM CalypsoData__c WHERE CD_TradeID__c IN :tradeSet])
        {
            System.debug('Name'+keys.Name);
            if(recMap.get(keys.CD_Customer__r.OwnerId) == 'FX Cash' && keys.CD_TradeID__c == tidMap.get(keys.CD_Customer__r.OwnerId))
            {
            cidMap.put(keys.CD_Customer__r.OwnerId, keys.Name);
                etbMap.put(keys.CD_Customer__r.OwnerId, keys.CD_ETBranchNumber__c);
                
                if(keys.CD_Customer__r.Officer_Code__c != null)
                {
                    q6Map.put(keys.CD_Customer__r.OwnerId, keys.CD_Customer__r.Officer_Code__c);
                }
                else if(keys.CD_BranchNumber__c != null && branchNumwithQ6Map.get(keys.CD_BranchNumber__c) != null)
                {
                    
                    q6Map.put(keys.CD_Customer__r.OwnerId, branchNumwithQ6Map.get(keys.CD_BranchNumber__c));
                }
                else
                {
                    q6Map.put(keys.CD_Customer__r.OwnerId, null);
                }
            }
            /*
            */
        }
        
        for(String keys: ownMap.keySet())
        {
            System.debug('CID'+cidMap.get(keys));
            wrappedDataList.add(new WrapperClass(datMap.get(keys), ownMap.get(keys), accMap.get(keys), recMap.get(keys), etbMap.get(keys),
                                                cidMap.get(keys), baseMap.get(keys), bankerMap.get(keys), q6Map.get(keys), teamMap.get(keys)));
        }
    }
    public PageReference downloadReport() {
        PageReference nextpage = new PageReference('/apex/DealReportSummaryFRSMDld');
        return nextpage;
    }
    
    
    Public class WrapperClass{
        Public String tradeDate {get; set;}
        Public String customerName {get; set;}
        Public String product {get; set;}
        Public String etbranchNumber {get; set;}
        Public String cid {get; set;}
        Public String revenue {get; set;}
        Public String rm {get; set;}
        Public String q6 {get; set;}
        Public String team {get; set;}
        Public String OwnerNames {get; set;}
                
        Public WrapperClass(String tradeDate, String OwnerNames, String customerName, String product,String etbranchNumber, String cid,
                            String revenue,String rm,String q6,String team)
        {
            
            
            this.tradeDate = tradeDate; 
            this.customerName =  customerName;
            this.product =  product;
            this.etbranchNumber =  etbranchNumber;
            this.cid = cid;
            this.revenue =  revenue;
            this.rm =  rm;
            this.q6 =  q6;
            this.team = team;
            this.OwnerNames = OwnerNames;
        }
    }
}