force-app/main/default/objects/Account/fields/RecordType__c.field-meta.xml
<CustomField>
    <fullName>RecordType__c</fullName>
    <label>Record Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Target</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Internal.recordType-meta.xml
<RecordType>
    <fullName>Internal</fullName>
    <active>true</active>
    <label>Internal</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Internal.recordType-meta.xml
<RecordType>
    <fullName>Internal</fullName>
    <active>true</active>
    <description>Used for Treasury Solutions employees</description>
    <label>Internal</label>
</RecordType>

force-app/main/default/objects/PMTarget__c/PMTarget__c.object-meta.xml
<CustomObject>
    <label>PM Target</label>
    <nameField>
        <displayFormat>Target - {00000}</displayFormat>
        <label>PM Target No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PM Targets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PMTarget__c/fields/PMTar_PMContact__c.field-meta.xml
<CustomField>
    <fullName>PMTar_PMContact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product Manager (Contact)</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Product Manager Contact type should be internal and Contact status should be active</errorMessage>
        <filterItems>
            <field>Contact.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Internal</value>
        </filterItems>
        <filterItems>
            <field>Contact.Contact_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>PM Targets</relationshipLabel>
    <relationshipName>PMTargets</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PMTarget__c/fields/PMTar_PMUser__c.field-meta.xml
<CustomField>
    <fullName>PMTar_PMUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Manager (User)</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PMTargets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PMTarget__c/fields/PMTar_Status__c.field-meta.xml
<CustomField>
    <fullName>PMTar_Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Ended</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
                <isActive>false</isActive>
                <label>Closed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PMTarget__c/fields/PMTar_TerminationDate__c.field-meta.xml
<CustomField>
    <fullName>PMTar_TerminationDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Termination Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PMTarget__c/fields/PMTar_TotalWorkingDays__c.field-meta.xml
<CustomField>
    <fullName>PMTar_TotalWorkingDays__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total # Working Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PMTarget__c/fields/PMTar_WorkingDays__c.field-meta.xml
<CustomField>
    <fullName>PMTar_WorkingDays__c</fullName>
    <label># Working Days To Date</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Business Centre</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Business Centre Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Centres</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>England</fullName>
            </value>
            <value>
                <fullName>Scotland</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PMTargetWorkingDays_Test.cls
@isTest
public class PMTargetWorkingDays_Test 
{
    
    static testMethod void createTargetData() 
    {
        Id RecordTypeIdContact = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Contact').getRecordTypeId();
        Id RecordTypeIdCustomer = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId();
        Id RecordTypeIdCustomerInternal = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Internal').getRecordTypeId();
        Id RecordTypeIdContactInternal = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Internal').getRecordTypeId();
        
        Integer countActive = 0;
        Integer countInactive = 0;
        Integer startYear = Date.Today().Year();
        Integer endYear = Date.Today().Year()+1;
        Date startDate = Date.newInstance(startYear,10,01);
        Date endDate = Date.newInstance(endYear,09,30);
        
        List<PMTarget__c> PMTarList = new List<PMTarget__c>();
        List<Team__c> teamList = new List<Team__c>();
        List<Contact> conList = new List<Contact>();
        List<PMTarget__c> testQueryList = new List<PMTarget__c>();
        
        User testUser1 = TestData.createUser('CYB');
        testUser1.Location__c = 'England';
        testUser1.username = 'testUser1@usernametestorg.com';
        insert testUser1;
        User testUser2 = TestData.createUser('CYB');
        testUser2.Location__c = 'Scotland';
        testUser1.username = 'testUser2@usernametestorg.com';
        insert testUser2;
        
        Account accCus = TestData.createCustomerAccount('Test Data Demo', RecordTypeIdCustomer);
        accCus.BillingCity = 'Test City';
        accCus.BillingStreet = 'Test Street';
        accCus.BillingPostalCode = '12345';
        accCus.RecordType__c = 'Customer';
        insert accCus;
        Account accint = TestData.createCalypsoAccountInternal('Clydesdale Bank', RecordTypeIdCustomerInternal);
        accint.RecordType__c = 'Internal';
        insert accint;
        for(Integer i=0; i<20; i++)
        {
            Contact con = TestData.createContactContact('Test Contact'+i, RecordTypeIdContact, accCus.Id);
            conList.add(con);
        }
        insert conList;
        
        Contact conint = TestData.createContactInternal('2345', RecordTypeIdContactInternal, accint.Id);
        insert conint;
        
        User testUser = TestData.createUser('CYB');
        testUser.Username = 'testUsersample@usernametestorg.com';
        insert testUser;
        
        for(Integer i=0;i<20;i++)
        {
            countActive = countActive +1;
            PMTarget__c testPMTar  = TestData.createPMMTarget();
            testPMTar.PMTar_PMContact__c = conint.Id;
            testPMTar.OwnerId = testUser.id;
            testPMTar.PMTar_TotalWorkingDays__c = 0;
            testPMTar.PMTar_WorkingDays__c = 0;
            if(math.mod(i,2)==0){
                testPMTar.PMTar_PMUser__c = testUser1.Id;
                testPMTar.PMTar_Status__c = 'Active';
            }
            else
            {
                testPMTar.PMTar_Status__c = 'Terminated';
                testPMTar.PMTar_PMUser__c = testUser2.Id;
                testPMTar.PMTar_TerminationDate__c=System.today();
            }
            PMTarList.add(testPMTar);
        }
        insert PMTarList;
        
        Test.startTest();
        
        PMTargetWorkingDays testObj = new PMTargetWorkingDays();
        DataBase.executeBatch(testObj); 
        
        Test.stopTest();
        List<PMTarget__c> list1 = [Select Id,Name,PMTar_TotalWorkingDays__c from PMTarget__c where PMTar_TotalWorkingDays__c>0];
        system.debug('----list1---'+list1);
        System.assertEquals(countActive, list1.size());
    }

}