force-app/main/default/objects/TSMTarget__c/TSMTarget__c.object-meta.xml
<CustomObject>
    <description>To hold the target and actual for a TSM under specific Team</description>
    <label>FRSM Target</label>
    <nameField>
        <displayFormat>Target - {00000}</displayFormat>
        <label>FRSM Target No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FRSM Targets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_FiscalYear__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_FiscalYear__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Fiscal Year</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_FYEndDate__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_FYEndDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>FY End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_FYStartDate__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_FYStartDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>FY Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_Status__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Ended</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
                <isActive>false</isActive>
                <label>Closed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_Team__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_Team__c</fullName>
    <label>Business Centre</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Team status is not active.</errorMessage>
        <filterItems>
            <field>Team__c.Team_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Team__c</referenceTo>
    <relationshipName>TSMTargets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_TSM__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_TSM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Risk Solutions Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>TSMTargets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_TSMManager__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_TSMManager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FRSM&#39;s Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>TSMManager</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TSMTargetTriggerHandler.cls
/*
@Author        : Sushant Shekhar
@Name          : TSMTargetTriggerHandler
@Created Date  : 5th March 2018
@Description   : This is a Handler for TSMTargetTrigger 
@version       : 1.0
*/
public class TSMTargetTriggerHandler 
{
 /**
* @description       Method to process and Validate the TSM Target before Insert 
* @name              onAfterInsert
* @param             List<TSMTarget__c>
* @return            void
* @throws            NA
*/ 
    public static void onBeforeInsert(List<TSMTarget__c> tsmTargetsList){
        Integer fyStartMonth = CYBGUtilClass.fiscalYearStartMonth(); 
        Set<ID> tsmIDsSet = new Set<ID>();
        For(TSMTarget__c eachTSMTarget : tsmTargetsList){
            tsmIDsSet.add(eachTSMTarget.TSMTar_TSM__c);
        }    
        Map<ID, User> tsmUserMap = new Map<ID, User>([Select id, Name, ManagerId From User Where ID IN :tsmIDsSet]);
        Map<String,TSMTarget__c> allActivetsmTargetMap = activeTSMTargets();
        For(TSMTarget__c eachTSMTarget : tsmTargetsList){
            eachTSMTarget.TSMTar_FiscalYear__c = CYBGUtilClass.findCurrentFY(System.Today(), fyStartMonth);
            eachTSMTarget.TSMTar_FYStartDate__c = CYBGUtilClass.findStartDateOfFY(System.Today(), fyStartMonth);        
            eachTSMTarget.TSMTar_FYEndDate__c = CYBGUtilClass.findEndDateOfFY(System.Today(), fyStartMonth); 
            if(tsmUserMap.get(eachTSMTarget.TSMTar_TSM__c).ManagerId != null)
            {
                eachTSMTarget.TSMTar_TSMManager__c = tsmUserMap.get(eachTSMTarget.TSMTar_TSM__c).ManagerId;
            }
            else
            {
                //eachTSMTarget.TSMTar_TSMManager__c = ''; //commented by krishna as test class for opportunity trigger handler is failing
            }
            
            if(allActivetsmTargetMap.containsKey((String)eachTSMTarget.TSMTar_TSM__c + (String)eachTSMTarget.TSMTar_Team__c))
            {
                eachTSMTarget.adderror(Label.TSMTargetDuplicateError+
                                      allActivetsmTargetMap.get((String)eachTSMTarget.TSMTar_TSM__c + 
                                                       (String)eachTSMTarget.TSMTar_Team__c).Name);
            }
        }
        List<TSMTarget__c> updatedList = WorkingDaysCalUtil.CalWorkingDaysForTSMTarget(tsmTargetsList); 
    }
    
   
    public static Map<String,TSMTarget__c> activeTSMTargets(){
        Map<String,TSMTarget__c> tsmTargetMap = new Map<String,TSMTarget__c>();
        For(TSMTarget__c eachTSMTarget :[Select TSMTar_TSM__c,TSMTar_Team__c, TSMTar_Status__c, Name
                                         From TSMTarget__c where TSMTar_Status__c =: System.Label.Active]){
            
            tsmTargetMap.put((String)eachTSMTarget.TSMTar_TSM__c + (String)eachTSMTarget.TSMTar_Team__c, eachTSMTarget);                       
        }
        return tsmTargetMap;
    }
    /**
* @description       Method to process and Validate the TSM Target before Update 
* @name              onBeforeUpdate
* @param             List<TSMTarget__c>
* @return            void
* @throws            NA
*/ 
    public static void onBeforeUpdate(List<TSMTarget__c> tsmTargetsList){
        List<TSMTarget__c> updatedList = WorkingDaysCalUtil.CalWorkingDaysForTSMTarget(tsmTargetsList);        
    }
}