force-app/main/default/objects/TSMTarget__c/TSMTarget__c.object-meta.xml
<CustomObject>
    <description>To hold the target and actual for a TSM under specific Team</description>
    <label>FRSM Target</label>
    <nameField>
        <displayFormat>Target - {00000}</displayFormat>
        <label>FRSM Target No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FRSM Targets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_CommTarget__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_CommTarget__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Commodity Target</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_CommTargetTillDate__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_CommTargetTillDate__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Commodity Target To Date</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_CommTarRemainAtClosure__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_CommTarRemainAtClosure__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Commodity Target Remaining At Closure</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_CRMTarget__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_CRMTarget__c</fullName>
    <defaultValue>0</defaultValue>
    <label>CRM Target</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_CRMTargetTillDate__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_CRMTargetTillDate__c</fullName>
    <defaultValue>0</defaultValue>
    <label>CRM Target To Date</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_CRMTarRemainAtClosure__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_CRMTarRemainAtClosure__c</fullName>
    <defaultValue>0</defaultValue>
    <label>CRM Target Remaining At Closure</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_EndDate__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_EndDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Plan End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_FXDirectTarget__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_FXDirectTarget__c</fullName>
    <defaultValue>0</defaultValue>
    <label>FX Direct Target</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_FXDirectTargetTillDate__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_FXDirectTargetTillDate__c</fullName>
    <defaultValue>0</defaultValue>
    <label>FX Direct Target To Date</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_FXDirectTarRemainAtClosure__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_FXDirectTarRemainAtClosure__c</fullName>
    <defaultValue>0</defaultValue>
    <label>FX Direct Target Remaining At Closure</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_FXIndirectTarget__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_FXIndirectTarget__c</fullName>
    <defaultValue>0</defaultValue>
    <label>FX Indirect Target</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_FXIndirectTargetTillDate__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_FXIndirectTargetTillDate__c</fullName>
    <defaultValue>0</defaultValue>
    <label>FX Indirect Target To Date</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_FXIndirectTarRemainAtClosure__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_FXIndirectTarRemainAtClosure__c</fullName>
    <defaultValue>0</defaultValue>
    <label>FX Indirect Target Remaining At Closure</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_FXRetail__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_FXRetail__c</fullName>
    <defaultValue>0</defaultValue>
    <label>FX Retail Target</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_FXRetailRemainingAtClosure__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_FXRetailRemainingAtClosure__c</fullName>
    <defaultValue>0</defaultValue>
    <label>FX Retail Target Remaining At Closure</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_FXRetailTillDate__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_FXRetailTillDate__c</fullName>
    <defaultValue>0</defaultValue>
    <label>FX Retail Target To Date</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_IRRMTarget__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_IRRMTarget__c</fullName>
    <defaultValue>0</defaultValue>
    <label>IRRM Target</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_IRRMTargetTillDate__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_IRRMTargetTillDate__c</fullName>
    <defaultValue>0</defaultValue>
    <label>IRRM Target To Date</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_IRRMTarRemainAtClosure__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_IRRMTarRemainAtClosure__c</fullName>
    <defaultValue>0</defaultValue>
    <label>IRRM Target Remaining At Closure</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_StartDate__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_StartDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Plan Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_Status__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Ended</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
                <isActive>false</isActive>
                <label>Closed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_Terminated__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_Terminated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Terminated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_TerminationDate__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_TerminationDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Termination Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_TotalWorkingDays__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_TotalWorkingDays__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total # Working Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_TSM__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_TSM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Risk Solutions Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>TSMTargets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_TSMLocation__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_TSMLocation__c</fullName>
    <formula>TEXT(TSMTar_TSM__r.Location__c)</formula>
    <label>FRSM Location</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_WorkingDays__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_WorkingDays__c</fullName>
    <label># Working Days To Date</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TSMTargetWorkingDays.cls
/*
@Author        : Sushant
@Name          : TSMTargetWorkingDays 
@Created Date  : 28th Feb 2018
@Description   : This is a Batch Class to get the # working days for TSM Target
@version       : 1.0
*/
global class TSMTargetWorkingDays implements Database.Batchable<sObject>{
/**
* @description       Method to get all Active and Closed TSM target records where End date is greater than Today
* @name              start
* @param             Database.BatchableContext
* @return            Database.QueryLocator
* @throws            NA
*/ 
    global Database.QueryLocator start(Database.BatchableContext BC){
        String query =  'SELECT ID, TSMTar_TSM__c, TSMTar_TSMLocation__c, TSMTar_StartDate__c, '+
                        'TSMTar_TotalWorkingDays__c, TSMTar_WorkingDays__c, TSMTar_TerminationDate__c, '+
                        'TSMTar_Status__c, TSMTar_EndDate__c , TSMTar_FXDirectTarget__c, TSMTar_Terminated__c, '+
            			'TSMTar_FXDirectTargetTillDate__c, TSMTar_FXIndirectTarget__c, TSMTar_FXIndirectTargetTillDate__c, '+
            			'TSMTar_CRMTarget__c, TSMTar_CRMTargetTillDate__c, TSMTar_CommTarget__c, '+
            			'TSMTar_CommTargetTillDate__c, TSMTar_IRRMTarget__c, TSMTar_IRRMTargetTillDate__c, '+
            			'TSMTar_FXRetail__c, TSMTar_FXRetailTillDate__c,'+
            			'TSMTar_FXRetailRemainingAtClosure__c,'+
            			'TSMTar_FXDirectTarRemainAtClosure__c, TSMTar_FXIndirectTarRemainAtClosure__c, '+
            			'TSMTar_CRMTarRemainAtClosure__c, TSMTar_CommTarRemainAtClosure__c, TSMTar_IRRMTarRemainAtClosure__c '+
                        'FROM TSMTarget__c WHERE TSMTar_Status__c != \'Inactive\' AND TSMTar_Terminated__c = false';        
        return Database.getQueryLocator(query);
    }
/**
* @description       Method to calculate No of working days till and Total No of working days .
* @name              execute
* @param             Database.BatchableContext,List<TSMTarget__c>
* @return            Void
* @throws            NA
*/ 
    global void execute(Database.BatchableContext BC, List<TSMTarget__c> scope){
        List<TSMTarget__c> updateTSMTarList = WorkingDaysCalUtil.CalWorkingDaysForTSMTarget(scope);
        Database.SaveResult[] urList = Database.update(updateTSMTarList, False);                
        /*for (Database.SaveResult ur : urList) {
            if (ur.isSuccess()) {
                System.debug('Successfully Updated TSM Target. TSM Target ID: ' + ur.getId());
            }
            else {
                for(Database.Error err : ur.getErrors()) {
                    System.debug('The following error has occurred.');                    
                    System.debug(err.getStatusCode() + ': ' + err.getMessage());
                    System.debug('TSM Target fields that affected this error: ' + err.getFields());
                }
            } 
        }*/
    }
/**
* @description       Finish Method
* @name              finish
* @param             Database.BatchableContext
* @return            Void
* @throws            NA
*/     
    global void finish(Database.BatchableContext BC){
    }
}