force-app/main/default/objects/TSMTarget__c/TSMTarget__c.object-meta.xml
<CustomObject>
    <description>To hold the target and actual for a TSM under specific Team</description>
    <label>FRSM Target</label>
    <nameField>
        <displayFormat>Target - {00000}</displayFormat>
        <label>FRSM Target No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FRSM Targets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_CommTarget__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_CommTarget__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Commodity Target</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_CRMTarget__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_CRMTarget__c</fullName>
    <defaultValue>0</defaultValue>
    <label>CRM Target</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_EndDate__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_EndDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Plan End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_FXDirectTarget__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_FXDirectTarget__c</fullName>
    <defaultValue>0</defaultValue>
    <label>FX Direct Target</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_FXIndirectTarget__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_FXIndirectTarget__c</fullName>
    <defaultValue>0</defaultValue>
    <label>FX Indirect Target</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_FXRetail__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_FXRetail__c</fullName>
    <defaultValue>0</defaultValue>
    <label>FX Retail Target</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_IRRMTarget__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_IRRMTarget__c</fullName>
    <defaultValue>0</defaultValue>
    <label>IRRM Target</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_IsCurrentFY__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_IsCurrentFY__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Current FY</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_StartDate__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_StartDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Plan Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_Status__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Ended</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
                <isActive>false</isActive>
                <label>Closed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_Team__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_Team__c</fullName>
    <label>Business Centre</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Team status is not active.</errorMessage>
        <filterItems>
            <field>Team__c.Team_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Team__c</referenceTo>
    <relationshipName>TSMTargets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_TSM__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_TSM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Risk Solutions Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>TSMTargets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TSMTargetFiscalYearBatch.cls
/*
@Author        : Santhoshan
@Name          : TSMTargetFiscalYearBatch
@Created Date  : 28th Feb 2018
@Description   : This is a Batch Class to convert the TSM Targets to the Current Fiscal Year
@version       : 1.0
*/
global class TSMTargetFiscalYearBatch implements Database.Batchable<sObject>{
    global Database.QueryLocator start(Database.BatchableContext BC){
        
        String query = 'SELECT TSMTar_TSM__c, TSMTar_Team__c,'+ 
            'TSMTar_StartDate__c,TSMTar_EndDate__c, TSMTar_IsCurrentFY__c,'+
            'TSMTar_FXDirectTarget__c, TSMTar_FXIndirectTarget__c,'+
            'TSMTar_CRMTarget__c, TSMTar_CommTarget__c, TSMTar_IRRMTarget__c,'+            
            'TSMTar_Status__c, TSMTar_FXRetail__c FROM TSMTarget__c '+
            'WHERE TSMTar_Status__c != \'Inactive\'';
        
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<TSMTarget__c> scope){
        List<TSMTarget__c> TSMTarList = new List<TSMTarget__c>();
        Integer fyStartMonth = CYBGUtilClass.fiscalYearStartMonth();
        Date startDate = CYBGUtilClass.findStartDateOfFY(System.Today(), fyStartMonth); 
        Date endDate = CYBGUtilClass.findEndDateOfFY(System.Today(), fyStartMonth); 
        
        for(TSMTarget__c eachRecTSM : scope){
            if(eachRecTSM.TSMTar_Status__c.equals(System.Label.Active) || eachRecTSM.TSMTar_Status__c.equals(System.Label.Ended))
            {
                TSMTarget__c newTSMTar = new TSMTarget__c();
                newTSMTar.TSMTar_TSM__c = eachRecTSM.TSMTar_TSM__c;
                newTSMTar.TSMTar_Team__c = eachRecTSM.TSMTar_Team__c;
                newTSMTar.TSMTar_StartDate__c = startDate;
                newTSMTar.TSMTar_EndDate__c = endDate;
                newTSMTar.TSMTar_IsCurrentFY__c = true;
                newTSMTar.TSMTar_FXDirectTarget__c = eachRecTSM.TSMTar_FXDirectTarget__c;
                newTSMTar.TSMTar_FXIndirectTarget__c = eachRecTSM.TSMTar_FXIndirectTarget__c;
                newTSMTar.TSMTar_CRMTarget__c = eachRecTSM.TSMTar_CRMTarget__c;
                newTSMTar.TSMTar_CommTarget__c = eachRecTSM.TSMTar_CommTarget__c;
                newTSMTar.TSMTar_IRRMTarget__c = eachRecTSM.TSMTar_IRRMTarget__c;  
                newTSMTar.TSMTar_FXRetail__c = eachRecTSM.TSMTar_FXRetail__c;  
                newTSMTar.TSMTar_Status__c = System.Label.Active;
                TSMTarList.add(newTSMTar);
                eachRecTSM.TSMTar_IsCurrentFY__c = false;
                eachRecTSM.TSMTar_Status__c = System.Label.Inactive;
            }
            //else if(eachRecTSM.TSMTar_Status__c.equals(System.Label.Terminated))
            else{
                eachRecTSM.TSMTar_IsCurrentFY__c = false;
                eachRecTSM.TSMTar_Status__c = System.Label.Inactive;
            }
            
        }
        if(!scope.isEmpty()){
        	Database.SaveResult[] urList = Database.update(scope,false);
            /*for (Database.SaveResult ur : urList) {
                if (ur.isSuccess()) {
                    System.debug('Successfully Updated Old TSM Target. TSM Target ID: ' + ur.getId());
                }
                else {
                    for(Database.Error err : ur.getErrors()) {
                        System.debug('The following error has occurred.');                    
                        System.debug(err.getStatusCode() + ': ' + err.getMessage());
                        System.debug('TSM Target fields that affected this error: ' + err.getFields());
                    }
                } 
            }*/
        }
        if(!TSMTarList.isEmpty()){
        	Database.SaveResult[] srList = Database.insert(TSMTarList,false);
            /*for (Database.SaveResult sr : srList) {
                if (sr.isSuccess()) {
                    System.debug('Successfully Inserted New TSM Target. TSM Target ID: ' + sr.getId());
                }
                else {
                    for(Database.Error err : sr.getErrors()) {
                        System.debug('The following error has occurred.');                    
                        System.debug(err.getStatusCode() + ': ' + err.getMessage());
                        System.debug('TSM Target fields that affected this error: ' + err.getFields());
                    }
                }
            }*/
        }        
    }
    
    global void finish(Database.BatchableContext BC){
    }
}