force-app/main/default/objects/Repository__c/Repository__c.object-meta.xml
<CustomObject>
    <description>An Object to store and manage data for Report.</description>
    <label>Repository</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Repository Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Repositories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Repository__c/fields/Rep_BusinessCentre__c.field-meta.xml
<CustomField>
    <fullName>Rep_BusinessCentre__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Business Centre</label>
    <length>220</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Repository__c/fields/Rep_BusinessCentreId__c.field-meta.xml
<CustomField>
    <fullName>Rep_BusinessCentreId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Business Centre Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Repository__c/fields/Rep_CombineId__c.field-meta.xml
<CustomField>
    <fullName>Rep_CombineId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Combine Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Repository__c/fields/Rep_CommodityActual__c.field-meta.xml
<CustomField>
    <fullName>Rep_CommodityActual__c</fullName>
    <label>Commodity Actual</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Repository__c/fields/Rep_FXDirectActual__c.field-meta.xml
<CustomField>
    <fullName>Rep_FXDirectActual__c</fullName>
    <label>FX Direct Actual</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Repository__c/fields/Rep_FXIndirectActual__c.field-meta.xml
<CustomField>
    <fullName>Rep_FXIndirectActual__c</fullName>
    <label>FX Indirect Actual</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Repository__c/fields/Rep_IRRMActual__c.field-meta.xml
<CustomField>
    <fullName>Rep_IRRMActual__c</fullName>
    <label>IRRM Actual</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Repository__c/fields/Rep_Month__c.field-meta.xml
<CustomField>
    <fullName>Rep_Month__c</fullName>
    <label>Month</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Repository__c/fields/Rep_MonthText__c.field-meta.xml
<CustomField>
    <fullName>Rep_MonthText__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Month Text</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Repository__c/fields/Rep_RMId__c.field-meta.xml
<CustomField>
    <fullName>Rep_RMId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>RM Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Repository__c/fields/Rep_RMName__c.field-meta.xml
<CustomField>
    <fullName>Rep_RMName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>RM Name</label>
    <length>220</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Repository__c/recordTypes/CustomerAndPM.recordType-meta.xml
<RecordType>
    <fullName>CustomerAndPM</fullName>
    <active>true</active>
    <label>CustomerAndPM</label>
</RecordType>

force-app/main/default/classes/ReportRep_Delete_Repository_PSD2_Test.cls
@isTest
public class ReportRep_Delete_Repository_PSD2_Test {
    
    public static testmethod void repDeleteCustomerAndPmRepositoryRecordsTest(){
        List<Repository__c> customerAndPmRepositoryList = new List<Repository__c>();
        Id RecordTypeIdRepositroyCustomerAndPm = Schema.SObjectType.Repository__c.getRecordTypeInfosByName().get('CustomerAndPM').getRecordTypeId();
        for(Integer i=0;i<=20;i++){
            Repository__c rep1 = new Repository__c();
            rep1.Rep_BusinessCentre__c = '1234'+i;
            rep1.RecordTypeId = RecordTypeIdRepositroyCustomerAndPm;
            rep1.Rep_BusinessCentreId__c = '1234'+i;
            rep1.Rep_CombineId__c = '12341234'+i;
            rep1.Rep_RMName__c = '2344'+i;
            rep1.Rep_RMId__c = '2344'+i;
            rep1.Rep_Month__c = 6;
            rep1.Rep_MonthText__c = '6';
            rep1.Rep_FXDirectActual__c = 1200;
            rep1.Rep_FXIndirectActual__c = 1200; 
            rep1.Rep_CommodityActual__c = 1200;
            rep1.Rep_IRRMActual__c = 1200;
            customerAndPmRepositoryList.add(rep1);                      
        }
        insert customerAndPmRepositoryList;
        Test.startTest();
        ReportRep_Delete_Repository_PSD2 reportRepDeleteCustomerAndPmRecords = new ReportRep_Delete_Repository_PSD2();
        Database.executeBatch(reportRepDeleteCustomerAndPmRecords, 100);
        Test.stopTest();        
    }
}