force-app/main/default/objects/Contact/fields/Contact_Status__c.field-meta.xml
<CustomField>
    <fullName>Contact_Status__c</fullName>
    <label>Contact Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <default>true</default>
                <label>Inactive</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Customer_Banking_Centre__c.field-meta.xml
<CustomField>
    <fullName>Customer_Banking_Centre__c</fullName>
    <label>Customer Banking Centre</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aberdeen</fullName>
            </value>
            <value>
                <fullName>Birmingham</fullName>
            </value>
            <value>
                <fullName>Business Direct</fullName>
            </value>
            <value>
                <fullName>Carlisle</fullName>
            </value>
            <value>
                <fullName>Closed Codes</fullName>
            </value>
            <value>
                <fullName>CRE - North</fullName>
            </value>
            <value>
                <fullName>Dundee</fullName>
            </value>
            <value>
                <fullName>East Midlands</fullName>
            </value>
            <value>
                <fullName>Edinburgh</fullName>
            </value>
            <value>
                <fullName>Gatwick</fullName>
            </value>
            <value>
                <fullName>Glasgow</fullName>
            </value>
            <value>
                <fullName>Gloucester</fullName>
            </value>
            <value>
                <fullName>Growth Finance</fullName>
            </value>
            <value>
                <fullName>Hull &amp; Humber</fullName>
            </value>
            <value>
                <fullName>Inverness</fullName>
            </value>
            <value>
                <fullName>Lanarkshire</fullName>
            </value>
            <value>
                <fullName>Leeds</fullName>
            </value>
            <value>
                <fullName>Lincoln</fullName>
            </value>
            <value>
                <fullName>London West End</fullName>
            </value>
            <value>
                <fullName>Manchester</fullName>
            </value>
            <value>
                <fullName>Merseyside</fullName>
            </value>
            <value>
                <fullName>North East</fullName>
            </value>
            <value>
                <fullName>North Yorkshire</fullName>
            </value>
            <value>
                <fullName>Northampton &amp; Peterborough</fullName>
            </value>
            <value>
                <fullName>Preston</fullName>
            </value>
            <value>
                <fullName>Reading &amp; Oxford</fullName>
            </value>
            <value>
                <fullName>SAF - Aberdeen Office</fullName>
            </value>
            <value>
                <fullName>SAF - Birmingham Office</fullName>
            </value>
            <value>
                <fullName>SAF - Central Scotland Office</fullName>
            </value>
            <value>
                <fullName>SAF - Leeds Office</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/TDM_BankingCenter__c.field-meta.xml
<CustomField>
    <fullName>TDM_BankingCenter__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>TDM_BankingCenter</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/TDM_Cust_Name__c.field-meta.xml
<CustomField>
    <fullName>TDM_Cust_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>TDM Cust Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/TDM_Name__c.field-meta.xml
<CustomField>
    <fullName>TDM_Name__c</fullName>
    <description>This field will receive value from TDM</description>
    <encryptionScheme>None</encryptionScheme>
    <label>TDM_Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Banker.recordType-meta.xml
<RecordType>
    <fullName>Banker</fullName>
    <active>true</active>
    <label>Banker</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Customer_Name__mdt/Customer_Name__mdt.object-meta.xml
<CustomObject>
    <label>Customer_Name</label>
    <pluralLabel>Customer_Names</pluralLabel>
</CustomObject>

force-app/main/default/objects/Customer_Name__mdt/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <label>Customer Type</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Customer_Name__mdt/fields/CustomerName__c.field-meta.xml
<CustomField>
    <fullName>CustomerName__c</fullName>
    <label>CustomerName</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ContactTriggerHandler.cls
/*
  @Author        : SUHAS BARGI
  @Name          : ContactTriggerHandler
  @Created Date  : 30th MARCH 2018
  @Description   : TriggerHandler for ContactTrigger
  @version       : 1.0
*/ 
public class ContactTriggerHandler {
    
    
    /**
* @description       To set First Name, Last Name & Customer Banking Centre
* @name              onBeforeInsert
* @param             List<Contact>
* @return            void
* @throws            NA
*/ 
    public static void onBeforeInsert(List<Contact> contactDataList) { 

        Map<String,String> CustNameMap = new Map<String,String>();
        For(Customer_Name__mdt eachCustName : [SELECT ID,Customer_Type__c,CustomerName__c FROM Customer_Name__mdt])
        {
            CustNameMap.put((String)eachCustName.CustomerName__c.trim(), (String)eachCustName.Customer_Type__c);
            
        }
        
        for(Contact eachCData : contactDataList){
            
                if(eachCData.TDM_Name__c != null){
                    if(eachCData.TDM_Name__c.lastIndexOf(' ') !=null && eachCData.TDM_Name__c.lastIndexOf(' ')>0){
                        Integer lastIndex = eachCData.TDM_Name__c.lastIndexOf(' ');            
                        eachCData.FirstName = eachCData.TDM_Name__c.substring(0, lastIndex);
                        eachCData.MiddleName='';
                        if(eachCData.TDM_Name__c.substring(eachCData.TDM_Name__c.lastIndexOf(' ')+1) !=null){
                            eachCData.LastName = eachCData.TDM_Name__c.substring(eachCData.TDM_Name__c.lastIndexOf(' ')+1);
                        }
                    }else{ 
                        eachCData.LastName =eachCData.TDM_Name__c;
                        eachCData.FirstName ='';
                        eachCData.MiddleName='';
                    }
                    eachCData.RecordTypeId=Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Banker').getRecordTypeId();
                }else if(eachCData.LastName == null){
                    eachCData.LastName='Reserved Banker';
                    eachCData.RecordTypeId=Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Banker').getRecordTypeId();
                }
            if(eachCData.Customer_Banking_Centre__c != Null || eachCData.TDM_BankingCenter__c != Null)
            	eachCData.Customer_Banking_Centre__c = (eachCData.TDM_BankingCenter__c==Null?eachCData.Customer_Banking_Centre__c:eachCData.TDM_BankingCenter__c);
            else
                eachCData.Customer_Banking_Centre__c = null;
            
            eachCData.Contact_Status__c='Active';
            if(eachCData.TDM_Cust_Name__c!=null && ! CustNameMap.isEmpty() && CustNameMap.containsKey(eachCData.TDM_Cust_Name__c.trim())){
                eachCData.AccountId=(Id)CustNameMap.get(eachCData.TDM_Cust_Name__c.trim());
            }

            eachCData.TDM_Name__c='';
            eachCData.TDM_BankingCenter__c='';
            eachCData.TDM_Cust_Name__c='';
        }
    }
    /**
* @description       To Update First Name, Last Name & Customer Banking Centre
* @name              onBeforeUpdate
* @param             List<Contact>
* @return            void
* @throws            NA
*/
    public static void onBeforeUpdate(List<Contact> contactDataList) { 
        Map<String,String> CustNameMap = new Map<String,String>();
        For(Customer_Name__mdt eachCustName : [SELECT ID,Customer_Type__c,CustomerName__c FROM Customer_Name__mdt])
        {
            CustNameMap.put((String)eachCustName.CustomerName__c.trim(), (String)eachCustName.Customer_Type__c);
            
        }

     	for(Contact eachCData : contactDataList){

            if(eachCData.TDM_Name__c != null){
                if(eachCData.TDM_Name__c.lastIndexOf(' ') !=null && eachCData.TDM_Name__c.lastIndexOf(' ')>0){
                    Integer lastIndex = eachCData.TDM_Name__c.lastIndexOf(' ');            
                    eachCData.FirstName = eachCData.TDM_Name__c.substring(0, lastIndex);
                    eachCData.MiddleName='';
                    if(eachCData.TDM_Name__c.substring(eachCData.TDM_Name__c.lastIndexOf(' ')+1) !=null){
                    eachCData.LastName = eachCData.TDM_Name__c.substring(eachCData.TDM_Name__c.lastIndexOf(' ')+1);
                    }
                }else{
                    eachCData.LastName =eachCData.TDM_Name__c;
                    eachCData.FirstName ='';
                    eachCData.MiddleName='';
                }
            }
            if(eachCData.Customer_Banking_Centre__c != Null || eachCData.TDM_BankingCenter__c != Null)
            	eachCData.Customer_Banking_Centre__c = (eachCData.TDM_BankingCenter__c==Null?eachCData.Customer_Banking_Centre__c:eachCData.TDM_BankingCenter__c);
            else
                eachCData.Customer_Banking_Centre__c = Null;
            if(eachCData.TDM_Cust_Name__c!=null && ! CustNameMap.isEmpty() && CustNameMap.containsKey(eachCData.TDM_Cust_Name__c.trim())){


            }

            eachCData.TDM_Name__c='';
            eachCData.TDM_BankingCenter__c='';
            eachCData.TDM_Cust_Name__c='';
        }
    }

}