force-app/main/default/objects/Division__c/Division__c.object-meta.xml
<CustomObject>
    <label>Group</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Division__c/fields/Div_CommActual__c.field-meta.xml
<CustomField>
    <fullName>Div_CommActual__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Commodity Actual</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Division__c/fields/Div_CommTarget__c.field-meta.xml
<CustomField>
    <fullName>Div_CommTarget__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Commodity Target</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Division__c/fields/Div_CRMActual__c.field-meta.xml
<CustomField>
    <fullName>Div_CRMActual__c</fullName>
    <defaultValue>0</defaultValue>
    <label>CRM Actual</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Division__c/fields/Div_CRMTarget__c.field-meta.xml
<CustomField>
    <fullName>Div_CRMTarget__c</fullName>
    <defaultValue>0</defaultValue>
    <label>CRM Target</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Division__c/fields/Div_FXDirectActual__c.field-meta.xml
<CustomField>
    <fullName>Div_FXDirectActual__c</fullName>
    <defaultValue>0</defaultValue>
    <label>FX Direct Actual</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Division__c/fields/Div_FXDirectTarget__c.field-meta.xml
<CustomField>
    <fullName>Div_FXDirectTarget__c</fullName>
    <defaultValue>0</defaultValue>
    <label>FX Direct Target</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Division__c/fields/Div_FXIndirectActual__c.field-meta.xml
<CustomField>
    <fullName>Div_FXIndirectActual__c</fullName>
    <defaultValue>0</defaultValue>
    <label>FX Indirect Actual</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Division__c/fields/Div_FXIndirectTarget__c.field-meta.xml
<CustomField>
    <fullName>Div_FXIndirectTarget__c</fullName>
    <defaultValue>0</defaultValue>
    <label>FX Indirect Target</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Division__c/fields/Div_FXRetail__c.field-meta.xml
<CustomField>
    <fullName>Div_FXRetail__c</fullName>
    <defaultValue>0</defaultValue>
    <label>FX Retail Target</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Division__c/fields/Div_FXRetailActual__c.field-meta.xml
<CustomField>
    <fullName>Div_FXRetailActual__c</fullName>
    <defaultValue>0</defaultValue>
    <label>FX Retail Actual</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Division__c/fields/Div_IRRMActual__c.field-meta.xml
<CustomField>
    <fullName>Div_IRRMActual__c</fullName>
    <defaultValue>0</defaultValue>
    <label>IRRM Actual</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Division__c/fields/Div_IRRMTarget__c.field-meta.xml
<CustomField>
    <fullName>Div_IRRMTarget__c</fullName>
    <defaultValue>0</defaultValue>
    <label>IRRM Target</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Division__c/fields/Div_NumberofChilds__c.field-meta.xml
<CustomField>
    <fullName>Div_NumberofChilds__c</fullName>
    <label>Number of Childs</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Region__c/Region__c.object-meta.xml
<CustomObject>
    <label>Division</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Division Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Divisions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Region__c/fields/Region_CommActual__c.field-meta.xml
<CustomField>
    <fullName>Region_CommActual__c</fullName>
    <label>Commodity Actual</label>
    <summarizedField>Centre__c.Centre_CommActual__c</summarizedField>
    <summaryForeignKey>Centre__c.Centre_Region__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Region__c/fields/Region_CommTarget__c.field-meta.xml
<CustomField>
    <fullName>Region_CommTarget__c</fullName>
    <label>Commodity Target</label>
    <summarizedField>Centre__c.Centre_CommTarget__c</summarizedField>
    <summaryForeignKey>Centre__c.Centre_Region__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Region__c/fields/Region_CRMActual__c.field-meta.xml
<CustomField>
    <fullName>Region_CRMActual__c</fullName>
    <label>CRM Actual</label>
    <summarizedField>Centre__c.Centre_CRMActual__c</summarizedField>
    <summaryForeignKey>Centre__c.Centre_Region__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Region__c/fields/Region_CRMTarget__c.field-meta.xml
<CustomField>
    <fullName>Region_CRMTarget__c</fullName>
    <label>CRM Target</label>
    <summarizedField>Centre__c.Centre_CRMTarget__c</summarizedField>
    <summaryForeignKey>Centre__c.Centre_Region__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Region__c/fields/Region_Division__c.field-meta.xml
<CustomField>
    <fullName>Region_Division__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Group</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Division is not active.</errorMessage>
        <filterItems>
            <field>Division__c.Div_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Division__c</referenceTo>
    <relationshipLabel>Divisions</relationshipLabel>
    <relationshipName>Regions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Region__c/fields/Region_FXDirectActual__c.field-meta.xml
<CustomField>
    <fullName>Region_FXDirectActual__c</fullName>
    <label>FX Direct Actual</label>
    <summarizedField>Centre__c.Centre_FXDirectActual__c</summarizedField>
    <summaryForeignKey>Centre__c.Centre_Region__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Region__c/fields/Region_FXDirectTarget__c.field-meta.xml
<CustomField>
    <fullName>Region_FXDirectTarget__c</fullName>
    <label>FX Direct Target</label>
    <summarizedField>Centre__c.Centre_FXDirectTarget__c</summarizedField>
    <summaryForeignKey>Centre__c.Centre_Region__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Region__c/fields/Region_FXIndirectActual__c.field-meta.xml
<CustomField>
    <fullName>Region_FXIndirectActual__c</fullName>
    <label>FX Indirect Actual</label>
    <summarizedField>Centre__c.Centre_FXIndirectActual__c</summarizedField>
    <summaryForeignKey>Centre__c.Centre_Region__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Region__c/fields/Region_FXIndirectTarget__c.field-meta.xml
<CustomField>
    <fullName>Region_FXIndirectTarget__c</fullName>
    <label>FX Indirect Target</label>
    <summarizedField>Centre__c.Centre_FXIndirectTarget__c</summarizedField>
    <summaryForeignKey>Centre__c.Centre_Region__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Region__c/fields/Region_FXRetail__c.field-meta.xml
<CustomField>
    <fullName>Region_FXRetail__c</fullName>
    <label>FX Retail Target</label>
    <summarizedField>Centre__c.Centre_FXRetail__c</summarizedField>
    <summaryFilterItems>
        <field>Centre__c.Centre_Status__c</field>
        <operation>equals</operation>
        <value>Active</value>
    </summaryFilterItems>
    <summaryForeignKey>Centre__c.Centre_Region__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Region__c/fields/Region_FXRetailActual__c.field-meta.xml
<CustomField>
    <fullName>Region_FXRetailActual__c</fullName>
    <label>FX Retail Actual</label>
    <summarizedField>Centre__c.Centre_FXRetailActual__c</summarizedField>
    <summaryFilterItems>
        <field>Centre__c.Centre_Status__c</field>
        <operation>equals</operation>
        <value>Active</value>
    </summaryFilterItems>
    <summaryForeignKey>Centre__c.Centre_Region__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Region__c/fields/Region_IRRMActual__c.field-meta.xml
<CustomField>
    <fullName>Region_IRRMActual__c</fullName>
    <label>IRRM Actual</label>
    <summarizedField>Centre__c.Centre_IRRMActual__c</summarizedField>
    <summaryForeignKey>Centre__c.Centre_Region__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Region__c/fields/Region_IRRMTarget__c.field-meta.xml
<CustomField>
    <fullName>Region_IRRMTarget__c</fullName>
    <label>IRRM Target</label>
    <summarizedField>Centre__c.Centre_IRRMTarget__c</summarizedField>
    <summaryForeignKey>Centre__c.Centre_Region__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Region__c/fields/Region_Status__c.field-meta.xml
<CustomField>
    <fullName>Region_Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/RegionTriggerHandler.cls
/*
@Author        : Ramkumar M B
@Name          : RegionTriggerHandler
@Created Date  : 12th February 2018
@Description   : This is a Handler for RegionTrigger 
@version       : 1.0
*/
public class RegionTriggerHandler 
{
    /**
* @description       Method to do the Roll up summary on Division based for each Region .
* @name              onAfterUpdate
* @param             List<Region__c>
* @return            void
* @throws            NA
*/ 
    public static void onAfterUpdate(List<Region__c> regionRecordList)
    {
        List<Division__c> divisionListToUpdate = new List<Division__c>();
        List<Region__c> regionRecordListforDivisions = new List<Region__c>();
        List<Id>divisionIdList =  new List<Id>();
        Map<Id,Division__c>divisionMap ;
        
        // Capturing old and new Division Id for each updated Region        
        For(Region__c eachRegion : regionRecordList)
        {
            Region__c oldRegion = (Region__c)Trigger.oldMap.get(eachRegion.Id);            
            If(oldRegion.Region_Division__c!=eachRegion.Region_Division__c)
            {
                divisionIdList.add(oldRegion.Region_Division__c);
            }          
            divisionIdList.add(eachRegion.Region_Division__c);            
            Division__c divisionRecordForEachTeam = new Division__c();
            divisionRecordForEachTeam.id = eachregion.Region_Division__c;            
        }              
        // Get all Division details and Region Details for captured Division Id list
        divisionMap     = New Map<Id,Division__c>([Select Id,Div_FXDirectTarget__c,Div_FXIndirectTarget__c,
                                                   Div_FXDirectActual__c,Div_FXIndirectActual__c,Div_CommTarget__c,
                                                   Div_CommActual__c,Div_CRMTarget__c,Div_NumberofChilds__c,
                                                   Div_CRMActual__c,Div_IRRMTarget__c,Div_IRRMActual__c,
                                                   Div_FXRetail__c,Div_FXRetailActual__c
                                                   from Division__c where ID IN  :divisionIdList]);
        regionRecordListforDivisions =           [Select Id,Region_Division__c,Region_FXDirectTarget__c,
                                                  Region_FXIndirectTarget__c,Region_FXRetail__c,Region_FXRetailActual__c,
                                                  Region_FXDirectActual__c,Region_FXIndirectActual__c,
                                                  Region_CommTarget__c,Region_CommActual__c,Region_CRMTarget__c,
                                                  Region_CRMActual__c,
                                                  Region_IRRMTarget__c,Region_IRRMActual__c from Region__c 
                                                  where Region_Division__c IN  :divisionIdList AND Region_Status__c =: System.Label.Active];
        
        
        
        //Iterate all the Captured division and Region records,
        //do the roll up for all matched Division under all region records .
        
        For(Division__c eachDivision :divisionMap.values())
        { 
            Division__c divisionValueInMap = divisionMap.get(eachDivision.Id);
            divisionValueInMap.Div_FXDirectTarget__c = 0;
            divisionValueInMap.Div_FXIndirectTarget__c = 0;
            divisionValueInMap.Div_FXDirectActual__c = 0;
            divisionValueInMap.Div_FXIndirectActual__c = 0;                    
            divisionValueInMap.div_CRMTarget__c = 0;
            divisionValueInMap.Div_CRMActual__c = 0;
            divisionValueInMap.div_CommTarget__c = 0;
            divisionValueInMap.Div_CommActual__c = 0;
            divisionValueInMap.div_IRRMTarget__c = 0;
            divisionValueInMap.Div_IRRMActual__c = 0;
            divisionValueInMap.Div_FXRetail__c   = 0;
            divisionValueInMap.Div_FXRetailActual__c = 0; 
            divisionValueInMap.Div_NumberofChilds__c = 0;
            For(Region__c eachRegion : regionRecordListforDivisions)
            {
                if(eachDivision.Id  == eachRegion.Region_Division__c)
                {
                    divisionValueInMap.Div_FXDirectTarget__c      =   divisionValueInMap.Div_FXDirectTarget__c +
                        eachRegion.Region_FXDirectTarget__c;
                    divisionValueInMap.Div_FXDirectActual__c      =   divisionValueInMap.Div_FXDirectActual__c+
                        eachRegion.Region_FXDirectActual__c;
                    divisionValueInMap.Div_FXIndirectTarget__c    =   divisionValueInMap.Div_FXIndirectTarget__c +
                        eachRegion.Region_FXIndirectTarget__c;
                    divisionValueInMap.Div_FXIndirectActual__c    =   divisionValueInMap.Div_FXIndirectActual__c+
                        eachRegion.Region_FXIndirectActual__c;   
                    divisionValueInMap.div_CRMTarget__c           =   divisionValueInMap.Div_CRMTarget__c +
                        eachRegion.Region_CRMTarget__c;
                    divisionValueInMap.Div_CRMActual__c           =   divisionValueInMap.Div_CRMActual__c+
                        eachRegion.Region_CRMActual__c;
                    divisionValueInMap.div_CommTarget__c          =   divisionValueInMap.Div_CommTarget__c+
                        eachRegion.Region_CommTarget__c;
                    divisionValueInMap.Div_CommActual__c          =   divisionValueInMap.Div_CommActual__c+
                        eachRegion.Region_CommActual__c;
                    divisionValueInMap.div_IRRMTarget__c          =   divisionValueInMap.Div_IRRMTarget__c+
                        eachRegion.Region_IRRMTarget__c;
                    divisionValueInMap.Div_IRRMActual__c          =   divisionValueInMap.Div_IRRMActual__c+
                        eachRegion.Region_IRRMActual__c;
                    divisionValueInMap.Div_FXRetail__c          =   divisionValueInMap.Div_FXRetail__c+
                        eachRegion.Region_FXRetail__c;                    
                    divisionValueInMap.Div_FXRetailActual__c          =   divisionValueInMap.Div_FXRetailActual__c+
                        eachRegion.Region_FXRetailActual__c;                    
                    divisionValueInMap.Div_NumberofChilds__c      =   divisionValueInMap.Div_NumberofChilds__c + 1;
                       
                    divisionMap.put(eachRegion.Region_Division__c, divisionValueInMap);                    
                }
            } 
        }         
        divisionListToUpdate = divisionMap.values();
        Database.SaveResult[] updateResult = Database.Update(divisionListToUpdate, False);  
    }
    
    public static void onAfterInsert(List<Region__c> regionRecordList)
    {
        List<Division__c> divisionListToUpdate = new List<Division__c>();
        List<Region__c> regionRecordListforDivisions = new List<Region__c>();
        List<Id>divisionIdList =  new List<Id>();
        Map<Id,Division__c>divisionMap ;
        
        // Capturing old and new Division Id for each updated Region        
        For(Region__c eachRegion : regionRecordList)
        {/*
            Region__c oldRegion = (Region__c)Trigger.oldMap.get(eachRegion.Id);            
            If(oldRegion.Region_Division__c!=eachRegion.Region_Division__c)
            {
                divisionIdList.add(oldRegion.Region_Division__c);
            }       
*/
            divisionIdList.add(eachRegion.Region_Division__c);            
            Division__c divisionRecordForEachTeam = new Division__c();
            divisionRecordForEachTeam.id = eachregion.Region_Division__c;            
        }              
        // Get all Division details and Region Details for captured Division Id list
        divisionMap     = New Map<Id,Division__c>([Select Id,Div_FXDirectTarget__c,Div_FXIndirectTarget__c,
                                                   Div_FXDirectActual__c,Div_FXIndirectActual__c,Div_CommTarget__c,
                                                   Div_CommActual__c,Div_CRMTarget__c,Div_NumberofChilds__c,
                                                   Div_CRMActual__c,Div_IRRMTarget__c,Div_IRRMActual__c,
                                                   Div_FXRetail__c,Div_FXRetailActual__c
                                                   from Division__c where ID IN  :divisionIdList]);
        regionRecordListforDivisions =           [Select Id,Region_Division__c,Region_FXDirectTarget__c,
                                                  Region_FXIndirectTarget__c,Region_FXRetail__c,Region_FXRetailActual__c,
                                                  Region_FXDirectActual__c,Region_FXIndirectActual__c,
                                                  Region_CommTarget__c,Region_CommActual__c,Region_CRMTarget__c,
                                                  Region_CRMActual__c,
                                                  Region_IRRMTarget__c,Region_IRRMActual__c from Region__c 
                                                  where Region_Division__c IN  :divisionIdList AND Region_Status__c =: System.Label.Active];
        
        
        
        //Iterate all the Captured division and Region records,
        //do the roll up for all matched Division under all region records .
        
        For(Division__c eachDivision :divisionMap.values())
        { 
            Division__c divisionValueInMap = divisionMap.get(eachDivision.Id);
            divisionValueInMap.Div_FXDirectTarget__c = 0;
            divisionValueInMap.Div_FXIndirectTarget__c = 0;
            divisionValueInMap.Div_FXDirectActual__c = 0;
            divisionValueInMap.Div_FXIndirectActual__c = 0;                    
            divisionValueInMap.div_CRMTarget__c = 0;
            divisionValueInMap.Div_CRMActual__c = 0;
            divisionValueInMap.div_CommTarget__c = 0;
            divisionValueInMap.Div_CommActual__c = 0;
            divisionValueInMap.div_IRRMTarget__c = 0;
            divisionValueInMap.Div_IRRMActual__c = 0;
            divisionValueInMap.Div_FXRetail__c   = 0;
            divisionValueInMap.Div_FXRetailActual__c = 0; 
            divisionValueInMap.Div_NumberofChilds__c = 0;
            For(Region__c eachRegion : regionRecordListforDivisions)
            {
                if(eachDivision.Id  == eachRegion.Region_Division__c)
                {
                    divisionValueInMap.Div_FXDirectTarget__c      =   divisionValueInMap.Div_FXDirectTarget__c +
                        eachRegion.Region_FXDirectTarget__c;
                    divisionValueInMap.Div_FXDirectActual__c      =   divisionValueInMap.Div_FXDirectActual__c+
                        eachRegion.Region_FXDirectActual__c;
                    divisionValueInMap.Div_FXIndirectTarget__c    =   divisionValueInMap.Div_FXIndirectTarget__c +
                        eachRegion.Region_FXIndirectTarget__c;
                    divisionValueInMap.Div_FXIndirectActual__c    =   divisionValueInMap.Div_FXIndirectActual__c+
                        eachRegion.Region_FXIndirectActual__c;   
                    divisionValueInMap.div_CRMTarget__c           =   divisionValueInMap.Div_CRMTarget__c +
                        eachRegion.Region_CRMTarget__c;
                    divisionValueInMap.Div_CRMActual__c           =   divisionValueInMap.Div_CRMActual__c+
                        eachRegion.Region_CRMActual__c;
                    divisionValueInMap.div_CommTarget__c          =   divisionValueInMap.Div_CommTarget__c+
                        eachRegion.Region_CommTarget__c;
                    divisionValueInMap.Div_CommActual__c          =   divisionValueInMap.Div_CommActual__c+
                        eachRegion.Region_CommActual__c;
                    divisionValueInMap.div_IRRMTarget__c          =   divisionValueInMap.div_IRRMTarget__c+
                        eachRegion.Region_IRRMTarget__c;
                    divisionValueInMap.Div_IRRMActual__c          =   divisionValueInMap.Div_IRRMActual__c+
                        eachRegion.Region_IRRMActual__c;
                    divisionValueInMap.Div_FXRetail__c          =   divisionValueInMap.Div_FXRetail__c+
                        eachRegion.Region_FXRetail__c;                    
                    divisionValueInMap.Div_FXRetailActual__c          =   divisionValueInMap.Div_FXRetailActual__c+
                        eachRegion.Region_FXRetailActual__c;                                    
                    
                    divisionValueInMap.Div_NumberofChilds__c      =   divisionValueInMap.Div_NumberofChilds__c + 1;
                       
                    divisionMap.put(eachRegion.Region_Division__c, divisionValueInMap);                    
                }
            } 
        }         
        divisionListToUpdate = divisionMap.values();
        Database.SaveResult[] updateResult = Database.Update(divisionListToUpdate, False);  
    }
}