force-app/main/default/objects/Centre__c/Centre__c.object-meta.xml
<CustomObject>
    <label>Region</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Centre__c/fields/Centre_Region__c.field-meta.xml
<CustomField>
    <fullName>Centre_Region__c</fullName>
    <label>Division</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Region is not active.</errorMessage>
        <filterItems>
            <field>Region__c.Region_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Region__c</referenceTo>
    <relationshipLabel>Regions</relationshipLabel>
    <relationshipName>Centres</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Division__c/Division__c.object-meta.xml
<CustomObject>
    <label>Group</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Division__c/fields/Div_Group__c.field-meta.xml
<CustomField>
    <fullName>Div_Group__c</fullName>
    <label>Bank</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Group is not active.</errorMessage>
        <filterItems>
            <field>Group__c.Group_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Group__c</referenceTo>
    <relationshipLabel>Groups</relationshipLabel>
    <relationshipName>Divisions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Group__c/Group__c.object-meta.xml
<CustomObject>
    <label>Bank</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Bank Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Banks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Region__c/Region__c.object-meta.xml
<CustomObject>
    <label>Division</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Division Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Divisions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Region__c/fields/Region_CommActual__c.field-meta.xml
<CustomField>
    <fullName>Region_CommActual__c</fullName>
    <label>Commodity Actual</label>
    <summarizedField>Centre__c.Centre_CommActual__c</summarizedField>
    <summaryForeignKey>Centre__c.Centre_Region__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Region__c/fields/Region_CommTarget__c.field-meta.xml
<CustomField>
    <fullName>Region_CommTarget__c</fullName>
    <label>Commodity Target</label>
    <summarizedField>Centre__c.Centre_CommTarget__c</summarizedField>
    <summaryForeignKey>Centre__c.Centre_Region__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Region__c/fields/Region_CRMActual__c.field-meta.xml
<CustomField>
    <fullName>Region_CRMActual__c</fullName>
    <label>CRM Actual</label>
    <summarizedField>Centre__c.Centre_CRMActual__c</summarizedField>
    <summaryForeignKey>Centre__c.Centre_Region__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Region__c/fields/Region_CRMTarget__c.field-meta.xml
<CustomField>
    <fullName>Region_CRMTarget__c</fullName>
    <label>CRM Target</label>
    <summarizedField>Centre__c.Centre_CRMTarget__c</summarizedField>
    <summaryForeignKey>Centre__c.Centre_Region__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Region__c/fields/Region_Division__c.field-meta.xml
<CustomField>
    <fullName>Region_Division__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Group</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Division is not active.</errorMessage>
        <filterItems>
            <field>Division__c.Div_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Division__c</referenceTo>
    <relationshipLabel>Divisions</relationshipLabel>
    <relationshipName>Regions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Region__c/fields/Region_FXDirectActual__c.field-meta.xml
<CustomField>
    <fullName>Region_FXDirectActual__c</fullName>
    <label>FX Direct Actual</label>
    <summarizedField>Centre__c.Centre_FXDirectActual__c</summarizedField>
    <summaryForeignKey>Centre__c.Centre_Region__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Region__c/fields/Region_FXDirectTarget__c.field-meta.xml
<CustomField>
    <fullName>Region_FXDirectTarget__c</fullName>
    <label>FX Direct Target</label>
    <summarizedField>Centre__c.Centre_FXDirectTarget__c</summarizedField>
    <summaryForeignKey>Centre__c.Centre_Region__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Region__c/fields/Region_FXIndirectActual__c.field-meta.xml
<CustomField>
    <fullName>Region_FXIndirectActual__c</fullName>
    <label>FX Indirect Actual</label>
    <summarizedField>Centre__c.Centre_FXIndirectActual__c</summarizedField>
    <summaryForeignKey>Centre__c.Centre_Region__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Region__c/fields/Region_FXIndirectTarget__c.field-meta.xml
<CustomField>
    <fullName>Region_FXIndirectTarget__c</fullName>
    <label>FX Indirect Target</label>
    <summarizedField>Centre__c.Centre_FXIndirectTarget__c</summarizedField>
    <summaryForeignKey>Centre__c.Centre_Region__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Region__c/fields/Region_IRRMActual__c.field-meta.xml
<CustomField>
    <fullName>Region_IRRMActual__c</fullName>
    <label>IRRM Actual</label>
    <summarizedField>Centre__c.Centre_IRRMActual__c</summarizedField>
    <summaryForeignKey>Centre__c.Centre_Region__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Region__c/fields/Region_IRRMTarget__c.field-meta.xml
<CustomField>
    <fullName>Region_IRRMTarget__c</fullName>
    <label>IRRM Target</label>
    <summarizedField>Centre__c.Centre_IRRMTarget__c</summarizedField>
    <summaryForeignKey>Centre__c.Centre_Region__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Business Centre</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Business Centre Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Centres</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Team__c/fields/Team_Centre__c.field-meta.xml
<CustomField>
    <fullName>Team_Centre__c</fullName>
    <label>Region</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Centre is not active.</errorMessage>
        <filterItems>
            <field>Centre__c.Centre_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Centre__c</referenceTo>
    <relationshipLabel>Business Centres</relationshipLabel>
    <relationshipName>Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TSMTarget__c/TSMTarget__c.object-meta.xml
<CustomObject>
    <description>To hold the target and actual for a TSM under specific Team</description>
    <label>FRSM Target</label>
    <nameField>
        <displayFormat>Target - {00000}</displayFormat>
        <label>FRSM Target No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FRSM Targets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_CommTarget__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_CommTarget__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Commodity Target</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_CRMTarget__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_CRMTarget__c</fullName>
    <defaultValue>0</defaultValue>
    <label>CRM Target</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_FXDirectTarget__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_FXDirectTarget__c</fullName>
    <defaultValue>0</defaultValue>
    <label>FX Direct Target</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_FXIndirectTarget__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_FXIndirectTarget__c</fullName>
    <defaultValue>0</defaultValue>
    <label>FX Indirect Target</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_IRRMTarget__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_IRRMTarget__c</fullName>
    <defaultValue>0</defaultValue>
    <label>IRRM Target</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_Team__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_Team__c</fullName>
    <label>Business Centre</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Team status is not active.</errorMessage>
        <filterItems>
            <field>Team__c.Team_Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Team__c</referenceTo>
    <relationshipName>TSMTargets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TSMTarget__c/fields/TSMTar_TSM__c.field-meta.xml
<CustomField>
    <fullName>TSMTar_TSM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Risk Solutions Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>TSMTargets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RegionTriggerHandler_Test.cls
/*
@Author        : Santhoshan
@Name          : RegionTriggerHandler_Test
@Created Date  : 12th Feb 2018
@Description   : This is a Test Class for RegionTriggerHandler
@version       : 1.0
*/

@isTest
public class RegionTriggerHandler_Test {
    /**
* @description       Test method to check the Region's Roll up Summary.
* @name              createOpportunity_Test
* @param             NA 
* @return            void
* @throws            NA
*/ 
    static testMethod void regionRollupSummary() {
        User ManagerUserTest = TestData.createMGRUser('System Administrator');
        insert ManagerUserTest;
        User userTest = TestData.createUser('CYB');
        userTest.ManagerId = ManagerUserTest.id;
        insert userTest;
        
        List<Region__c> regionQueryList = new List<Region__c>();
        List<TSMTarget__c> TSMTargetList = new List<TSMTarget__c>();        
        Group__c testGroup = TestData.createGroup();
        insert testGroup;        
        Division__c testDivision = TestData.createDivision();
        testDivision.Div_Group__c=testGroup.Id;       
        insert testDivision;        
        Region__c testRegion = TestData.createRegion();
        testRegion.Region_Division__c=testDivision.id;        
        insert testRegion;        
        Centre__c testCentre = TestData.createCentre();
        testCentre.Centre_Region__c=testRegion.id;        
        insert testCentre;        
        Team__c testTeam = TestData.createTeam();
        testTeam.Team_Centre__c = testCentre.id;        
        insert testTeam;        
        TSMTarget__c testTarget = TestData.createTSMTarget();
        testTarget.TSMTar_Team__c = testTeam.id;
        testTarget.TSMTar_TSM__c = userTest.id;
        TSMTargetList.add(testTarget);        
        TSMTarget__c testTarget2 = TestData.createTSMTarget();
        testTarget2.TSMTar_Team__c = testTeam.id;
        testTarget2.TSMTar_TSM__c = userTest.id;
        TSMTargetList.add(testTarget2);      	            
        insert TSMTargetList;       
        System.runAs(userTest) {
            Test.startTest();
            testTarget.TSMTar_FXDirectTarget__c = 500;
            testTarget.TSMTar_FXIndirectTarget__c = 600;
            testTarget.TSMTar_CRMTarget__c = 700;
            testTarget.TSMTar_CommTarget__c = 800;
            testTarget.TSMTar_IRRMTarget__c = 900;
            update testTarget;
            Test.stopTest();
        }               
        regionQueryList = [SELECT Region_FXDirectTarget__c, Region_FXIndirectTarget__c,
                           Region_CRMTarget__c, Region_CommTarget__c, Region_IRRMTarget__c,
                           Region_FXDirectActual__c, Region_FXIndirectActual__c,
                           Region_CRMActual__c, Region_CommActual__c,
                           Region_IRRMActual__c FROM Region__c 
                           WHERE Name='Test Region'];
        
        System.assertEquals(1000, regionQueryList[0].Region_FXDirectTarget__c);
        System.assertEquals(1100, regionQueryList[0].Region_FXIndirectTarget__c);
        System.assertEquals(1200, regionQueryList[0].Region_CRMTarget__c);
        System.assertEquals(1300, regionQueryList[0].Region_CommTarget__c);
        System.assertEquals(1400, regionQueryList[0].Region_IRRMTarget__c);
        
    }    
}